// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/augno/api/services/auth-service/internal/domain (interfaces: TokenSvc)
//
// Generated by this command:
//
//	mockgen -destination /Users/danealbaugh/Code/augno/api/services/auth-service/internal/domain/mock/service/token_svc_mock.go -package servicemock github.com/augno/api/services/auth-service/internal/domain TokenSvc
//

// Package servicemock is a generated GoMock package.
package servicemock

import (
	context "context"
	reflect "reflect"

	domain "github.com/augno/api/services/auth-service/internal/domain"
	apierror "github.com/augno/api/shared/errors"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenSvc is a mock of TokenSvc interface.
type MockTokenSvc struct {
	ctrl     *gomock.Controller
	recorder *MockTokenSvcMockRecorder
	isgomock struct{}
}

// MockTokenSvcMockRecorder is the mock recorder for MockTokenSvc.
type MockTokenSvcMockRecorder struct {
	mock *MockTokenSvc
}

// NewMockTokenSvc creates a new mock instance.
func NewMockTokenSvc(ctrl *gomock.Controller) *MockTokenSvc {
	mock := &MockTokenSvc{ctrl: ctrl}
	mock.recorder = &MockTokenSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenSvc) EXPECT() *MockTokenSvcMockRecorder {
	return m.recorder
}

// RefreshToken mocks base method.
func (m *MockTokenSvc) RefreshToken(ctx context.Context, refreshToken string) (*domain.RefreshTokenResult, *apierror.APIError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, refreshToken)
	ret0, _ := ret[0].(*domain.RefreshTokenResult)
	ret1, _ := ret[1].(*apierror.APIError)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockTokenSvcMockRecorder) RefreshToken(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockTokenSvc)(nil).RefreshToken), ctx, refreshToken)
}

// RevokeRefreshToken mocks base method.
func (m *MockTokenSvc) RevokeRefreshToken(ctx context.Context, refreshToken string) *apierror.APIError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeRefreshToken", ctx, refreshToken)
	ret0, _ := ret[0].(*apierror.APIError)
	return ret0
}

// RevokeRefreshToken indicates an expected call of RevokeRefreshToken.
func (mr *MockTokenSvcMockRecorder) RevokeRefreshToken(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeRefreshToken", reflect.TypeOf((*MockTokenSvc)(nil).RevokeRefreshToken), ctx, refreshToken)
}
