// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/augno/api/shared/db"
	"github.com/jackc/pgx/v5/pgtype"
)

type AgentAccountStatus struct {
	ID                string
	AccountID         string
	AgentDefinitionID string
	StatusCode        string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type AgentAction struct {
	ID                  string
	AccountID           string
	AgentRunID          string
	ToolSlug            string
	StatusCode          string
	Label               pgtype.Text
	Description         pgtype.Text
	Input               []byte
	Output              []byte
	ErrorMessage        pgtype.Text
	EntityType          pgtype.Text
	EntityID            pgtype.Text
	RequiresReview      bool
	ReviewedAt          pgtype.Timestamptz
	ReviewedBy          pgtype.Text
	ReviewedByActorType pgtype.Text
	ReviewedByActorName pgtype.Text
	ExecutedAt          pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type AgentAlert struct {
	ID                      string
	AccountID               string
	AgentRunID              pgtype.Text
	AgentActionID           pgtype.Text
	SeverityCode            string
	StatusCode              string
	Title                   string
	Message                 pgtype.Text
	Metadata                []byte
	AcknowledgedAt          pgtype.Timestamptz
	AcknowledgedByActorID   pgtype.Text
	AcknowledgedByActorType pgtype.Text
	AcknowledgedByActorName pgtype.Text
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

type AgentArtifact struct {
	ID            string
	AccountID     string
	AgentActionID string
	ArtifactType  string
	Name          string
	Content       pgtype.Text
	Metadata      []byte
	S3Key         pgtype.Text
	MimeType      pgtype.Text
	SizeBytes     pgtype.Int8
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type AgentConfig struct {
	ID                string
	AccountID         string
	AgentDefinitionID string
	IsEnabled         bool
	Config            []byte
	Schedule          pgtype.Text
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type AgentDefinition struct {
	ID             string
	AccountID      pgtype.Text
	Name           string
	Slug           string
	Description    pgtype.Text
	DefinitionType string
	CategoryCode   string
	TriggerType    string
	IsActive       bool
	Config         []byte
	RoleID         pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type AgentDefinitionTool struct {
	ID                string
	AgentDefinitionID string
	ToolDefinitionID  string
	Config            []byte
	SortOrder         int32
	RequireReview     bool
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type AgentMemory struct {
	ID         string
	AccountID  string
	Category   string
	Content    string
	Metadata   []byte
	EntityType pgtype.Text
	EntityID   pgtype.Text
	Importance float64
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type AgentRun struct {
	ID                      string
	AccountID               string
	AgentDefinitionID       string
	AgentConfigID           pgtype.Text
	StatusCode              string
	TriggerType             string
	Input                   []byte
	Output                  []byte
	ErrorMessage            pgtype.Text
	StartedAt               pgtype.Timestamptz
	CompletedAt             pgtype.Timestamptz
	DurationMs              pgtype.Int4
	TotalInputTokens        int64
	TotalOutputTokens       int64
	TriggeredByActorID      pgtype.Text
	TriggeredByIdentityType pgtype.Text
	TriggeredByActorName    pgtype.Text
	AllowedToolSlugs        []byte
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

type AgentRunEvent struct {
	ID            string
	AgentRunID    string
	AccountID     string
	StepType      string
	Title         string
	Content       pgtype.Text
	Sequence      int32
	DurationMs    pgtype.Int4
	AgentActionID pgtype.Text
	Metadata      []byte
	ActorID       pgtype.Text
	ActorType     pgtype.Text
	ActorName     pgtype.Text
	CreatedAt     pgtype.Timestamptz
}

type AgentTokenUsage struct {
	ID           string
	AccountID    string
	Date         pgtype.Date
	InputTokens  int64
	OutputTokens int64
	TotalCost    float64
	RunCount     int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type DeletedRecord struct {
	ID           int64
	DeletedAt    pgtype.Timestamptz
	ResourceType string
	ResourceID   string
	Data         []byte
}

type MessageInbox struct {
	ID              int64
	MessageID       string
	ServiceName     string
	Handler         string
	MessageType     string
	RequestID       pgtype.Text
	ParentMessageID pgtype.Text
	Status          string
	Attempts        int32
	LastError       pgtype.Text
	ReceivedAt      pgtype.Timestamptz
	ProcessedAt     pgtype.Timestamptz
}

type MessageOutbox struct {
	ID              int64
	MessageID       string
	ServiceName     string
	MessageType     string
	Destination     string
	RoutingKey      pgtype.Text
	Headers         db.NullableRawMessage
	Payload         []byte
	Status          string
	Attempts        int32
	MaxAttempts     int32
	NextRunAt       pgtype.Timestamptz
	LockedAt        pgtype.Timestamptz
	LockOwner       pgtype.Text
	LockExpiresAt   pgtype.Timestamptz
	LastError       pgtype.Text
	PublishedAt     pgtype.Timestamptz
	RequestID       pgtype.Text
	ParentMessageID pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type ServiceIdempotencyKey struct {
	ID             int64
	TypeID         string
	ServiceName    string
	Handler        string
	IdempotencyKey string
	ActorID        pgtype.Text
	IdentityType   string
	ScopeHash      string
	ResponseCode   pgtype.Int4
	ResponseBody   []byte
	RecoveryPoint  string
	LockedAt       pgtype.Timestamptz
	LockOwner      pgtype.Text
	LockExpiresAt  pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	LastRunAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
}

type TaskLease struct {
	Name       string
	Holder     string
	AcquiredAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
}

type ToolDefinition struct {
	ID                  string
	DisplayName         string
	Description         pgtype.Text
	ConfigSchema        []byte
	Slug                pgtype.Text
	InputSchema         []byte
	Category            string
	ToolGroupID         pgtype.Text
	RequiredPermissions []byte
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type ToolGroup struct {
	ID          string
	Name        string
	Description pgtype.Text
	Slug        string
	Icon        pgtype.Text
	SortOrder   int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
