// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: doc_api_key.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createDocAPIKey = `-- name: CreateDocAPIKey :execresult
INSERT INTO doc_api_key (type_id, api_key_id, encrypted_secret, created_at, updated_at)
VALUES (?, ?, ?, NOW(3), NOW(3))
`

type CreateDocAPIKeyParams struct {
	TypeID          string
	ApiKeyID        string
	EncryptedSecret string
}

func (q *Queries) CreateDocAPIKey(ctx context.Context, arg CreateDocAPIKeyParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDocAPIKey, arg.TypeID, arg.ApiKeyID, arg.EncryptedSecret)
}

const deleteDocAPIKeyByAPIKeyID = `-- name: DeleteDocAPIKeyByAPIKeyID :exec
DELETE FROM doc_api_key WHERE api_key_id = ?
`

func (q *Queries) DeleteDocAPIKeyByAPIKeyID(ctx context.Context, apiKeyID string) error {
	_, err := q.db.ExecContext(ctx, deleteDocAPIKeyByAPIKeyID, apiKeyID)
	return err
}

const deleteDocAPIKeyByID = `-- name: DeleteDocAPIKeyByID :exec
DELETE FROM doc_api_key WHERE id = ?
`

func (q *Queries) DeleteDocAPIKeyByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDocAPIKeyByID, id)
	return err
}

const findDocAPIKeyByAPIKeyID = `-- name: FindDocAPIKeyByAPIKeyID :one
SELECT id, type_id, api_key_id, encrypted_secret, created_at, updated_at
FROM doc_api_key WHERE api_key_id = ? LIMIT 1
`

func (q *Queries) FindDocAPIKeyByAPIKeyID(ctx context.Context, apiKeyID string) (DocApiKey, error) {
	row := q.db.QueryRowContext(ctx, findDocAPIKeyByAPIKeyID, apiKeyID)
	var i DocApiKey
	err := row.Scan(
		&i.ID,
		&i.TypeID,
		&i.ApiKeyID,
		&i.EncryptedSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findDocAPIKeyBySandboxAccountID = `-- name: FindDocAPIKeyBySandboxAccountID :one
SELECT
    dak.id, dak.type_id, dak.api_key_id, dak.encrypted_secret,
    dak.created_at, dak.updated_at,
    ak.expires_at AS ak_expires_at, ak.revoked_at AS ak_revoked_at
FROM doc_api_key dak
JOIN api_key ak ON dak.api_key_id = ak.type_id
WHERE ak.owner_account_id = ?
ORDER BY dak.id DESC
LIMIT 1
`

type FindDocAPIKeyBySandboxAccountIDRow struct {
	ID              int64
	TypeID          string
	ApiKeyID        string
	EncryptedSecret string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	AkExpiresAt     sql.NullTime
	AkRevokedAt     sql.NullTime
}

func (q *Queries) FindDocAPIKeyBySandboxAccountID(ctx context.Context, ownerAccountID string) (FindDocAPIKeyBySandboxAccountIDRow, error) {
	row := q.db.QueryRowContext(ctx, findDocAPIKeyBySandboxAccountID, ownerAccountID)
	var i FindDocAPIKeyBySandboxAccountIDRow
	err := row.Scan(
		&i.ID,
		&i.TypeID,
		&i.ApiKeyID,
		&i.EncryptedSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AkExpiresAt,
		&i.AkRevokedAt,
	)
	return i, err
}

const updateDocAPIKey = `-- name: UpdateDocAPIKey :exec
UPDATE doc_api_key SET api_key_id = ?, encrypted_secret = ?, updated_at = NOW(3) WHERE id = ?
`

type UpdateDocAPIKeyParams struct {
	ApiKeyID        string
	EncryptedSecret string
	ID              int64
}

func (q *Queries) UpdateDocAPIKey(ctx context.Context, arg UpdateDocAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, updateDocAPIKey, arg.ApiKeyID, arg.EncryptedSecret, arg.ID)
	return err
}
