// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registration_session.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const completeRegistrationSession = `-- name: CompleteRegistrationSession :exec
UPDATE registration_session
SET completed_at = NOW(3), account_id = ?, updated_at = NOW(3)
WHERE id = ?
`

type CompleteRegistrationSessionParams struct {
	AccountID sql.NullString
	ID        int64
}

func (q *Queries) CompleteRegistrationSession(ctx context.Context, arg CompleteRegistrationSessionParams) error {
	_, err := q.db.ExecContext(ctx, completeRegistrationSession, arg.AccountID, arg.ID)
	return err
}

const createRegistrationSession = `-- name: CreateRegistrationSession :execresult
INSERT INTO registration_session (
    type_id, email, plan_code, step, verification_token, is_email_verified,
    is_existing_user, session_data, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, NOW(3), NOW(3))
`

type CreateRegistrationSessionParams struct {
	TypeID            string
	Email             string
	PlanCode          string
	Step              string
	VerificationToken string
	IsEmailVerified   bool
	IsExistingUser    sql.NullBool
	SessionData       json.RawMessage
}

func (q *Queries) CreateRegistrationSession(ctx context.Context, arg CreateRegistrationSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRegistrationSession,
		arg.TypeID,
		arg.Email,
		arg.PlanCode,
		arg.Step,
		arg.VerificationToken,
		arg.IsEmailVerified,
		arg.IsExistingUser,
		arg.SessionData,
	)
}

const deleteRegistrationSession = `-- name: DeleteRegistrationSession :exec
DELETE FROM registration_session
WHERE id = ?
`

func (q *Queries) DeleteRegistrationSession(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRegistrationSession, id)
	return err
}

const getRegistrationSessionByEmail = `-- name: GetRegistrationSessionByEmail :one
SELECT id, type_id, email, plan_code, step, verification_token, is_email_verified,
       is_existing_user, user_id, account_id, stripe_customer_id,
       stripe_checkout_session_id, stripe_subscription_id, payment_completed, session_data,
       completed_at, created_at, updated_at
FROM registration_session
WHERE email = ?
AND completed_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetRegistrationSessionByEmail(ctx context.Context, email string) (RegistrationSession, error) {
	row := q.db.QueryRowContext(ctx, getRegistrationSessionByEmail, email)
	var i RegistrationSession
	err := row.Scan(
		&i.ID,
		&i.TypeID,
		&i.Email,
		&i.PlanCode,
		&i.Step,
		&i.VerificationToken,
		&i.IsEmailVerified,
		&i.IsExistingUser,
		&i.UserID,
		&i.AccountID,
		&i.StripeCustomerID,
		&i.StripeCheckoutSessionID,
		&i.StripeSubscriptionID,
		&i.PaymentCompleted,
		&i.SessionData,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRegistrationSessionByID = `-- name: GetRegistrationSessionByID :one
SELECT id, type_id, email, plan_code, step, verification_token, is_email_verified,
       is_existing_user, user_id, account_id, stripe_customer_id,
       stripe_checkout_session_id, stripe_subscription_id, payment_completed, session_data,
       completed_at, created_at, updated_at
FROM registration_session
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetRegistrationSessionByID(ctx context.Context, id int64) (RegistrationSession, error) {
	row := q.db.QueryRowContext(ctx, getRegistrationSessionByID, id)
	var i RegistrationSession
	err := row.Scan(
		&i.ID,
		&i.TypeID,
		&i.Email,
		&i.PlanCode,
		&i.Step,
		&i.VerificationToken,
		&i.IsEmailVerified,
		&i.IsExistingUser,
		&i.UserID,
		&i.AccountID,
		&i.StripeCustomerID,
		&i.StripeCheckoutSessionID,
		&i.StripeSubscriptionID,
		&i.PaymentCompleted,
		&i.SessionData,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRegistrationSessionByToken = `-- name: GetRegistrationSessionByToken :one
SELECT id, type_id, email, plan_code, step, verification_token, is_email_verified,
       is_existing_user, user_id, account_id, stripe_customer_id,
       stripe_checkout_session_id, stripe_subscription_id, payment_completed, session_data,
       completed_at, created_at, updated_at
FROM registration_session
WHERE verification_token = ?
LIMIT 1
`

func (q *Queries) GetRegistrationSessionByToken(ctx context.Context, verificationToken string) (RegistrationSession, error) {
	row := q.db.QueryRowContext(ctx, getRegistrationSessionByToken, verificationToken)
	var i RegistrationSession
	err := row.Scan(
		&i.ID,
		&i.TypeID,
		&i.Email,
		&i.PlanCode,
		&i.Step,
		&i.VerificationToken,
		&i.IsEmailVerified,
		&i.IsExistingUser,
		&i.UserID,
		&i.AccountID,
		&i.StripeCustomerID,
		&i.StripeCheckoutSessionID,
		&i.StripeSubscriptionID,
		&i.PaymentCompleted,
		&i.SessionData,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRegistrationSessionByTypeID = `-- name: GetRegistrationSessionByTypeID :one
SELECT id, type_id, email, plan_code, step, verification_token, is_email_verified,
       is_existing_user, user_id, account_id, stripe_customer_id,
       stripe_checkout_session_id, stripe_subscription_id, payment_completed, session_data,
       completed_at, created_at, updated_at
FROM registration_session
WHERE type_id = ?
LIMIT 1
`

func (q *Queries) GetRegistrationSessionByTypeID(ctx context.Context, typeID string) (RegistrationSession, error) {
	row := q.db.QueryRowContext(ctx, getRegistrationSessionByTypeID, typeID)
	var i RegistrationSession
	err := row.Scan(
		&i.ID,
		&i.TypeID,
		&i.Email,
		&i.PlanCode,
		&i.Step,
		&i.VerificationToken,
		&i.IsEmailVerified,
		&i.IsExistingUser,
		&i.UserID,
		&i.AccountID,
		&i.StripeCustomerID,
		&i.StripeCheckoutSessionID,
		&i.StripeSubscriptionID,
		&i.PaymentCompleted,
		&i.SessionData,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRegistrationSessionsByUserIDBackward = `-- name: ListRegistrationSessionsByUserIDBackward :many
SELECT id, type_id, email, plan_code, step, verification_token, is_email_verified,
       is_existing_user, user_id, account_id, stripe_customer_id,
       stripe_checkout_session_id, stripe_subscription_id, payment_completed, session_data,
       completed_at, created_at, updated_at
FROM registration_session
WHERE registration_session.user_id = ?
  AND registration_session.completed_at IS NULL
  AND (
    registration_session.created_at > ?
    OR (registration_session.created_at = ? AND registration_session.id > ?)
  )
ORDER BY registration_session.created_at ASC, registration_session.id ASC
LIMIT ?
`

type ListRegistrationSessionsByUserIDBackwardParams struct {
	UserID          sql.NullString
	CursorCreatedAt time.Time
	CursorID        int64
	Limit           int32
}

func (q *Queries) ListRegistrationSessionsByUserIDBackward(ctx context.Context, arg ListRegistrationSessionsByUserIDBackwardParams) ([]RegistrationSession, error) {
	rows, err := q.db.QueryContext(ctx, listRegistrationSessionsByUserIDBackward,
		arg.UserID,
		arg.CursorCreatedAt,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegistrationSession
	for rows.Next() {
		var i RegistrationSession
		if err := rows.Scan(
			&i.ID,
			&i.TypeID,
			&i.Email,
			&i.PlanCode,
			&i.Step,
			&i.VerificationToken,
			&i.IsEmailVerified,
			&i.IsExistingUser,
			&i.UserID,
			&i.AccountID,
			&i.StripeCustomerID,
			&i.StripeCheckoutSessionID,
			&i.StripeSubscriptionID,
			&i.PaymentCompleted,
			&i.SessionData,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistrationSessionsByUserIDForward = `-- name: ListRegistrationSessionsByUserIDForward :many
SELECT id, type_id, email, plan_code, step, verification_token, is_email_verified,
       is_existing_user, user_id, account_id, stripe_customer_id,
       stripe_checkout_session_id, stripe_subscription_id, payment_completed, session_data,
       completed_at, created_at, updated_at
FROM registration_session
WHERE registration_session.user_id = ?
  AND registration_session.completed_at IS NULL
  AND (
    ? IS NULL
    OR registration_session.created_at < ?
    OR (registration_session.created_at = ? AND registration_session.id < ?)
  )
ORDER BY registration_session.created_at DESC, registration_session.id DESC
LIMIT ?
`

type ListRegistrationSessionsByUserIDForwardParams struct {
	UserID          sql.NullString
	CursorCreatedAt sql.NullTime
	CursorID        sql.NullInt64
	Limit           int32
}

func (q *Queries) ListRegistrationSessionsByUserIDForward(ctx context.Context, arg ListRegistrationSessionsByUserIDForwardParams) ([]RegistrationSession, error) {
	rows, err := q.db.QueryContext(ctx, listRegistrationSessionsByUserIDForward,
		arg.UserID,
		arg.CursorCreatedAt,
		arg.CursorCreatedAt,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegistrationSession
	for rows.Next() {
		var i RegistrationSession
		if err := rows.Scan(
			&i.ID,
			&i.TypeID,
			&i.Email,
			&i.PlanCode,
			&i.Step,
			&i.VerificationToken,
			&i.IsEmailVerified,
			&i.IsExistingUser,
			&i.UserID,
			&i.AccountID,
			&i.StripeCustomerID,
			&i.StripeCheckoutSessionID,
			&i.StripeSubscriptionID,
			&i.PaymentCompleted,
			&i.SessionData,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRegistrationSessionAccountID = `-- name: UpdateRegistrationSessionAccountID :exec
UPDATE registration_session
SET account_id = ?, updated_at = NOW(3)
WHERE id = ?
`

type UpdateRegistrationSessionAccountIDParams struct {
	AccountID sql.NullString
	ID        int64
}

func (q *Queries) UpdateRegistrationSessionAccountID(ctx context.Context, arg UpdateRegistrationSessionAccountIDParams) error {
	_, err := q.db.ExecContext(ctx, updateRegistrationSessionAccountID, arg.AccountID, arg.ID)
	return err
}

const updateRegistrationSessionEmailVerified = `-- name: UpdateRegistrationSessionEmailVerified :exec
UPDATE registration_session
SET is_email_verified = ?, is_existing_user = ?, updated_at = NOW(3)
WHERE id = ?
`

type UpdateRegistrationSessionEmailVerifiedParams struct {
	IsEmailVerified bool
	IsExistingUser  sql.NullBool
	ID              int64
}

func (q *Queries) UpdateRegistrationSessionEmailVerified(ctx context.Context, arg UpdateRegistrationSessionEmailVerifiedParams) error {
	_, err := q.db.ExecContext(ctx, updateRegistrationSessionEmailVerified, arg.IsEmailVerified, arg.IsExistingUser, arg.ID)
	return err
}

const updateRegistrationSessionPaymentCompleted = `-- name: UpdateRegistrationSessionPaymentCompleted :exec
UPDATE registration_session
SET payment_completed = ?, stripe_subscription_id = ?, updated_at = NOW(3)
WHERE id = ?
`

type UpdateRegistrationSessionPaymentCompletedParams struct {
	PaymentCompleted     bool
	StripeSubscriptionID sql.NullString
	ID                   int64
}

func (q *Queries) UpdateRegistrationSessionPaymentCompleted(ctx context.Context, arg UpdateRegistrationSessionPaymentCompletedParams) error {
	_, err := q.db.ExecContext(ctx, updateRegistrationSessionPaymentCompleted, arg.PaymentCompleted, arg.StripeSubscriptionID, arg.ID)
	return err
}

const updateRegistrationSessionPlanCode = `-- name: UpdateRegistrationSessionPlanCode :exec
UPDATE registration_session
SET plan_code = ?, updated_at = NOW(3)
WHERE id = ?
`

type UpdateRegistrationSessionPlanCodeParams struct {
	PlanCode string
	ID       int64
}

func (q *Queries) UpdateRegistrationSessionPlanCode(ctx context.Context, arg UpdateRegistrationSessionPlanCodeParams) error {
	_, err := q.db.ExecContext(ctx, updateRegistrationSessionPlanCode, arg.PlanCode, arg.ID)
	return err
}

const updateRegistrationSessionStep = `-- name: UpdateRegistrationSessionStep :exec
UPDATE registration_session
SET step = ?, session_data = ?, updated_at = NOW(3)
WHERE id = ?
`

type UpdateRegistrationSessionStepParams struct {
	Step        string
	SessionData json.RawMessage
	ID          int64
}

func (q *Queries) UpdateRegistrationSessionStep(ctx context.Context, arg UpdateRegistrationSessionStepParams) error {
	_, err := q.db.ExecContext(ctx, updateRegistrationSessionStep, arg.Step, arg.SessionData, arg.ID)
	return err
}

const updateRegistrationSessionStripeCustomer = `-- name: UpdateRegistrationSessionStripeCustomer :exec
UPDATE registration_session
SET stripe_customer_id = ?, stripe_checkout_session_id = ?, updated_at = NOW(3)
WHERE id = ?
`

type UpdateRegistrationSessionStripeCustomerParams struct {
	StripeCustomerID        sql.NullString
	StripeCheckoutSessionID sql.NullString
	ID                      int64
}

func (q *Queries) UpdateRegistrationSessionStripeCustomer(ctx context.Context, arg UpdateRegistrationSessionStripeCustomerParams) error {
	_, err := q.db.ExecContext(ctx, updateRegistrationSessionStripeCustomer, arg.StripeCustomerID, arg.StripeCheckoutSessionID, arg.ID)
	return err
}

const updateRegistrationSessionToken = `-- name: UpdateRegistrationSessionToken :exec
UPDATE registration_session
SET verification_token = ?, updated_at = NOW(3)
WHERE id = ?
`

type UpdateRegistrationSessionTokenParams struct {
	VerificationToken string
	ID                int64
}

func (q *Queries) UpdateRegistrationSessionToken(ctx context.Context, arg UpdateRegistrationSessionTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateRegistrationSessionToken, arg.VerificationToken, arg.ID)
	return err
}

const updateRegistrationSessionUser = `-- name: UpdateRegistrationSessionUser :exec
UPDATE registration_session
SET user_id = ?, session_data = ?, updated_at = NOW(3)
WHERE id = ?
`

type UpdateRegistrationSessionUserParams struct {
	UserID      sql.NullString
	SessionData json.RawMessage
	ID          int64
}

func (q *Queries) UpdateRegistrationSessionUser(ctx context.Context, arg UpdateRegistrationSessionUserParams) error {
	_, err := q.db.ExecContext(ctx, updateRegistrationSessionUser, arg.UserID, arg.SessionData, arg.ID)
	return err
}
