// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/augno/api/services/core-service/internal/domain (interfaces: AccountSvc)
//
// Generated by this command:
//
//	mockgen -destination /Users/dane/Code/augno/api/services/core-service/internal/domain/mock/service/account_svc_mock.go -package servicemock github.com/augno/api/services/core-service/internal/domain AccountSvc
//

// Package servicemock is a generated GoMock package.
package servicemock

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/augno/api/services/core-service/internal/domain"
	apierror "github.com/augno/api/shared/errors"
	gomock "go.uber.org/mock/gomock"
)

// MockAccountSvc is a mock of AccountSvc interface.
type MockAccountSvc struct {
	ctrl     *gomock.Controller
	recorder *MockAccountSvcMockRecorder
	isgomock struct{}
}

// MockAccountSvcMockRecorder is the mock recorder for MockAccountSvc.
type MockAccountSvcMockRecorder struct {
	mock *MockAccountSvc
}

// NewMockAccountSvc creates a new mock instance.
func NewMockAccountSvc(ctrl *gomock.Controller) *MockAccountSvc {
	mock := &MockAccountSvc{ctrl: ctrl}
	mock.recorder = &MockAccountSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountSvc) EXPECT() *MockAccountSvcMockRecorder {
	return m.recorder
}

// ClearAccountStripeCustomer mocks base method.
func (m *MockAccountSvc) ClearAccountStripeCustomer(ctx context.Context, accountID string) *apierror.APIError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearAccountStripeCustomer", ctx, accountID)
	ret0, _ := ret[0].(*apierror.APIError)
	return ret0
}

// ClearAccountStripeCustomer indicates an expected call of ClearAccountStripeCustomer.
func (mr *MockAccountSvcMockRecorder) ClearAccountStripeCustomer(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearAccountStripeCustomer", reflect.TypeOf((*MockAccountSvc)(nil).ClearAccountStripeCustomer), ctx, accountID)
}

// CompleteRegistration mocks base method.
func (m *MockAccountSvc) CompleteRegistration(ctx context.Context, input domain.CompleteRegistrationInput) (*domain.CompleteRegistrationOutput, *apierror.APIError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteRegistration", ctx, input)
	ret0, _ := ret[0].(*domain.CompleteRegistrationOutput)
	ret1, _ := ret[1].(*apierror.APIError)
	return ret0, ret1
}

// CompleteRegistration indicates an expected call of CompleteRegistration.
func (mr *MockAccountSvcMockRecorder) CompleteRegistration(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteRegistration", reflect.TypeOf((*MockAccountSvc)(nil).CompleteRegistration), ctx, input)
}

// GetAccountByStripeCustomerID mocks base method.
func (m *MockAccountSvc) GetAccountByStripeCustomerID(ctx context.Context, stripeCustomerID string) (string, string, *apierror.APIError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByStripeCustomerID", ctx, stripeCustomerID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(*apierror.APIError)
	return ret0, ret1, ret2
}

// GetAccountByStripeCustomerID indicates an expected call of GetAccountByStripeCustomerID.
func (mr *MockAccountSvcMockRecorder) GetAccountByStripeCustomerID(ctx, stripeCustomerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByStripeCustomerID", reflect.TypeOf((*MockAccountSvc)(nil).GetAccountByStripeCustomerID), ctx, stripeCustomerID)
}

// GetAccountContext mocks base method.
func (m *MockAccountSvc) GetAccountContext(ctx context.Context, accountID string) (*domain.AccountContext, *apierror.APIError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountContext", ctx, accountID)
	ret0, _ := ret[0].(*domain.AccountContext)
	ret1, _ := ret[1].(*apierror.APIError)
	return ret0, ret1
}

// GetAccountContext indicates an expected call of GetAccountContext.
func (mr *MockAccountSvcMockRecorder) GetAccountContext(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountContext", reflect.TypeOf((*MockAccountSvc)(nil).GetAccountContext), ctx, accountID)
}

// GetAccountRelationByAPIKeyID mocks base method.
func (m *MockAccountSvc) GetAccountRelationByAPIKeyID(ctx context.Context, ownerAccountID string, apiKeyID int64) (*domain.AccountRelation, *apierror.APIError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountRelationByAPIKeyID", ctx, ownerAccountID, apiKeyID)
	ret0, _ := ret[0].(*domain.AccountRelation)
	ret1, _ := ret[1].(*apierror.APIError)
	return ret0, ret1
}

// GetAccountRelationByAPIKeyID indicates an expected call of GetAccountRelationByAPIKeyID.
func (mr *MockAccountSvcMockRecorder) GetAccountRelationByAPIKeyID(ctx, ownerAccountID, apiKeyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountRelationByAPIKeyID", reflect.TypeOf((*MockAccountSvc)(nil).GetAccountRelationByAPIKeyID), ctx, ownerAccountID, apiKeyID)
}

// GetAccountRelationByUserID mocks base method.
func (m *MockAccountSvc) GetAccountRelationByUserID(ctx context.Context, ownerAccountID, userID string) (*domain.AccountRelation, *apierror.APIError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountRelationByUserID", ctx, ownerAccountID, userID)
	ret0, _ := ret[0].(*domain.AccountRelation)
	ret1, _ := ret[1].(*apierror.APIError)
	return ret0, ret1
}

// GetAccountRelationByUserID indicates an expected call of GetAccountRelationByUserID.
func (mr *MockAccountSvcMockRecorder) GetAccountRelationByUserID(ctx, ownerAccountID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountRelationByUserID", reflect.TypeOf((*MockAccountSvc)(nil).GetAccountRelationByUserID), ctx, ownerAccountID, userID)
}

// GetAdminRole mocks base method.
func (m *MockAccountSvc) GetAdminRole(ctx context.Context) (string, *apierror.APIError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminRole", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*apierror.APIError)
	return ret0, ret1
}

// GetAdminRole indicates an expected call of GetAdminRole.
func (mr *MockAccountSvcMockRecorder) GetAdminRole(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminRole", reflect.TypeOf((*MockAccountSvc)(nil).GetAdminRole), ctx)
}

// GetRolePermissions mocks base method.
func (m *MockAccountSvc) GetRolePermissions(ctx context.Context, roleID string) (map[string]bool, *apierror.APIError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRolePermissions", ctx, roleID)
	ret0, _ := ret[0].(map[string]bool)
	ret1, _ := ret[1].(*apierror.APIError)
	return ret0, ret1
}

// GetRolePermissions indicates an expected call of GetRolePermissions.
func (mr *MockAccountSvcMockRecorder) GetRolePermissions(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRolePermissions", reflect.TypeOf((*MockAccountSvc)(nil).GetRolePermissions), ctx, roleID)
}

// GetUserAccountAccess mocks base method.
func (m *MockAccountSvc) GetUserAccountAccess(ctx context.Context, userID, accountID string) (*domain.AccountUserAccess, bool, *apierror.APIError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAccountAccess", ctx, userID, accountID)
	ret0, _ := ret[0].(*domain.AccountUserAccess)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(*apierror.APIError)
	return ret0, ret1, ret2
}

// GetUserAccountAccess indicates an expected call of GetUserAccountAccess.
func (mr *MockAccountSvcMockRecorder) GetUserAccountAccess(ctx, userID, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAccountAccess", reflect.TypeOf((*MockAccountSvc)(nil).GetUserAccountAccess), ctx, userID, accountID)
}

// ListUserAccountAffiliations mocks base method.
func (m *MockAccountSvc) ListUserAccountAffiliations(ctx context.Context, userID string) ([]domain.AccountAffiliation, *string, *apierror.APIError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserAccountAffiliations", ctx, userID)
	ret0, _ := ret[0].([]domain.AccountAffiliation)
	ret1, _ := ret[1].(*string)
	ret2, _ := ret[2].(*apierror.APIError)
	return ret0, ret1, ret2
}

// ListUserAccountAffiliations indicates an expected call of ListUserAccountAffiliations.
func (mr *MockAccountSvcMockRecorder) ListUserAccountAffiliations(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserAccountAffiliations", reflect.TypeOf((*MockAccountSvc)(nil).ListUserAccountAffiliations), ctx, userID)
}

// MarkAccountUserUsed mocks base method.
func (m *MockAccountSvc) MarkAccountUserUsed(ctx context.Context, accountUserID string) *apierror.APIError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAccountUserUsed", ctx, accountUserID)
	ret0, _ := ret[0].(*apierror.APIError)
	return ret0
}

// MarkAccountUserUsed indicates an expected call of MarkAccountUserUsed.
func (mr *MockAccountSvcMockRecorder) MarkAccountUserUsed(ctx, accountUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAccountUserUsed", reflect.TypeOf((*MockAccountSvc)(nil).MarkAccountUserUsed), ctx, accountUserID)
}

// UpdateAccountSubscription mocks base method.
func (m *MockAccountSvc) UpdateAccountSubscription(ctx context.Context, accountID string, status *string, planCode string, stripeSubID *string, periodEnd *time.Time, stripeCustomerID *string) *apierror.APIError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccountSubscription", ctx, accountID, status, planCode, stripeSubID, periodEnd, stripeCustomerID)
	ret0, _ := ret[0].(*apierror.APIError)
	return ret0
}

// UpdateAccountSubscription indicates an expected call of UpdateAccountSubscription.
func (mr *MockAccountSvcMockRecorder) UpdateAccountSubscription(ctx, accountID, status, planCode, stripeSubID, periodEnd, stripeCustomerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccountSubscription", reflect.TypeOf((*MockAccountSvc)(nil).UpdateAccountSubscription), ctx, accountID, status, planCode, stripeSubID, periodEnd, stripeCustomerID)
}
