// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/augno/api/services/auth-service/internal/domain (interfaces: UserRepo)
//
// Generated by this command:
//
//	mockgen -destination /Users/dane/Code/augno/api/services/auth-service/internal/domain/mock/repository/user_repo_mock.go -package repositorymock github.com/augno/api/services/auth-service/internal/domain UserRepo
//

// Package repositorymock is a generated GoMock package.
package repositorymock

import (
	context "context"
	reflect "reflect"

	types "github.com/augno/api/services/auth-service/pkg/types"
	contracts "github.com/augno/api/shared/contracts"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
	isgomock struct{}
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepo) Create(ctx context.Context, userID, email, name, hashedPassword string) (*types.User, *contracts.APIError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, email, name, hashedPassword)
	ret0, _ := ret[0].(*types.User)
	ret1, _ := ret[1].(*contracts.APIError)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserRepoMockRecorder) Create(ctx, userID, email, name, hashedPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepo)(nil).Create), ctx, userID, email, name, hashedPassword)
}

// Find mocks base method.
func (m *MockUserRepo) Find(ctx context.Context, identifier string) (*types.User, *contracts.APIError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, identifier)
	ret0, _ := ret[0].(*types.User)
	ret1, _ := ret[1].(*contracts.APIError)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockUserRepoMockRecorder) Find(ctx, identifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockUserRepo)(nil).Find), ctx, identifier)
}

// UpdatePassword mocks base method.
func (m *MockUserRepo) UpdatePassword(ctx context.Context, userID, hashedPassword string) *contracts.APIError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, userID, hashedPassword)
	ret0, _ := ret[0].(*contracts.APIError)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockUserRepoMockRecorder) UpdatePassword(ctx, userID, hashedPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockUserRepo)(nil).UpdatePassword), ctx, userID, hashedPassword)
}
