package productionrunep

import (
	"context"
	"net/http"

	apiendpoint "github.com/augno/api/services/api-gateway/pkg/endpoint"
	apiexample "github.com/augno/api/services/api-gateway/pkg/example"
	apirequest "github.com/augno/api/services/api-gateway/pkg/request"
	apiresource "github.com/augno/api/services/api-gateway/pkg/resource"
	"github.com/augno/api/shared/constants"
	apierror "github.com/augno/api/shared/errors"
	"github.com/augno/api/shared/field"
)

// Batch in a bulk production run create.
type BulkCreateBatchInput struct {
	// Item the batch produces, referenced by `id` or `sku`.
	Item apirequest.ItemIdentifier `json:"item" validate:"required"` // no `max` here: length validators panic on struct fields, so the limits live on ItemIdentifier
	// Good quantity produced by the batch, as a decimal string.
	QuantityValue string `json:"quantity_value" validate:"required" format:"decimal"`
	// Unit for `quantity_value`, referenced by `id`, `name`, or `abbreviation`.
	QuantityUnit apirequest.UnitIdentifier `json:"quantity_unit" validate:"required"`

	// Run time spent on the batch, as a decimal string. Ignored unless `seconds_unit` is
	// also provided.
	SecondsValue field.Optional[string] `json:"seconds_value,omitzero" format:"decimal"`
	// Unit for `seconds_value`, referenced by `id`, `name`, or `abbreviation`.
	SecondsUnit field.Optional[apirequest.UnitIdentifier] `json:"seconds_unit,omitzero"`
	// Scrap quantity generated by the batch, as a decimal string. Ignored unless
	// `waste_unit` is also provided.
	WasteValue field.Optional[string] `json:"waste_value,omitzero" format:"decimal"`
	// Unit for `waste_value`, referenced by `id`, `name`, or `abbreviation`.
	WasteUnit field.Optional[apirequest.UnitIdentifier] `json:"waste_unit,omitzero"`

	// ID of the production step the batch is recorded against.
	ProductionStepID field.Optional[string] `json:"production_step_id,omitzero"`
	// Scanning station where the batch will be scanned, referenced by `id` or `name`.
	ScanningStation field.Optional[apirequest.ObjectIdentifier] `json:"scanning_station,omitzero"`
}

// Production run to create, with its batches.
type BulkCreateProductionRunInput struct {
	// Account user accountable for executing the run. Accepts either an account user id or
	// a user id; it is resolved and stored as the account user.
	ResponsibleUserID string `json:"responsible_user_id" validate:"required"`
	// Batches created with the run. At least one is required.
	Batches []BulkCreateBatchInput `json:"batches" validate:"required,min=1,dive"`
}

// Request to bulk create production runs.
type BulkCreateProductionRunsRequest struct {
	// Production runs to create, each owning its batches. Run numbers are assigned
	// automatically as the next sequential numbers for the account.
	ProductionRuns []BulkCreateProductionRunInput `json:"production_runs" validate:"required,min=1,max=1000,dive"`
}

var sampleBulkCreateProductionRunsRequest = &BulkCreateProductionRunsRequest{
	ProductionRuns: []BulkCreateProductionRunInput{
		{
			ResponsibleUserID: apiresource.SampleUserID,
			Batches: []BulkCreateBatchInput{
				{
					Item: apirequest.ItemIdentifier{
						ID:  apiresource.SampleItemID,
						SKU: apiresource.SampleItemSKU,
					},
					QuantityValue: "100.0",
					QuantityUnit: apirequest.UnitIdentifier{
						ID:           apiresource.SampleUnitID,
						Name:         apiresource.SampleUnitName,
						Abbreviation: apiresource.SampleUnitAbbreviation,
					},
					ProductionStepID: field.Some(apiresource.SampleProductionStepID),
				},
			},
		},
	},
}

func (*BulkCreateProductionRunsRequest) SchemaExample() any {
	return apiexample.ValidateAndMarshalToMap(sampleBulkCreateProductionRunsRequest)
}

// Creates multiple production runs with their batches. Validates and resolves synchronously,
// then writes asynchronously — 202 with a job whose `results` already carry the new ids.
type BulkCreateProductionRunsEndpoint struct{}

func (e *BulkCreateProductionRunsEndpoint) Materialize() *apiendpoint.APIEndpoint[*BulkCreateProductionRunsRequest, *apiresource.Job] {
	return (&apiendpoint.APIEndpoint[*BulkCreateProductionRunsRequest, *apiresource.Job]{
		Title:             "Bulk Create Production Runs",
		Method:            http.MethodPost,
		ContentType:       "application/json",
		Route:             "/v1/operations/production-runs/actions/bulk-create",
		SuccessStatusCode: http.StatusAccepted,
		Public:            false,
		Preview:           true,
		ObjectType:        constants.ObjectTypeJob,
		ServiceHandler: func(svc any) func(ctx context.Context, req *BulkCreateProductionRunsRequest) (*apiresource.Job, *apierror.APIError) {
			return svc.(ProductionRunSvc).BulkCreateProductionRuns
		},
		// The work is accepted, not done, so point at the job rather than at any run.
		LocationFunc: func(resp *apiresource.Job) string {
			return "/v1/core/jobs/" + resp.ID
		},
	})
}
