// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.acquireOutboxMessagesStmt, err = db.PrepareContext(ctx, acquireOutboxMessages); err != nil {
		return nil, fmt.Errorf("error preparing query AcquireOutboxMessages: %w", err)
	}
	if q.advanceIdempotencyRecoveryPointStmt, err = db.PrepareContext(ctx, advanceIdempotencyRecoveryPoint); err != nil {
		return nil, fmt.Errorf("error preparing query AdvanceIdempotencyRecoveryPoint: %w", err)
	}
	if q.cleanupExpiredOutboxLocksStmt, err = db.PrepareContext(ctx, cleanupExpiredOutboxLocks); err != nil {
		return nil, fmt.Errorf("error preparing query CleanupExpiredOutboxLocks: %w", err)
	}
	if q.clearAccountStripeCustomerStmt, err = db.PrepareContext(ctx, clearAccountStripeCustomer); err != nil {
		return nil, fmt.Errorf("error preparing query ClearAccountStripeCustomer: %w", err)
	}
	if q.countActiveAccountUsersStmt, err = db.PrepareContext(ctx, countActiveAccountUsers); err != nil {
		return nil, fmt.Errorf("error preparing query CountActiveAccountUsers: %w", err)
	}
	if q.countNonSandboxAccountsByPlanCodeStmt, err = db.PrepareContext(ctx, countNonSandboxAccountsByPlanCode); err != nil {
		return nil, fmt.Errorf("error preparing query CountNonSandboxAccountsByPlanCode: %w", err)
	}
	if q.countSandboxAccountsStmt, err = db.PrepareContext(ctx, countSandboxAccounts); err != nil {
		return nil, fmt.Errorf("error preparing query CountSandboxAccounts: %w", err)
	}
	if q.createAccountStmt, err = db.PrepareContext(ctx, createAccount); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAccount: %w", err)
	}
	if q.createAccountAddressStmt, err = db.PrepareContext(ctx, createAccountAddress); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAccountAddress: %w", err)
	}
	if q.createAccountForRegistrationStmt, err = db.PrepareContext(ctx, createAccountForRegistration); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAccountForRegistration: %w", err)
	}
	if q.createAccountPortalStmt, err = db.PrepareContext(ctx, createAccountPortal); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAccountPortal: %w", err)
	}
	if q.createAccountUserForRegistrationStmt, err = db.PrepareContext(ctx, createAccountUserForRegistration); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAccountUserForRegistration: %w", err)
	}
	if q.createAddressStmt, err = db.PrepareContext(ctx, createAddress); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAddress: %w", err)
	}
	if q.createGeolocationStmt, err = db.PrepareContext(ctx, createGeolocation); err != nil {
		return nil, fmt.Errorf("error preparing query CreateGeolocation: %w", err)
	}
	if q.createIdempotencyKeyStmt, err = db.PrepareContext(ctx, createIdempotencyKey); err != nil {
		return nil, fmt.Errorf("error preparing query CreateIdempotencyKey: %w", err)
	}
	if q.createOutboxMessageStmt, err = db.PrepareContext(ctx, createOutboxMessage); err != nil {
		return nil, fmt.Errorf("error preparing query CreateOutboxMessage: %w", err)
	}
	if q.createRoleStmt, err = db.PrepareContext(ctx, createRole); err != nil {
		return nil, fmt.Errorf("error preparing query CreateRole: %w", err)
	}
	if q.createRolePermissionStmt, err = db.PrepareContext(ctx, createRolePermission); err != nil {
		return nil, fmt.Errorf("error preparing query CreateRolePermission: %w", err)
	}
	if q.createSandboxAccountStmt, err = db.PrepareContext(ctx, createSandboxAccount); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSandboxAccount: %w", err)
	}
	if q.deactivateAccountUsersExceptStmt, err = db.PrepareContext(ctx, deactivateAccountUsersExcept); err != nil {
		return nil, fmt.Errorf("error preparing query DeactivateAccountUsersExcept: %w", err)
	}
	if q.deleteAccountByIDStmt, err = db.PrepareContext(ctx, deleteAccountByID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAccountByID: %w", err)
	}
	if q.deleteAccountByIDIfSandboxStmt, err = db.PrepareContext(ctx, deleteAccountByIDIfSandbox); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAccountByIDIfSandbox: %w", err)
	}
	if q.deleteExpiredIdempotencyKeysStmt, err = db.PrepareContext(ctx, deleteExpiredIdempotencyKeys); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteExpiredIdempotencyKeys: %w", err)
	}
	if q.deleteSandboxAccountByIDStmt, err = db.PrepareContext(ctx, deleteSandboxAccountByID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSandboxAccountByID: %w", err)
	}
	if q.deleteSandboxAccountByTypeIDStmt, err = db.PrepareContext(ctx, deleteSandboxAccountByTypeID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSandboxAccountByTypeID: %w", err)
	}
	if q.ensureAccountUserActiveStmt, err = db.PrepareContext(ctx, ensureAccountUserActive); err != nil {
		return nil, fmt.Errorf("error preparing query EnsureAccountUserActive: %w", err)
	}
	if q.findAccountAffiliationsByUserIDStmt, err = db.PrepareContext(ctx, findAccountAffiliationsByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query FindAccountAffiliationsByUserID: %w", err)
	}
	if q.findAccountRelationByOwnerAccountIDAndAPIKeyIDStmt, err = db.PrepareContext(ctx, findAccountRelationByOwnerAccountIDAndAPIKeyID); err != nil {
		return nil, fmt.Errorf("error preparing query FindAccountRelationByOwnerAccountIDAndAPIKeyID: %w", err)
	}
	if q.findAccountRelationByOwnerAccountIDAndUserIDStmt, err = db.PrepareContext(ctx, findAccountRelationByOwnerAccountIDAndUserID); err != nil {
		return nil, fmt.Errorf("error preparing query FindAccountRelationByOwnerAccountIDAndUserID: %w", err)
	}
	if q.findAccountUserWithRoleByAccountIDAndUserIDStmt, err = db.PrepareContext(ctx, findAccountUserWithRoleByAccountIDAndUserID); err != nil {
		return nil, fmt.Errorf("error preparing query FindAccountUserWithRoleByAccountIDAndUserID: %w", err)
	}
	if q.findAdminUserIDByAccountIDStmt, err = db.PrepareContext(ctx, findAdminUserIDByAccountID); err != nil {
		return nil, fmt.Errorf("error preparing query FindAdminUserIDByAccountID: %w", err)
	}
	if q.findFirstSandboxAccountByOwnerAccountIDStmt, err = db.PrepareContext(ctx, findFirstSandboxAccountByOwnerAccountID); err != nil {
		return nil, fmt.Errorf("error preparing query FindFirstSandboxAccountByOwnerAccountID: %w", err)
	}
	if q.findLastUsedAccountIDStmt, err = db.PrepareContext(ctx, findLastUsedAccountID); err != nil {
		return nil, fmt.Errorf("error preparing query FindLastUsedAccountID: %w", err)
	}
	if q.findRolePermissionStringsStmt, err = db.PrepareContext(ctx, findRolePermissionStrings); err != nil {
		return nil, fmt.Errorf("error preparing query FindRolePermissionStrings: %w", err)
	}
	if q.findSandboxAccountByAccountIDStmt, err = db.PrepareContext(ctx, findSandboxAccountByAccountID); err != nil {
		return nil, fmt.Errorf("error preparing query FindSandboxAccountByAccountID: %w", err)
	}
	if q.findSandboxAccountByTypeIDStmt, err = db.PrepareContext(ctx, findSandboxAccountByTypeID); err != nil {
		return nil, fmt.Errorf("error preparing query FindSandboxAccountByTypeID: %w", err)
	}
	if q.getAccountByStripeCustomerIDStmt, err = db.PrepareContext(ctx, getAccountByStripeCustomerID); err != nil {
		return nil, fmt.Errorf("error preparing query GetAccountByStripeCustomerID: %w", err)
	}
	if q.getAccountContextStmt, err = db.PrepareContext(ctx, getAccountContext); err != nil {
		return nil, fmt.Errorf("error preparing query GetAccountContext: %w", err)
	}
	if q.getAccountPlanCodeStmt, err = db.PrepareContext(ctx, getAccountPlanCode); err != nil {
		return nil, fmt.Errorf("error preparing query GetAccountPlanCode: %w", err)
	}
	if q.getAccountPlanTypeIDByCodeStmt, err = db.PrepareContext(ctx, getAccountPlanTypeIDByCode); err != nil {
		return nil, fmt.Errorf("error preparing query GetAccountPlanTypeIDByCode: %w", err)
	}
	if q.getAdminRoleIDStmt, err = db.PrepareContext(ctx, getAdminRoleID); err != nil {
		return nil, fmt.Errorf("error preparing query GetAdminRoleID: %w", err)
	}
	if q.getAllPermissionsStmt, err = db.PrepareContext(ctx, getAllPermissions); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllPermissions: %w", err)
	}
	if q.getIdempotencyKeyByScopeHashStmt, err = db.PrepareContext(ctx, getIdempotencyKeyByScopeHash); err != nil {
		return nil, fmt.Errorf("error preparing query GetIdempotencyKeyByScopeHash: %w", err)
	}
	if q.getIdempotencyKeyByTypeIDStmt, err = db.PrepareContext(ctx, getIdempotencyKeyByTypeID); err != nil {
		return nil, fmt.Errorf("error preparing query GetIdempotencyKeyByTypeID: %w", err)
	}
	if q.getIdempotencyRecoveryPointStmt, err = db.PrepareContext(ctx, getIdempotencyRecoveryPoint); err != nil {
		return nil, fmt.Errorf("error preparing query GetIdempotencyRecoveryPoint: %w", err)
	}
	if q.getInboxRecordByMessageAndHandlerStmt, err = db.PrepareContext(ctx, getInboxRecordByMessageAndHandler); err != nil {
		return nil, fmt.Errorf("error preparing query GetInboxRecordByMessageAndHandler: %w", err)
	}
	if q.getLockedOutboxMessagesStmt, err = db.PrepareContext(ctx, getLockedOutboxMessages); err != nil {
		return nil, fmt.Errorf("error preparing query GetLockedOutboxMessages: %w", err)
	}
	if q.getSandboxLimitByAccountIDStmt, err = db.PrepareContext(ctx, getSandboxLimitByAccountID); err != nil {
		return nil, fmt.Errorf("error preparing query GetSandboxLimitByAccountID: %w", err)
	}
	if q.getSeatLimitByPlanCodeStmt, err = db.PrepareContext(ctx, getSeatLimitByPlanCode); err != nil {
		return nil, fmt.Errorf("error preparing query GetSeatLimitByPlanCode: %w", err)
	}
	if q.listSandboxAccountsBackwardStmt, err = db.PrepareContext(ctx, listSandboxAccountsBackward); err != nil {
		return nil, fmt.Errorf("error preparing query ListSandboxAccountsBackward: %w", err)
	}
	if q.listSandboxAccountsForwardStmt, err = db.PrepareContext(ctx, listSandboxAccountsForward); err != nil {
		return nil, fmt.Errorf("error preparing query ListSandboxAccountsForward: %w", err)
	}
	if q.listUnitsBackwardStmt, err = db.PrepareContext(ctx, listUnitsBackward); err != nil {
		return nil, fmt.Errorf("error preparing query ListUnitsBackward: %w", err)
	}
	if q.listUnitsForwardStmt, err = db.PrepareContext(ctx, listUnitsForward); err != nil {
		return nil, fmt.Errorf("error preparing query ListUnitsForward: %w", err)
	}
	if q.markInboxRecordFailedStmt, err = db.PrepareContext(ctx, markInboxRecordFailed); err != nil {
		return nil, fmt.Errorf("error preparing query MarkInboxRecordFailed: %w", err)
	}
	if q.markInboxRecordProcessedStmt, err = db.PrepareContext(ctx, markInboxRecordProcessed); err != nil {
		return nil, fmt.Errorf("error preparing query MarkInboxRecordProcessed: %w", err)
	}
	if q.markOutboxMessageFailedStmt, err = db.PrepareContext(ctx, markOutboxMessageFailed); err != nil {
		return nil, fmt.Errorf("error preparing query MarkOutboxMessageFailed: %w", err)
	}
	if q.markOutboxMessagePublishedStmt, err = db.PrepareContext(ctx, markOutboxMessagePublished); err != nil {
		return nil, fmt.Errorf("error preparing query MarkOutboxMessagePublished: %w", err)
	}
	if q.purgeProcessedInboxMessagesStmt, err = db.PrepareContext(ctx, purgeProcessedInboxMessages); err != nil {
		return nil, fmt.Errorf("error preparing query PurgeProcessedInboxMessages: %w", err)
	}
	if q.purgePublishedOutboxMessagesStmt, err = db.PrepareContext(ctx, purgePublishedOutboxMessages); err != nil {
		return nil, fmt.Errorf("error preparing query PurgePublishedOutboxMessages: %w", err)
	}
	if q.reactivateAccountUsersStmt, err = db.PrepareContext(ctx, reactivateAccountUsers); err != nil {
		return nil, fmt.Errorf("error preparing query ReactivateAccountUsers: %w", err)
	}
	if q.setAccountDefaultBillingAddressStmt, err = db.PrepareContext(ctx, setAccountDefaultBillingAddress); err != nil {
		return nil, fmt.Errorf("error preparing query SetAccountDefaultBillingAddress: %w", err)
	}
	if q.setAccountDefaultShippingAddressStmt, err = db.PrepareContext(ctx, setAccountDefaultShippingAddress); err != nil {
		return nil, fmt.Errorf("error preparing query SetAccountDefaultShippingAddress: %w", err)
	}
	if q.setIdempotencyResponseStmt, err = db.PrepareContext(ctx, setIdempotencyResponse); err != nil {
		return nil, fmt.Errorf("error preparing query SetIdempotencyResponse: %w", err)
	}
	if q.tryInsertInboxRecordStmt, err = db.PrepareContext(ctx, tryInsertInboxRecord); err != nil {
		return nil, fmt.Errorf("error preparing query TryInsertInboxRecord: %w", err)
	}
	if q.updateAccountSubscriptionStmt, err = db.PrepareContext(ctx, updateAccountSubscription); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAccountSubscription: %w", err)
	}
	if q.updateAccountUserLastUsedAtStmt, err = db.PrepareContext(ctx, updateAccountUserLastUsedAt); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAccountUserLastUsedAt: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.acquireOutboxMessagesStmt != nil {
		if cerr := q.acquireOutboxMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing acquireOutboxMessagesStmt: %w", cerr)
		}
	}
	if q.advanceIdempotencyRecoveryPointStmt != nil {
		if cerr := q.advanceIdempotencyRecoveryPointStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing advanceIdempotencyRecoveryPointStmt: %w", cerr)
		}
	}
	if q.cleanupExpiredOutboxLocksStmt != nil {
		if cerr := q.cleanupExpiredOutboxLocksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing cleanupExpiredOutboxLocksStmt: %w", cerr)
		}
	}
	if q.clearAccountStripeCustomerStmt != nil {
		if cerr := q.clearAccountStripeCustomerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearAccountStripeCustomerStmt: %w", cerr)
		}
	}
	if q.countActiveAccountUsersStmt != nil {
		if cerr := q.countActiveAccountUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countActiveAccountUsersStmt: %w", cerr)
		}
	}
	if q.countNonSandboxAccountsByPlanCodeStmt != nil {
		if cerr := q.countNonSandboxAccountsByPlanCodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countNonSandboxAccountsByPlanCodeStmt: %w", cerr)
		}
	}
	if q.countSandboxAccountsStmt != nil {
		if cerr := q.countSandboxAccountsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countSandboxAccountsStmt: %w", cerr)
		}
	}
	if q.createAccountStmt != nil {
		if cerr := q.createAccountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAccountStmt: %w", cerr)
		}
	}
	if q.createAccountAddressStmt != nil {
		if cerr := q.createAccountAddressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAccountAddressStmt: %w", cerr)
		}
	}
	if q.createAccountForRegistrationStmt != nil {
		if cerr := q.createAccountForRegistrationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAccountForRegistrationStmt: %w", cerr)
		}
	}
	if q.createAccountPortalStmt != nil {
		if cerr := q.createAccountPortalStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAccountPortalStmt: %w", cerr)
		}
	}
	if q.createAccountUserForRegistrationStmt != nil {
		if cerr := q.createAccountUserForRegistrationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAccountUserForRegistrationStmt: %w", cerr)
		}
	}
	if q.createAddressStmt != nil {
		if cerr := q.createAddressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAddressStmt: %w", cerr)
		}
	}
	if q.createGeolocationStmt != nil {
		if cerr := q.createGeolocationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createGeolocationStmt: %w", cerr)
		}
	}
	if q.createIdempotencyKeyStmt != nil {
		if cerr := q.createIdempotencyKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createIdempotencyKeyStmt: %w", cerr)
		}
	}
	if q.createOutboxMessageStmt != nil {
		if cerr := q.createOutboxMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createOutboxMessageStmt: %w", cerr)
		}
	}
	if q.createRoleStmt != nil {
		if cerr := q.createRoleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createRoleStmt: %w", cerr)
		}
	}
	if q.createRolePermissionStmt != nil {
		if cerr := q.createRolePermissionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createRolePermissionStmt: %w", cerr)
		}
	}
	if q.createSandboxAccountStmt != nil {
		if cerr := q.createSandboxAccountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSandboxAccountStmt: %w", cerr)
		}
	}
	if q.deactivateAccountUsersExceptStmt != nil {
		if cerr := q.deactivateAccountUsersExceptStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deactivateAccountUsersExceptStmt: %w", cerr)
		}
	}
	if q.deleteAccountByIDStmt != nil {
		if cerr := q.deleteAccountByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAccountByIDStmt: %w", cerr)
		}
	}
	if q.deleteAccountByIDIfSandboxStmt != nil {
		if cerr := q.deleteAccountByIDIfSandboxStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAccountByIDIfSandboxStmt: %w", cerr)
		}
	}
	if q.deleteExpiredIdempotencyKeysStmt != nil {
		if cerr := q.deleteExpiredIdempotencyKeysStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteExpiredIdempotencyKeysStmt: %w", cerr)
		}
	}
	if q.deleteSandboxAccountByIDStmt != nil {
		if cerr := q.deleteSandboxAccountByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSandboxAccountByIDStmt: %w", cerr)
		}
	}
	if q.deleteSandboxAccountByTypeIDStmt != nil {
		if cerr := q.deleteSandboxAccountByTypeIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSandboxAccountByTypeIDStmt: %w", cerr)
		}
	}
	if q.ensureAccountUserActiveStmt != nil {
		if cerr := q.ensureAccountUserActiveStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing ensureAccountUserActiveStmt: %w", cerr)
		}
	}
	if q.findAccountAffiliationsByUserIDStmt != nil {
		if cerr := q.findAccountAffiliationsByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findAccountAffiliationsByUserIDStmt: %w", cerr)
		}
	}
	if q.findAccountRelationByOwnerAccountIDAndAPIKeyIDStmt != nil {
		if cerr := q.findAccountRelationByOwnerAccountIDAndAPIKeyIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findAccountRelationByOwnerAccountIDAndAPIKeyIDStmt: %w", cerr)
		}
	}
	if q.findAccountRelationByOwnerAccountIDAndUserIDStmt != nil {
		if cerr := q.findAccountRelationByOwnerAccountIDAndUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findAccountRelationByOwnerAccountIDAndUserIDStmt: %w", cerr)
		}
	}
	if q.findAccountUserWithRoleByAccountIDAndUserIDStmt != nil {
		if cerr := q.findAccountUserWithRoleByAccountIDAndUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findAccountUserWithRoleByAccountIDAndUserIDStmt: %w", cerr)
		}
	}
	if q.findAdminUserIDByAccountIDStmt != nil {
		if cerr := q.findAdminUserIDByAccountIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findAdminUserIDByAccountIDStmt: %w", cerr)
		}
	}
	if q.findFirstSandboxAccountByOwnerAccountIDStmt != nil {
		if cerr := q.findFirstSandboxAccountByOwnerAccountIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findFirstSandboxAccountByOwnerAccountIDStmt: %w", cerr)
		}
	}
	if q.findLastUsedAccountIDStmt != nil {
		if cerr := q.findLastUsedAccountIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findLastUsedAccountIDStmt: %w", cerr)
		}
	}
	if q.findRolePermissionStringsStmt != nil {
		if cerr := q.findRolePermissionStringsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findRolePermissionStringsStmt: %w", cerr)
		}
	}
	if q.findSandboxAccountByAccountIDStmt != nil {
		if cerr := q.findSandboxAccountByAccountIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findSandboxAccountByAccountIDStmt: %w", cerr)
		}
	}
	if q.findSandboxAccountByTypeIDStmt != nil {
		if cerr := q.findSandboxAccountByTypeIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findSandboxAccountByTypeIDStmt: %w", cerr)
		}
	}
	if q.getAccountByStripeCustomerIDStmt != nil {
		if cerr := q.getAccountByStripeCustomerIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAccountByStripeCustomerIDStmt: %w", cerr)
		}
	}
	if q.getAccountContextStmt != nil {
		if cerr := q.getAccountContextStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAccountContextStmt: %w", cerr)
		}
	}
	if q.getAccountPlanCodeStmt != nil {
		if cerr := q.getAccountPlanCodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAccountPlanCodeStmt: %w", cerr)
		}
	}
	if q.getAccountPlanTypeIDByCodeStmt != nil {
		if cerr := q.getAccountPlanTypeIDByCodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAccountPlanTypeIDByCodeStmt: %w", cerr)
		}
	}
	if q.getAdminRoleIDStmt != nil {
		if cerr := q.getAdminRoleIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAdminRoleIDStmt: %w", cerr)
		}
	}
	if q.getAllPermissionsStmt != nil {
		if cerr := q.getAllPermissionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllPermissionsStmt: %w", cerr)
		}
	}
	if q.getIdempotencyKeyByScopeHashStmt != nil {
		if cerr := q.getIdempotencyKeyByScopeHashStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getIdempotencyKeyByScopeHashStmt: %w", cerr)
		}
	}
	if q.getIdempotencyKeyByTypeIDStmt != nil {
		if cerr := q.getIdempotencyKeyByTypeIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getIdempotencyKeyByTypeIDStmt: %w", cerr)
		}
	}
	if q.getIdempotencyRecoveryPointStmt != nil {
		if cerr := q.getIdempotencyRecoveryPointStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getIdempotencyRecoveryPointStmt: %w", cerr)
		}
	}
	if q.getInboxRecordByMessageAndHandlerStmt != nil {
		if cerr := q.getInboxRecordByMessageAndHandlerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getInboxRecordByMessageAndHandlerStmt: %w", cerr)
		}
	}
	if q.getLockedOutboxMessagesStmt != nil {
		if cerr := q.getLockedOutboxMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLockedOutboxMessagesStmt: %w", cerr)
		}
	}
	if q.getSandboxLimitByAccountIDStmt != nil {
		if cerr := q.getSandboxLimitByAccountIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSandboxLimitByAccountIDStmt: %w", cerr)
		}
	}
	if q.getSeatLimitByPlanCodeStmt != nil {
		if cerr := q.getSeatLimitByPlanCodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSeatLimitByPlanCodeStmt: %w", cerr)
		}
	}
	if q.listSandboxAccountsBackwardStmt != nil {
		if cerr := q.listSandboxAccountsBackwardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSandboxAccountsBackwardStmt: %w", cerr)
		}
	}
	if q.listSandboxAccountsForwardStmt != nil {
		if cerr := q.listSandboxAccountsForwardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSandboxAccountsForwardStmt: %w", cerr)
		}
	}
	if q.listUnitsBackwardStmt != nil {
		if cerr := q.listUnitsBackwardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUnitsBackwardStmt: %w", cerr)
		}
	}
	if q.listUnitsForwardStmt != nil {
		if cerr := q.listUnitsForwardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUnitsForwardStmt: %w", cerr)
		}
	}
	if q.markInboxRecordFailedStmt != nil {
		if cerr := q.markInboxRecordFailedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markInboxRecordFailedStmt: %w", cerr)
		}
	}
	if q.markInboxRecordProcessedStmt != nil {
		if cerr := q.markInboxRecordProcessedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markInboxRecordProcessedStmt: %w", cerr)
		}
	}
	if q.markOutboxMessageFailedStmt != nil {
		if cerr := q.markOutboxMessageFailedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markOutboxMessageFailedStmt: %w", cerr)
		}
	}
	if q.markOutboxMessagePublishedStmt != nil {
		if cerr := q.markOutboxMessagePublishedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markOutboxMessagePublishedStmt: %w", cerr)
		}
	}
	if q.purgeProcessedInboxMessagesStmt != nil {
		if cerr := q.purgeProcessedInboxMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing purgeProcessedInboxMessagesStmt: %w", cerr)
		}
	}
	if q.purgePublishedOutboxMessagesStmt != nil {
		if cerr := q.purgePublishedOutboxMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing purgePublishedOutboxMessagesStmt: %w", cerr)
		}
	}
	if q.reactivateAccountUsersStmt != nil {
		if cerr := q.reactivateAccountUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing reactivateAccountUsersStmt: %w", cerr)
		}
	}
	if q.setAccountDefaultBillingAddressStmt != nil {
		if cerr := q.setAccountDefaultBillingAddressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setAccountDefaultBillingAddressStmt: %w", cerr)
		}
	}
	if q.setAccountDefaultShippingAddressStmt != nil {
		if cerr := q.setAccountDefaultShippingAddressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setAccountDefaultShippingAddressStmt: %w", cerr)
		}
	}
	if q.setIdempotencyResponseStmt != nil {
		if cerr := q.setIdempotencyResponseStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setIdempotencyResponseStmt: %w", cerr)
		}
	}
	if q.tryInsertInboxRecordStmt != nil {
		if cerr := q.tryInsertInboxRecordStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing tryInsertInboxRecordStmt: %w", cerr)
		}
	}
	if q.updateAccountSubscriptionStmt != nil {
		if cerr := q.updateAccountSubscriptionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAccountSubscriptionStmt: %w", cerr)
		}
	}
	if q.updateAccountUserLastUsedAtStmt != nil {
		if cerr := q.updateAccountUserLastUsedAtStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAccountUserLastUsedAtStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                                 DBTX
	tx                                                 *sql.Tx
	acquireOutboxMessagesStmt                          *sql.Stmt
	advanceIdempotencyRecoveryPointStmt                *sql.Stmt
	cleanupExpiredOutboxLocksStmt                      *sql.Stmt
	clearAccountStripeCustomerStmt                     *sql.Stmt
	countActiveAccountUsersStmt                        *sql.Stmt
	countNonSandboxAccountsByPlanCodeStmt              *sql.Stmt
	countSandboxAccountsStmt                           *sql.Stmt
	createAccountStmt                                  *sql.Stmt
	createAccountAddressStmt                           *sql.Stmt
	createAccountForRegistrationStmt                   *sql.Stmt
	createAccountPortalStmt                            *sql.Stmt
	createAccountUserForRegistrationStmt               *sql.Stmt
	createAddressStmt                                  *sql.Stmt
	createGeolocationStmt                              *sql.Stmt
	createIdempotencyKeyStmt                           *sql.Stmt
	createOutboxMessageStmt                            *sql.Stmt
	createRoleStmt                                     *sql.Stmt
	createRolePermissionStmt                           *sql.Stmt
	createSandboxAccountStmt                           *sql.Stmt
	deactivateAccountUsersExceptStmt                   *sql.Stmt
	deleteAccountByIDStmt                              *sql.Stmt
	deleteAccountByIDIfSandboxStmt                     *sql.Stmt
	deleteExpiredIdempotencyKeysStmt                   *sql.Stmt
	deleteSandboxAccountByIDStmt                       *sql.Stmt
	deleteSandboxAccountByTypeIDStmt                   *sql.Stmt
	ensureAccountUserActiveStmt                        *sql.Stmt
	findAccountAffiliationsByUserIDStmt                *sql.Stmt
	findAccountRelationByOwnerAccountIDAndAPIKeyIDStmt *sql.Stmt
	findAccountRelationByOwnerAccountIDAndUserIDStmt   *sql.Stmt
	findAccountUserWithRoleByAccountIDAndUserIDStmt    *sql.Stmt
	findAdminUserIDByAccountIDStmt                     *sql.Stmt
	findFirstSandboxAccountByOwnerAccountIDStmt        *sql.Stmt
	findLastUsedAccountIDStmt                          *sql.Stmt
	findRolePermissionStringsStmt                      *sql.Stmt
	findSandboxAccountByAccountIDStmt                  *sql.Stmt
	findSandboxAccountByTypeIDStmt                     *sql.Stmt
	getAccountByStripeCustomerIDStmt                   *sql.Stmt
	getAccountContextStmt                              *sql.Stmt
	getAccountPlanCodeStmt                             *sql.Stmt
	getAccountPlanTypeIDByCodeStmt                     *sql.Stmt
	getAdminRoleIDStmt                                 *sql.Stmt
	getAllPermissionsStmt                              *sql.Stmt
	getIdempotencyKeyByScopeHashStmt                   *sql.Stmt
	getIdempotencyKeyByTypeIDStmt                      *sql.Stmt
	getIdempotencyRecoveryPointStmt                    *sql.Stmt
	getInboxRecordByMessageAndHandlerStmt              *sql.Stmt
	getLockedOutboxMessagesStmt                        *sql.Stmt
	getSandboxLimitByAccountIDStmt                     *sql.Stmt
	getSeatLimitByPlanCodeStmt                         *sql.Stmt
	listSandboxAccountsBackwardStmt                    *sql.Stmt
	listSandboxAccountsForwardStmt                     *sql.Stmt
	listUnitsBackwardStmt                              *sql.Stmt
	listUnitsForwardStmt                               *sql.Stmt
	markInboxRecordFailedStmt                          *sql.Stmt
	markInboxRecordProcessedStmt                       *sql.Stmt
	markOutboxMessageFailedStmt                        *sql.Stmt
	markOutboxMessagePublishedStmt                     *sql.Stmt
	purgeProcessedInboxMessagesStmt                    *sql.Stmt
	purgePublishedOutboxMessagesStmt                   *sql.Stmt
	reactivateAccountUsersStmt                         *sql.Stmt
	setAccountDefaultBillingAddressStmt                *sql.Stmt
	setAccountDefaultShippingAddressStmt               *sql.Stmt
	setIdempotencyResponseStmt                         *sql.Stmt
	tryInsertInboxRecordStmt                           *sql.Stmt
	updateAccountSubscriptionStmt                      *sql.Stmt
	updateAccountUserLastUsedAtStmt                    *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                                 tx,
		tx:                                                 tx,
		acquireOutboxMessagesStmt:                          q.acquireOutboxMessagesStmt,
		advanceIdempotencyRecoveryPointStmt:                q.advanceIdempotencyRecoveryPointStmt,
		cleanupExpiredOutboxLocksStmt:                      q.cleanupExpiredOutboxLocksStmt,
		clearAccountStripeCustomerStmt:                     q.clearAccountStripeCustomerStmt,
		countActiveAccountUsersStmt:                        q.countActiveAccountUsersStmt,
		countNonSandboxAccountsByPlanCodeStmt:              q.countNonSandboxAccountsByPlanCodeStmt,
		countSandboxAccountsStmt:                           q.countSandboxAccountsStmt,
		createAccountStmt:                                  q.createAccountStmt,
		createAccountAddressStmt:                           q.createAccountAddressStmt,
		createAccountForRegistrationStmt:                   q.createAccountForRegistrationStmt,
		createAccountPortalStmt:                            q.createAccountPortalStmt,
		createAccountUserForRegistrationStmt:               q.createAccountUserForRegistrationStmt,
		createAddressStmt:                                  q.createAddressStmt,
		createGeolocationStmt:                              q.createGeolocationStmt,
		createIdempotencyKeyStmt:                           q.createIdempotencyKeyStmt,
		createOutboxMessageStmt:                            q.createOutboxMessageStmt,
		createRoleStmt:                                     q.createRoleStmt,
		createRolePermissionStmt:                           q.createRolePermissionStmt,
		createSandboxAccountStmt:                           q.createSandboxAccountStmt,
		deactivateAccountUsersExceptStmt:                   q.deactivateAccountUsersExceptStmt,
		deleteAccountByIDStmt:                              q.deleteAccountByIDStmt,
		deleteAccountByIDIfSandboxStmt:                     q.deleteAccountByIDIfSandboxStmt,
		deleteExpiredIdempotencyKeysStmt:                   q.deleteExpiredIdempotencyKeysStmt,
		deleteSandboxAccountByIDStmt:                       q.deleteSandboxAccountByIDStmt,
		deleteSandboxAccountByTypeIDStmt:                   q.deleteSandboxAccountByTypeIDStmt,
		ensureAccountUserActiveStmt:                        q.ensureAccountUserActiveStmt,
		findAccountAffiliationsByUserIDStmt:                q.findAccountAffiliationsByUserIDStmt,
		findAccountRelationByOwnerAccountIDAndAPIKeyIDStmt: q.findAccountRelationByOwnerAccountIDAndAPIKeyIDStmt,
		findAccountRelationByOwnerAccountIDAndUserIDStmt:   q.findAccountRelationByOwnerAccountIDAndUserIDStmt,
		findAccountUserWithRoleByAccountIDAndUserIDStmt:    q.findAccountUserWithRoleByAccountIDAndUserIDStmt,
		findAdminUserIDByAccountIDStmt:                     q.findAdminUserIDByAccountIDStmt,
		findFirstSandboxAccountByOwnerAccountIDStmt:        q.findFirstSandboxAccountByOwnerAccountIDStmt,
		findLastUsedAccountIDStmt:                          q.findLastUsedAccountIDStmt,
		findRolePermissionStringsStmt:                      q.findRolePermissionStringsStmt,
		findSandboxAccountByAccountIDStmt:                  q.findSandboxAccountByAccountIDStmt,
		findSandboxAccountByTypeIDStmt:                     q.findSandboxAccountByTypeIDStmt,
		getAccountByStripeCustomerIDStmt:                   q.getAccountByStripeCustomerIDStmt,
		getAccountContextStmt:                              q.getAccountContextStmt,
		getAccountPlanCodeStmt:                             q.getAccountPlanCodeStmt,
		getAccountPlanTypeIDByCodeStmt:                     q.getAccountPlanTypeIDByCodeStmt,
		getAdminRoleIDStmt:                                 q.getAdminRoleIDStmt,
		getAllPermissionsStmt:                              q.getAllPermissionsStmt,
		getIdempotencyKeyByScopeHashStmt:                   q.getIdempotencyKeyByScopeHashStmt,
		getIdempotencyKeyByTypeIDStmt:                      q.getIdempotencyKeyByTypeIDStmt,
		getIdempotencyRecoveryPointStmt:                    q.getIdempotencyRecoveryPointStmt,
		getInboxRecordByMessageAndHandlerStmt:              q.getInboxRecordByMessageAndHandlerStmt,
		getLockedOutboxMessagesStmt:                        q.getLockedOutboxMessagesStmt,
		getSandboxLimitByAccountIDStmt:                     q.getSandboxLimitByAccountIDStmt,
		getSeatLimitByPlanCodeStmt:                         q.getSeatLimitByPlanCodeStmt,
		listSandboxAccountsBackwardStmt:                    q.listSandboxAccountsBackwardStmt,
		listSandboxAccountsForwardStmt:                     q.listSandboxAccountsForwardStmt,
		listUnitsBackwardStmt:                              q.listUnitsBackwardStmt,
		listUnitsForwardStmt:                               q.listUnitsForwardStmt,
		markInboxRecordFailedStmt:                          q.markInboxRecordFailedStmt,
		markInboxRecordProcessedStmt:                       q.markInboxRecordProcessedStmt,
		markOutboxMessageFailedStmt:                        q.markOutboxMessageFailedStmt,
		markOutboxMessagePublishedStmt:                     q.markOutboxMessagePublishedStmt,
		purgeProcessedInboxMessagesStmt:                    q.purgeProcessedInboxMessagesStmt,
		purgePublishedOutboxMessagesStmt:                   q.purgePublishedOutboxMessagesStmt,
		reactivateAccountUsersStmt:                         q.reactivateAccountUsersStmt,
		setAccountDefaultBillingAddressStmt:                q.setAccountDefaultBillingAddressStmt,
		setAccountDefaultShippingAddressStmt:               q.setAccountDefaultShippingAddressStmt,
		setIdempotencyResponseStmt:                         q.setIdempotencyResponseStmt,
		tryInsertInboxRecordStmt:                           q.tryInsertInboxRecordStmt,
		updateAccountSubscriptionStmt:                      q.updateAccountSubscriptionStmt,
		updateAccountUserLastUsedAtStmt:                    q.updateAccountUserLastUsedAtStmt,
	}
}
