// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: item_category.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const countItemCategoryInAccount = `-- name: CountItemCategoryInAccount :one
SELECT COUNT(*) FROM item_category
WHERE id = ?
AND (account_id = ? OR account_id IS NULL)
`

type CountItemCategoryInAccountParams struct {
	ID        string
	AccountID sql.NullString
}

func (q *Queries) CountItemCategoryInAccount(ctx context.Context, arg CountItemCategoryInAccountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countItemCategoryInAccount, arg.ID, arg.AccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPropertiesInCategoryByName = `-- name: CountPropertiesInCategoryByName :one
SELECT COUNT(*) FROM property p
INNER JOIN _item_categories_properties icp ON icp.B = p.id
WHERE icp.A = ?
AND p.name = ?
AND p.account_id = ?
AND (? IS NULL OR p.id != ?)
`

type CountPropertiesInCategoryByNameParams struct {
	ItemCategoryID    string
	Name              string
	AccountID         string
	ExcludePropertyID sql.NullString
}

func (q *Queries) CountPropertiesInCategoryByName(ctx context.Context, arg CountPropertiesInCategoryByNameParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPropertiesInCategoryByName,
		arg.ItemCategoryID,
		arg.Name,
		arg.AccountID,
		arg.ExcludePropertyID,
		arg.ExcludePropertyID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPropertyInAccount = `-- name: CountPropertyInAccount :one
SELECT COUNT(*) FROM property
WHERE id = ?
AND account_id = ?
`

type CountPropertyInAccountParams struct {
	ID        string
	AccountID string
}

func (q *Queries) CountPropertyInAccount(ctx context.Context, arg CountPropertyInAccountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPropertyInAccount, arg.ID, arg.AccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnitGroupVisibleToAccount = `-- name: CountUnitGroupVisibleToAccount :one
SELECT COUNT(*) FROM unit_group
WHERE id = ?
AND (account_id = ? OR account_id IS NULL)
`

type CountUnitGroupVisibleToAccountParams struct {
	ID        string
	AccountID sql.NullString
}

func (q *Queries) CountUnitGroupVisibleToAccount(ctx context.Context, arg CountUnitGroupVisibleToAccountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnitGroupVisibleToAccount, arg.ID, arg.AccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteItemCategory = `-- name: DeleteItemCategory :execresult
DELETE FROM item_category
WHERE id = ?
AND account_id = ?
`

type DeleteItemCategoryParams struct {
	ID        string
	AccountID sql.NullString
}

func (q *Queries) DeleteItemCategory(ctx context.Context, arg DeleteItemCategoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteItemCategory, arg.ID, arg.AccountID)
}

const deleteItemCategoryProperty = `-- name: DeleteItemCategoryProperty :exec
DELETE FROM _item_categories_properties
WHERE A = ? AND B = ?
`

type DeleteItemCategoryPropertyParams struct {
	ItemCategoryID string
	PropertyID     string
}

func (q *Queries) DeleteItemCategoryProperty(ctx context.Context, arg DeleteItemCategoryPropertyParams) error {
	_, err := q.db.ExecContext(ctx, deleteItemCategoryProperty, arg.ItemCategoryID, arg.PropertyID)
	return err
}

const getItemCategoriesByIDs = `-- name: GetItemCategoriesByIDs :many
SELECT
    ic.id,
    ic.name,
    ic.notes,
    ic.item_category_type_code,
    ic.unit_group_id,
    ic.account_id,
    ic.created_at,
    ic.updated_at
FROM item_category ic
WHERE ic.id IN (/*SLICE:ids*/?)
AND (ic.account_id = ? OR ic.account_id IS NULL)
`

type GetItemCategoriesByIDsParams struct {
	Ids       []string
	AccountID sql.NullString
}

type GetItemCategoriesByIDsRow struct {
	ID                   string
	Name                 string
	Notes                sql.NullString
	ItemCategoryTypeCode string
	UnitGroupID          string
	AccountID            sql.NullString
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

func (q *Queries) GetItemCategoriesByIDs(ctx context.Context, arg GetItemCategoriesByIDsParams) ([]GetItemCategoriesByIDsRow, error) {
	query := getItemCategoriesByIDs
	var queryParams []interface{}
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.AccountID)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetItemCategoriesByIDsRow
	for rows.Next() {
		var i GetItemCategoriesByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Notes,
			&i.ItemCategoryTypeCode,
			&i.UnitGroupID,
			&i.AccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemCategory = `-- name: GetItemCategory :one
SELECT
    ic.id,
    ic.name,
    ic.notes,
    ic.item_category_type_code,
    ic.unit_group_id,
    ic.account_id,
    ic.created_at,
    ic.updated_at
FROM item_category ic
WHERE ic.id = ?
AND (ic.account_id = ? OR ic.account_id IS NULL)
`

type GetItemCategoryParams struct {
	ID        string
	AccountID sql.NullString
}

type GetItemCategoryRow struct {
	ID                   string
	Name                 string
	Notes                sql.NullString
	ItemCategoryTypeCode string
	UnitGroupID          string
	AccountID            sql.NullString
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

func (q *Queries) GetItemCategory(ctx context.Context, arg GetItemCategoryParams) (GetItemCategoryRow, error) {
	row := q.db.QueryRowContext(ctx, getItemCategory, arg.ID, arg.AccountID)
	var i GetItemCategoryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Notes,
		&i.ItemCategoryTypeCode,
		&i.UnitGroupID,
		&i.AccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnitGroupForCategory = `-- name: GetUnitGroupForCategory :one
SELECT
    ug.id,
    ug.name,
    ug.base_unit_id,
    ug.unit_type_code,
    ug.created_at,
    ug.updated_at
FROM unit_group ug
WHERE ug.id = ?
`

type GetUnitGroupForCategoryRow struct {
	ID           string
	Name         string
	BaseUnitID   string
	UnitTypeCode string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) GetUnitGroupForCategory(ctx context.Context, id string) (GetUnitGroupForCategoryRow, error) {
	row := q.db.QueryRowContext(ctx, getUnitGroupForCategory, id)
	var i GetUnitGroupForCategoryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUnitID,
		&i.UnitTypeCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertItemCategory = `-- name: InsertItemCategory :exec
INSERT INTO item_category (
    id,
    name,
    item_category_type_code,
    unit_group_id,
    account_id,
    created_at,
    updated_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    NOW(3),
    NOW(3)
)
`

type InsertItemCategoryParams struct {
	ID                   string
	Name                 string
	ItemCategoryTypeCode string
	UnitGroupID          string
	AccountID            sql.NullString
}

func (q *Queries) InsertItemCategory(ctx context.Context, arg InsertItemCategoryParams) error {
	_, err := q.db.ExecContext(ctx, insertItemCategory,
		arg.ID,
		arg.Name,
		arg.ItemCategoryTypeCode,
		arg.UnitGroupID,
		arg.AccountID,
	)
	return err
}

const insertItemCategoryProperty = `-- name: InsertItemCategoryProperty :exec
INSERT INTO _item_categories_properties (A, B)
VALUES (?, ?)
`

type InsertItemCategoryPropertyParams struct {
	ItemCategoryID string
	PropertyID     string
}

func (q *Queries) InsertItemCategoryProperty(ctx context.Context, arg InsertItemCategoryPropertyParams) error {
	_, err := q.db.ExecContext(ctx, insertItemCategoryProperty, arg.ItemCategoryID, arg.PropertyID)
	return err
}

const listItemCategoriesBackward = `-- name: ListItemCategoriesBackward :many
SELECT
    ic.id,
    ic.name,
    ic.notes,
    ic.item_category_type_code,
    ic.unit_group_id,
    ic.account_id,
    ic.created_at,
    ic.updated_at
FROM item_category ic
WHERE (ic.account_id = ? OR ic.account_id IS NULL)
AND (? IS NULL OR ic.item_category_type_code = ?)
AND (
    ? IS NULL
    OR ic.name LIKE ?
)
AND (
    ic.created_at > ?
    OR (ic.created_at = ? AND ic.id > ?)
)
ORDER BY ic.created_at ASC, ic.id ASC
LIMIT ?
`

type ListItemCategoriesBackwardParams struct {
	AccountID            sql.NullString
	ItemCategoryTypeCode sql.NullString
	SearchQuery          sql.NullString
	CursorCreatedAt      time.Time
	CursorID             string
	Limit                int32
}

type ListItemCategoriesBackwardRow struct {
	ID                   string
	Name                 string
	Notes                sql.NullString
	ItemCategoryTypeCode string
	UnitGroupID          string
	AccountID            sql.NullString
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

func (q *Queries) ListItemCategoriesBackward(ctx context.Context, arg ListItemCategoriesBackwardParams) ([]ListItemCategoriesBackwardRow, error) {
	rows, err := q.db.QueryContext(ctx, listItemCategoriesBackward,
		arg.AccountID,
		arg.ItemCategoryTypeCode,
		arg.ItemCategoryTypeCode,
		arg.SearchQuery,
		arg.SearchQuery,
		arg.CursorCreatedAt,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemCategoriesBackwardRow
	for rows.Next() {
		var i ListItemCategoriesBackwardRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Notes,
			&i.ItemCategoryTypeCode,
			&i.UnitGroupID,
			&i.AccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemCategoriesForward = `-- name: ListItemCategoriesForward :many
SELECT
    ic.id,
    ic.name,
    ic.notes,
    ic.item_category_type_code,
    ic.unit_group_id,
    ic.account_id,
    ic.created_at,
    ic.updated_at
FROM item_category ic
WHERE (ic.account_id = ? OR ic.account_id IS NULL)
AND (? IS NULL OR ic.item_category_type_code = ?)
AND (
    ? IS NULL
    OR ic.name LIKE ?
)
AND (
    ? IS NULL
    OR ic.created_at < ?
    OR (ic.created_at = ? AND ic.id < ?)
)
ORDER BY ic.created_at DESC, ic.id DESC
LIMIT ?
`

type ListItemCategoriesForwardParams struct {
	AccountID            sql.NullString
	ItemCategoryTypeCode sql.NullString
	SearchQuery          sql.NullString
	CursorCreatedAt      sql.NullTime
	CursorID             sql.NullString
	Limit                int32
}

type ListItemCategoriesForwardRow struct {
	ID                   string
	Name                 string
	Notes                sql.NullString
	ItemCategoryTypeCode string
	UnitGroupID          string
	AccountID            sql.NullString
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

func (q *Queries) ListItemCategoriesForward(ctx context.Context, arg ListItemCategoriesForwardParams) ([]ListItemCategoriesForwardRow, error) {
	rows, err := q.db.QueryContext(ctx, listItemCategoriesForward,
		arg.AccountID,
		arg.ItemCategoryTypeCode,
		arg.ItemCategoryTypeCode,
		arg.SearchQuery,
		arg.SearchQuery,
		arg.CursorCreatedAt,
		arg.CursorCreatedAt,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemCategoriesForwardRow
	for rows.Next() {
		var i ListItemCategoriesForwardRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Notes,
			&i.ItemCategoryTypeCode,
			&i.UnitGroupID,
			&i.AccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemCategoryProperties = `-- name: ListItemCategoryProperties :many
SELECT
    p.id,
    p.name,
    p.created_at,
    p.updated_at
FROM property p
INNER JOIN _item_categories_properties icp ON icp.B = p.id
WHERE icp.A = ?
`

type ListItemCategoryPropertiesRow struct {
	ID        string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) ListItemCategoryProperties(ctx context.Context, itemCategoryID string) ([]ListItemCategoryPropertiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listItemCategoryProperties, itemCategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemCategoryPropertiesRow
	for rows.Next() {
		var i ListItemCategoryPropertiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemCategoryPropertiesForCategories = `-- name: ListItemCategoryPropertiesForCategories :many
SELECT
    icp.A AS item_category_id,
    p.id AS property_id,
    p.name AS property_name,
    p.created_at AS property_created_at,
    p.updated_at AS property_updated_at
FROM property p
INNER JOIN _item_categories_properties icp ON icp.B = p.id
WHERE icp.A IN (/*SLICE:item_category_ids*/?)
ORDER BY icp.A, p.name
`

type ListItemCategoryPropertiesForCategoriesRow struct {
	ItemCategoryID    string
	PropertyID        string
	PropertyName      string
	PropertyCreatedAt time.Time
	PropertyUpdatedAt time.Time
}

func (q *Queries) ListItemCategoryPropertiesForCategories(ctx context.Context, itemCategoryIds []string) ([]ListItemCategoryPropertiesForCategoriesRow, error) {
	query := listItemCategoryPropertiesForCategories
	var queryParams []interface{}
	if len(itemCategoryIds) > 0 {
		for _, v := range itemCategoryIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:item_category_ids*/?", strings.Repeat(",?", len(itemCategoryIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:item_category_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemCategoryPropertiesForCategoriesRow
	for rows.Next() {
		var i ListItemCategoryPropertiesForCategoriesRow
		if err := rows.Scan(
			&i.ItemCategoryID,
			&i.PropertyID,
			&i.PropertyName,
			&i.PropertyCreatedAt,
			&i.PropertyUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItemCategory = `-- name: UpdateItemCategory :execresult
UPDATE item_category SET
    name = COALESCE(?, name),
    notes = COALESCE(?, notes),
    updated_at = NOW(3)
WHERE id = ?
AND account_id = ?
`

type UpdateItemCategoryParams struct {
	Name      sql.NullString
	Notes     sql.NullString
	ID        string
	AccountID sql.NullString
}

func (q *Queries) UpdateItemCategory(ctx context.Context, arg UpdateItemCategoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateItemCategory,
		arg.Name,
		arg.Notes,
		arg.ID,
		arg.AccountID,
	)
}

const updateItemCategoryUnitGroup = `-- name: UpdateItemCategoryUnitGroup :execresult
UPDATE item_category SET
    unit_group_id = ?,
    updated_at = NOW(3)
WHERE id = ?
AND account_id = ?
`

type UpdateItemCategoryUnitGroupParams struct {
	UnitGroupID string
	ID          string
	AccountID   sql.NullString
}

func (q *Queries) UpdateItemCategoryUnitGroup(ctx context.Context, arg UpdateItemCategoryUnitGroupParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateItemCategoryUnitGroup, arg.UnitGroupID, arg.ID, arg.AccountID)
}
