// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_payment_intent.sql

package sqlc

import (
	"context"
)

const deleteOrderPaymentIntent = `-- name: DeleteOrderPaymentIntent :exec
DELETE FROM order_payment_intent WHERE id = ?
`

func (q *Queries) DeleteOrderPaymentIntent(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteOrderPaymentIntentStmt, deleteOrderPaymentIntent, id)
	return err
}

const findOrderPaymentIntentByPaymentIntentID = `-- name: FindOrderPaymentIntentByPaymentIntentID :one
SELECT id, payment_intent_id, sales_order_id
FROM order_payment_intent
WHERE payment_intent_id = ?
LIMIT 1
`

type FindOrderPaymentIntentByPaymentIntentIDRow struct {
	ID              string
	PaymentIntentID string
	SalesOrderID    string
}

func (q *Queries) FindOrderPaymentIntentByPaymentIntentID(ctx context.Context, paymentIntentID string) (FindOrderPaymentIntentByPaymentIntentIDRow, error) {
	row := q.queryRow(ctx, q.findOrderPaymentIntentByPaymentIntentIDStmt, findOrderPaymentIntentByPaymentIntentID, paymentIntentID)
	var i FindOrderPaymentIntentByPaymentIntentIDRow
	err := row.Scan(&i.ID, &i.PaymentIntentID, &i.SalesOrderID)
	return i, err
}

const insertOrderPaymentIntent = `-- name: InsertOrderPaymentIntent :exec
INSERT INTO order_payment_intent (id, payment_intent_id, sales_order_id, created_at, updated_at)
VALUES (?, ?, ?, NOW(3), NOW(3))
`

type InsertOrderPaymentIntentParams struct {
	ID              string
	PaymentIntentID string
	SalesOrderID    string
}

func (q *Queries) InsertOrderPaymentIntent(ctx context.Context, arg InsertOrderPaymentIntentParams) error {
	_, err := q.exec(ctx, q.insertOrderPaymentIntentStmt, insertOrderPaymentIntent, arg.ID, arg.PaymentIntentID, arg.SalesOrderID)
	return err
}
