// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: priority.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const getPriority = `-- name: GetPriority :one
SELECT
    priority.id,
    priority.name,
    priority.code,
    priority.created_at,
    priority.updated_at
FROM priority
WHERE priority.id = ? OR priority.code = ?
`

type GetPriorityParams struct {
	ID   string
	Code string
}

func (q *Queries) GetPriority(ctx context.Context, arg GetPriorityParams) (Priority, error) {
	row := q.db.QueryRowContext(ctx, getPriority, arg.ID, arg.Code)
	var i Priority
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPrioritiesBackward = `-- name: ListPrioritiesBackward :many
SELECT
    priority.id,
    priority.name,
    priority.code,
    priority.created_at,
    priority.updated_at
FROM priority
WHERE (
    ? IS NULL
    OR priority.name LIKE ?
)
AND (
    priority.created_at > ?
    OR (priority.created_at = ? AND priority.id > ?)
)
ORDER BY priority.created_at ASC, priority.id ASC
LIMIT ?
`

type ListPrioritiesBackwardParams struct {
	SearchQuery     sql.NullString
	CursorCreatedAt time.Time
	CursorID        string
	Limit           int32
}

func (q *Queries) ListPrioritiesBackward(ctx context.Context, arg ListPrioritiesBackwardParams) ([]Priority, error) {
	rows, err := q.db.QueryContext(ctx, listPrioritiesBackward,
		arg.SearchQuery,
		arg.SearchQuery,
		arg.CursorCreatedAt,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Priority
	for rows.Next() {
		var i Priority
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrioritiesForward = `-- name: ListPrioritiesForward :many
SELECT
    priority.id,
    priority.name,
    priority.code,
    priority.created_at,
    priority.updated_at
FROM priority
WHERE (
    ? IS NULL
    OR priority.name LIKE ?
)
AND (
    ? IS NULL
    OR priority.created_at < ?
    OR (priority.created_at = ? AND priority.id < ?)
)
ORDER BY priority.created_at DESC, priority.id DESC
LIMIT ?
`

type ListPrioritiesForwardParams struct {
	SearchQuery     sql.NullString
	CursorCreatedAt sql.NullTime
	CursorID        sql.NullString
	Limit           int32
}

func (q *Queries) ListPrioritiesForward(ctx context.Context, arg ListPrioritiesForwardParams) ([]Priority, error) {
	rows, err := q.db.QueryContext(ctx, listPrioritiesForward,
		arg.SearchQuery,
		arg.SearchQuery,
		arg.CursorCreatedAt,
		arg.CursorCreatedAt,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Priority
	for rows.Next() {
		var i Priority
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
