// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: receivable.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const getOpenCreditsByCustomer = `-- name: GetOpenCreditsByCustomer :many
SELECT
    t.id,
    t.number,
    t.created_at,
    tq.value AS original_amount,
    ROUND(
        tq.value - COALESCE((
            SELECT SUM(aq.value)
            FROM transaction_allocation ta
            JOIN quantity aq ON aq.id = ta.amount_id
            WHERE ta.transaction_id = t.id
        ), 0),
    2) AS leftover_amount
FROM transaction t
JOIN quantity tq ON tq.id = t.amount_id
WHERE t.account_id = ?
AND t.customer_account_id = ?
AND t.is_fully_allocated = false
ORDER BY t.created_at DESC
`

type GetOpenCreditsByCustomerParams struct {
	AccountID         string
	CustomerAccountID string
}

type GetOpenCreditsByCustomerRow struct {
	ID             string
	Number         string
	CreatedAt      time.Time
	OriginalAmount string
	LeftoverAmount float64
}

func (q *Queries) GetOpenCreditsByCustomer(ctx context.Context, arg GetOpenCreditsByCustomerParams) ([]GetOpenCreditsByCustomerRow, error) {
	rows, err := q.db.QueryContext(ctx, getOpenCreditsByCustomer, arg.AccountID, arg.CustomerAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOpenCreditsByCustomerRow
	for rows.Next() {
		var i GetOpenCreditsByCustomerRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.CreatedAt,
			&i.OriginalAmount,
			&i.LeftoverAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceivablesBackward = `-- name: ListReceivablesBackward :many
SELECT
    rec.id,
    rec.invoice_number,
    rec.is_paid_in_full,
    rec.created_at,
    rec.po_number,
    rec.customer_id,
    rec.customer_name,
    rec.customer_number,
    rec.remaining_balance
FROM (
    SELECT
        inv.id,
        inv.number AS invoice_number,
        inv.is_paid_in_full,
        inv.created_at,
        so.customer_po_number AS po_number,
        buyer.id AS customer_id,
        buyer.name AS customer_name,
        ar.external_number AS customer_number,
        ROUND(
            COALESCE((
                SELECT SUM(q.value * rt.value)
                FROM invoice_line il
                JOIN quantity q ON q.id = il.quantity_id
                JOIN sales_order_line sol ON sol.id = il.sales_order_line_id
                JOIN rate rt ON rt.id = sol.unit_price_id
                WHERE il.invoice_id = inv.id
            ), 0)
            -
            COALESCE((
                SELECT SUM(aq.value)
                FROM transaction_allocation ta
                JOIN quantity aq ON aq.id = ta.amount_id
                JOIN ` + "`" + `transaction` + "`" + ` txn ON txn.id = ta.transaction_id
                WHERE ta.invoice_id = inv.id
                AND txn.funds_received_at IS NOT NULL
                AND txn.funds_received_at < COALESCE(?, CAST('9999-12-31 23:59:59' AS DATETIME(6)))
            ), 0),
        2) AS remaining_balance
    FROM invoice inv
    JOIN sales_order so ON inv.sales_order_id = so.id
    JOIN account_relation ar ON ar.owner_account_id = inv.account_id
        AND ar.counterparty_account_id = so.buyer_account_id
        AND ar.account_relation_role_code = 'customer'
    JOIN account buyer ON buyer.id = so.buyer_account_id
    WHERE inv.account_id = ?
    AND inv.is_paid_in_full = false
    AND (? IS NULL OR inv.created_at < ?)
    AND (
        ? IS NULL
        OR inv.number LIKE ?
        OR buyer.name LIKE ?
    )
    AND (
        inv.created_at > ?
        OR (inv.created_at = ? AND inv.id > ?)
    )
) rec
WHERE ? = false OR rec.remaining_balance > 0
ORDER BY rec.created_at ASC, rec.id ASC
LIMIT ?
`

type ListReceivablesBackwardParams struct {
	AllocationCutoffDate   sql.NullTime
	AccountID              string
	CutoffDate             sql.NullTime
	SearchQuery            sql.NullString
	CursorCreatedAt        time.Time
	CursorID               string
	RequirePositiveBalance interface{}
	Limit                  int32
}

type ListReceivablesBackwardRow struct {
	ID               string
	InvoiceNumber    string
	IsPaidInFull     bool
	CreatedAt        time.Time
	PoNumber         sql.NullString
	CustomerID       string
	CustomerName     string
	CustomerNumber   string
	RemainingBalance float64
}

func (q *Queries) ListReceivablesBackward(ctx context.Context, arg ListReceivablesBackwardParams) ([]ListReceivablesBackwardRow, error) {
	rows, err := q.db.QueryContext(ctx, listReceivablesBackward,
		arg.AllocationCutoffDate,
		arg.AccountID,
		arg.CutoffDate,
		arg.CutoffDate,
		arg.SearchQuery,
		arg.SearchQuery,
		arg.SearchQuery,
		arg.CursorCreatedAt,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RequirePositiveBalance,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReceivablesBackwardRow
	for rows.Next() {
		var i ListReceivablesBackwardRow
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNumber,
			&i.IsPaidInFull,
			&i.CreatedAt,
			&i.PoNumber,
			&i.CustomerID,
			&i.CustomerName,
			&i.CustomerNumber,
			&i.RemainingBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceivablesByCustomerBackward = `-- name: ListReceivablesByCustomerBackward :many
SELECT
    rec.id,
    rec.invoice_number,
    rec.is_paid_in_full,
    rec.created_at,
    rec.po_number,
    rec.customer_id,
    rec.customer_name,
    rec.customer_number,
    rec.remaining_balance
FROM (
    SELECT
        inv.id,
        inv.number AS invoice_number,
        inv.is_paid_in_full,
        inv.created_at,
        so.customer_po_number AS po_number,
        buyer.id AS customer_id,
        buyer.name AS customer_name,
        ar.external_number AS customer_number,
        ROUND(
            COALESCE((
                SELECT SUM(q.value * rt.value)
                FROM invoice_line il
                JOIN quantity q ON q.id = il.quantity_id
                JOIN sales_order_line sol ON sol.id = il.sales_order_line_id
                JOIN rate rt ON rt.id = sol.unit_price_id
                WHERE il.invoice_id = inv.id
            ), 0)
            -
            COALESCE((
                SELECT SUM(aq.value)
                FROM transaction_allocation ta
                JOIN quantity aq ON aq.id = ta.amount_id
                JOIN ` + "`" + `transaction` + "`" + ` txn ON txn.id = ta.transaction_id
                WHERE ta.invoice_id = inv.id
                AND txn.funds_received_at IS NOT NULL
                AND txn.funds_received_at < COALESCE(?, CAST('9999-12-31 23:59:59' AS DATETIME(6)))
            ), 0),
        2) AS remaining_balance
    FROM invoice inv
    JOIN sales_order so ON inv.sales_order_id = so.id
    JOIN account_relation ar ON ar.owner_account_id = inv.account_id
        AND ar.counterparty_account_id = so.buyer_account_id
        AND ar.account_relation_role_code = 'customer'
    JOIN account buyer ON buyer.id = so.buyer_account_id
    WHERE inv.account_id = ?
    AND so.buyer_account_id = ?
    AND inv.is_paid_in_full = false
    AND (? IS NULL OR inv.created_at < ?)
    AND (
        ? IS NULL
        OR inv.number LIKE ?
        OR buyer.name LIKE ?
    )
    AND (
        inv.created_at > ?
        OR (inv.created_at = ? AND inv.id > ?)
    )
) rec
WHERE ? = false OR rec.remaining_balance > 0
ORDER BY rec.created_at ASC, rec.id ASC
LIMIT ?
`

type ListReceivablesByCustomerBackwardParams struct {
	AllocationCutoffDate   sql.NullTime
	AccountID              string
	CustomerAccountID      string
	CutoffDate             sql.NullTime
	SearchQuery            sql.NullString
	CursorCreatedAt        time.Time
	CursorID               string
	RequirePositiveBalance interface{}
	Limit                  int32
}

type ListReceivablesByCustomerBackwardRow struct {
	ID               string
	InvoiceNumber    string
	IsPaidInFull     bool
	CreatedAt        time.Time
	PoNumber         sql.NullString
	CustomerID       string
	CustomerName     string
	CustomerNumber   string
	RemainingBalance float64
}

func (q *Queries) ListReceivablesByCustomerBackward(ctx context.Context, arg ListReceivablesByCustomerBackwardParams) ([]ListReceivablesByCustomerBackwardRow, error) {
	rows, err := q.db.QueryContext(ctx, listReceivablesByCustomerBackward,
		arg.AllocationCutoffDate,
		arg.AccountID,
		arg.CustomerAccountID,
		arg.CutoffDate,
		arg.CutoffDate,
		arg.SearchQuery,
		arg.SearchQuery,
		arg.SearchQuery,
		arg.CursorCreatedAt,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RequirePositiveBalance,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReceivablesByCustomerBackwardRow
	for rows.Next() {
		var i ListReceivablesByCustomerBackwardRow
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNumber,
			&i.IsPaidInFull,
			&i.CreatedAt,
			&i.PoNumber,
			&i.CustomerID,
			&i.CustomerName,
			&i.CustomerNumber,
			&i.RemainingBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceivablesByCustomerForward = `-- name: ListReceivablesByCustomerForward :many
SELECT
    rec.id,
    rec.invoice_number,
    rec.is_paid_in_full,
    rec.created_at,
    rec.po_number,
    rec.customer_id,
    rec.customer_name,
    rec.customer_number,
    rec.remaining_balance
FROM (
    SELECT
        inv.id,
        inv.number AS invoice_number,
        inv.is_paid_in_full,
        inv.created_at,
        so.customer_po_number AS po_number,
        buyer.id AS customer_id,
        buyer.name AS customer_name,
        ar.external_number AS customer_number,
        ROUND(
            COALESCE((
                SELECT SUM(q.value * rt.value)
                FROM invoice_line il
                JOIN quantity q ON q.id = il.quantity_id
                JOIN sales_order_line sol ON sol.id = il.sales_order_line_id
                JOIN rate rt ON rt.id = sol.unit_price_id
                WHERE il.invoice_id = inv.id
            ), 0)
            -
            COALESCE((
                SELECT SUM(aq.value)
                FROM transaction_allocation ta
                JOIN quantity aq ON aq.id = ta.amount_id
                JOIN ` + "`" + `transaction` + "`" + ` txn ON txn.id = ta.transaction_id
                WHERE ta.invoice_id = inv.id
                AND txn.funds_received_at IS NOT NULL
                AND txn.funds_received_at < COALESCE(?, CAST('9999-12-31 23:59:59' AS DATETIME(6)))
            ), 0),
        2) AS remaining_balance
    FROM invoice inv
    JOIN sales_order so ON inv.sales_order_id = so.id
    JOIN account_relation ar ON ar.owner_account_id = inv.account_id
        AND ar.counterparty_account_id = so.buyer_account_id
        AND ar.account_relation_role_code = 'customer'
    JOIN account buyer ON buyer.id = so.buyer_account_id
    WHERE inv.account_id = ?
    AND so.buyer_account_id = ?
    AND inv.is_paid_in_full = false
    AND (? IS NULL OR inv.created_at < ?)
    AND (
        ? IS NULL
        OR inv.number LIKE ?
        OR buyer.name LIKE ?
    )
    AND (
        ? IS NULL
        OR inv.created_at < ?
        OR (inv.created_at = ? AND inv.id < ?)
    )
) rec
WHERE ? = false OR rec.remaining_balance > 0
ORDER BY rec.created_at DESC, rec.id DESC
LIMIT ?
`

type ListReceivablesByCustomerForwardParams struct {
	AllocationCutoffDate   sql.NullTime
	AccountID              string
	CustomerAccountID      string
	CutoffDate             sql.NullTime
	SearchQuery            sql.NullString
	CursorCreatedAt        sql.NullTime
	CursorID               sql.NullString
	RequirePositiveBalance interface{}
	Limit                  int32
}

type ListReceivablesByCustomerForwardRow struct {
	ID               string
	InvoiceNumber    string
	IsPaidInFull     bool
	CreatedAt        time.Time
	PoNumber         sql.NullString
	CustomerID       string
	CustomerName     string
	CustomerNumber   string
	RemainingBalance float64
}

func (q *Queries) ListReceivablesByCustomerForward(ctx context.Context, arg ListReceivablesByCustomerForwardParams) ([]ListReceivablesByCustomerForwardRow, error) {
	rows, err := q.db.QueryContext(ctx, listReceivablesByCustomerForward,
		arg.AllocationCutoffDate,
		arg.AccountID,
		arg.CustomerAccountID,
		arg.CutoffDate,
		arg.CutoffDate,
		arg.SearchQuery,
		arg.SearchQuery,
		arg.SearchQuery,
		arg.CursorCreatedAt,
		arg.CursorCreatedAt,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RequirePositiveBalance,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReceivablesByCustomerForwardRow
	for rows.Next() {
		var i ListReceivablesByCustomerForwardRow
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNumber,
			&i.IsPaidInFull,
			&i.CreatedAt,
			&i.PoNumber,
			&i.CustomerID,
			&i.CustomerName,
			&i.CustomerNumber,
			&i.RemainingBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceivablesForward = `-- name: ListReceivablesForward :many
SELECT
    rec.id,
    rec.invoice_number,
    rec.is_paid_in_full,
    rec.created_at,
    rec.po_number,
    rec.customer_id,
    rec.customer_name,
    rec.customer_number,
    rec.remaining_balance
FROM (
    SELECT
        inv.id,
        inv.number AS invoice_number,
        inv.is_paid_in_full,
        inv.created_at,
        so.customer_po_number AS po_number,
        buyer.id AS customer_id,
        buyer.name AS customer_name,
        ar.external_number AS customer_number,
        ROUND(
            COALESCE((
                SELECT SUM(q.value * rt.value)
                FROM invoice_line il
                JOIN quantity q ON q.id = il.quantity_id
                JOIN sales_order_line sol ON sol.id = il.sales_order_line_id
                JOIN rate rt ON rt.id = sol.unit_price_id
                WHERE il.invoice_id = inv.id
            ), 0)
            -
            COALESCE((
                SELECT SUM(aq.value)
                FROM transaction_allocation ta
                JOIN quantity aq ON aq.id = ta.amount_id
                JOIN ` + "`" + `transaction` + "`" + ` txn ON txn.id = ta.transaction_id
                WHERE ta.invoice_id = inv.id
                AND txn.funds_received_at IS NOT NULL
                AND txn.funds_received_at < COALESCE(?, CAST('9999-12-31 23:59:59' AS DATETIME(6)))
            ), 0),
        2) AS remaining_balance
    FROM invoice inv
    JOIN sales_order so ON inv.sales_order_id = so.id
    JOIN account_relation ar ON ar.owner_account_id = inv.account_id
        AND ar.counterparty_account_id = so.buyer_account_id
        AND ar.account_relation_role_code = 'customer'
    JOIN account buyer ON buyer.id = so.buyer_account_id
    WHERE inv.account_id = ?
    AND inv.is_paid_in_full = false
    AND (? IS NULL OR inv.created_at < ?)
    AND (
        ? IS NULL
        OR inv.number LIKE ?
        OR buyer.name LIKE ?
    )
    AND (
        ? IS NULL
        OR inv.created_at < ?
        OR (inv.created_at = ? AND inv.id < ?)
    )
) rec
WHERE ? = false OR rec.remaining_balance > 0
ORDER BY rec.created_at DESC, rec.id DESC
LIMIT ?
`

type ListReceivablesForwardParams struct {
	AllocationCutoffDate   sql.NullTime
	AccountID              string
	CutoffDate             sql.NullTime
	SearchQuery            sql.NullString
	CursorCreatedAt        sql.NullTime
	CursorID               sql.NullString
	RequirePositiveBalance interface{}
	Limit                  int32
}

type ListReceivablesForwardRow struct {
	ID               string
	InvoiceNumber    string
	IsPaidInFull     bool
	CreatedAt        time.Time
	PoNumber         sql.NullString
	CustomerID       string
	CustomerName     string
	CustomerNumber   string
	RemainingBalance float64
}

// Nets only allocations whose transaction has a funds-received date before the cutoff, then drops
// anything already settled by then; without a cutoff every unpaid invoice is reported as-is.
func (q *Queries) ListReceivablesForward(ctx context.Context, arg ListReceivablesForwardParams) ([]ListReceivablesForwardRow, error) {
	rows, err := q.db.QueryContext(ctx, listReceivablesForward,
		arg.AllocationCutoffDate,
		arg.AccountID,
		arg.CutoffDate,
		arg.CutoffDate,
		arg.SearchQuery,
		arg.SearchQuery,
		arg.SearchQuery,
		arg.CursorCreatedAt,
		arg.CursorCreatedAt,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RequirePositiveBalance,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReceivablesForwardRow
	for rows.Next() {
		var i ListReceivablesForwardRow
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNumber,
			&i.IsPaidInFull,
			&i.CreatedAt,
			&i.PoNumber,
			&i.CustomerID,
			&i.CustomerName,
			&i.CustomerNumber,
			&i.RemainingBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
