// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: receiving_order.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const calculateQuantityYetToBeReceived = `-- name: CalculateQuantityYetToBeReceived :one
SELECT
    oq.value AS ordered_value,
    COALESCE(SUM(CAST(rq.value AS DECIMAL(20,6))), 0) AS received_total,
    ou.id AS unit_id
FROM receiving_order_line rol
JOIN sales_order_line sol ON rol.sales_order_line_id = sol.id
JOIN quantity oq ON sol.quantity_id = oq.id
JOIN unit ou ON oq.unit_id = ou.id
LEFT JOIN receiving_order_line all_rol ON all_rol.sales_order_line_id = sol.id
LEFT JOIN quantity rq ON all_rol.quantity_id = rq.id
WHERE rol.id = ?
GROUP BY oq.value, ou.id
`

type CalculateQuantityYetToBeReceivedRow struct {
	OrderedValue  string
	ReceivedTotal interface{}
	UnitID        string
}

func (q *Queries) CalculateQuantityYetToBeReceived(ctx context.Context, lineID string) (CalculateQuantityYetToBeReceivedRow, error) {
	row := q.db.QueryRowContext(ctx, calculateQuantityYetToBeReceived, lineID)
	var i CalculateQuantityYetToBeReceivedRow
	err := row.Scan(&i.OrderedValue, &i.ReceivedTotal, &i.UnitID)
	return i, err
}

const checkAllLinesStocked = `-- name: CheckAllLinesStocked :one
SELECT COUNT(*) AS unstocked_count
FROM receiving_order_line rol
JOIN receiving_order ro ON rol.receiving_order_id = ro.id
WHERE rol.receiving_order_id = ?
AND ro.account_id = ?
AND rol.stocked_at IS NULL
`

type CheckAllLinesStockedParams struct {
	ReceivingOrderID string
	AccountID        string
}

func (q *Queries) CheckAllLinesStocked(ctx context.Context, arg CheckAllLinesStockedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkAllLinesStocked, arg.ReceivingOrderID, arg.AccountID)
	var unstocked_count int64
	err := row.Scan(&unstocked_count)
	return unstocked_count, err
}

const countDeliveriesByPurchaseOrder = `-- name: CountDeliveriesByPurchaseOrder :one
SELECT COUNT(*) AS delivery_count
FROM delivery
WHERE sales_order_id = ?
`

func (q *Queries) CountDeliveriesByPurchaseOrder(ctx context.Context, purchaseOrderID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeliveriesByPurchaseOrder, purchaseOrderID)
	var delivery_count int64
	err := row.Scan(&delivery_count)
	return delivery_count, err
}

const createReceivingOrder = `-- name: CreateReceivingOrder :exec
INSERT INTO receiving_order (id, number, order_id, account_id, created_at, updated_at)
VALUES (?, ?, ?, ?, NOW(3), NOW(3))
`

type CreateReceivingOrderParams struct {
	ID        string
	Number    string
	OrderID   string
	AccountID string
}

func (q *Queries) CreateReceivingOrder(ctx context.Context, arg CreateReceivingOrderParams) error {
	_, err := q.db.ExecContext(ctx, createReceivingOrder,
		arg.ID,
		arg.Number,
		arg.OrderID,
		arg.AccountID,
	)
	return err
}

const createReceivingOrderLine = `-- name: CreateReceivingOrderLine :exec
INSERT INTO receiving_order_line (id, receiving_order_id, quantity_id, sales_order_line_id, created_at, updated_at)
VALUES (?, ?, ?, ?, NOW(3), NOW(3))
`

type CreateReceivingOrderLineParams struct {
	ID               string
	ReceivingOrderID string
	QuantityID       string
	SalesOrderLineID string
}

func (q *Queries) CreateReceivingOrderLine(ctx context.Context, arg CreateReceivingOrderLineParams) error {
	_, err := q.db.ExecContext(ctx, createReceivingOrderLine,
		arg.ID,
		arg.ReceivingOrderID,
		arg.QuantityID,
		arg.SalesOrderLineID,
	)
	return err
}

const deleteDuplicateReceivingOrderLines = `-- name: DeleteDuplicateReceivingOrderLines :exec
DELETE rol FROM receiving_order_line rol
JOIN receiving_order ro ON rol.receiving_order_id = ro.id
JOIN (
    SELECT
        sales_order_line_id,
        MIN(id) AS keep_id
    FROM receiving_order_line
    WHERE receiving_order_line.receiving_order_id = ?
    GROUP BY sales_order_line_id
    HAVING COUNT(*) > 1
) dup ON dup.sales_order_line_id = rol.sales_order_line_id
WHERE rol.receiving_order_id = ?
AND ro.account_id = ?
AND rol.id <> dup.keep_id
`

type DeleteDuplicateReceivingOrderLinesParams struct {
	ReceivingOrderID string
	AccountID        string
}

func (q *Queries) DeleteDuplicateReceivingOrderLines(ctx context.Context, arg DeleteDuplicateReceivingOrderLinesParams) error {
	_, err := q.db.ExecContext(ctx, deleteDuplicateReceivingOrderLines, arg.ReceivingOrderID, arg.ReceivingOrderID, arg.AccountID)
	return err
}

const deleteReceivingOrderByOrderID = `-- name: DeleteReceivingOrderByOrderID :exec
DELETE FROM receiving_order WHERE order_id = ?
`

func (q *Queries) DeleteReceivingOrderByOrderID(ctx context.Context, orderID string) error {
	_, err := q.db.ExecContext(ctx, deleteReceivingOrderByOrderID, orderID)
	return err
}

const deleteReceivingOrderLinesByOrderID = `-- name: DeleteReceivingOrderLinesByOrderID :exec
DELETE rol FROM receiving_order_line rol
JOIN receiving_order ro ON ro.id = rol.receiving_order_id
WHERE ro.order_id = ?
`

func (q *Queries) DeleteReceivingOrderLinesByOrderID(ctx context.Context, orderID string) error {
	_, err := q.db.ExecContext(ctx, deleteReceivingOrderLinesByOrderID, orderID)
	return err
}

const deleteReceivingOrderLinesByOrderLineID = `-- name: DeleteReceivingOrderLinesByOrderLineID :exec
DELETE FROM receiving_order_line WHERE sales_order_line_id = ?
`

func (q *Queries) DeleteReceivingOrderLinesByOrderLineID(ctx context.Context, salesOrderLineID string) error {
	_, err := q.db.ExecContext(ctx, deleteReceivingOrderLinesByOrderLineID, salesOrderLineID)
	return err
}

const findUnstockedLineIDs = `-- name: FindUnstockedLineIDs :many
SELECT
    rol.id,
    rol.sales_order_line_id AS order_line_id
FROM receiving_order_line rol
JOIN receiving_order ro ON rol.receiving_order_id = ro.id
LEFT JOIN quantity q ON rol.quantity_id = q.id
WHERE rol.receiving_order_id = ?
AND ro.account_id = ?
AND ro.completed_at IS NULL
AND rol.stocked_at IS NULL
AND (
    ? = false
    OR (q.value IS NOT NULL AND CAST(q.value AS DECIMAL(20,6)) > 0)
)
`

type FindUnstockedLineIDsParams struct {
	ReceivingOrderID string
	AccountID        string
	EnforceNonZero   interface{}
}

type FindUnstockedLineIDsRow struct {
	ID          string
	OrderLineID string
}

func (q *Queries) FindUnstockedLineIDs(ctx context.Context, arg FindUnstockedLineIDsParams) ([]FindUnstockedLineIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, findUnstockedLineIDs, arg.ReceivingOrderID, arg.AccountID, arg.EnforceNonZero)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindUnstockedLineIDsRow
	for rows.Next() {
		var i FindUnstockedLineIDsRow
		if err := rows.Scan(&i.ID, &i.OrderLineID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllocationSumForIssue = `-- name: GetAllocationSumForIssue :one
SELECT COALESCE(SUM(CAST(q.value AS DECIMAL(65,30)) * (u.ratio_numerator / u.ratio_denominator)), 0) AS total_allocated
FROM inventory_allocation ia
JOIN quantity q ON q.id = ia.quantity_id
JOIN unit u ON u.id = q.unit_id
WHERE ia.inventory_issue_id = ?
`

// Each allocation is taken through its own unit's ratio before it is added: an issue in pounds can be
// covered by allocations recorded in grams, and once they are added together the caller has nothing
// left to convert with. Divide the total by a unit's ratio to read it in that unit.
func (q *Queries) GetAllocationSumForIssue(ctx context.Context, issueID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getAllocationSumForIssue, issueID)
	var total_allocated interface{}
	err := row.Scan(&total_allocated)
	return total_allocated, err
}

const getLotByKey = `-- name: GetLotByKey :one
SELECT id FROM lot
WHERE account_id = ?
AND item_id = ?
AND lot_number = ?
`

type GetLotByKeyParams struct {
	AccountID string
	ItemID    string
	LotNumber string
}

func (q *Queries) GetLotByKey(ctx context.Context, arg GetLotByKeyParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getLotByKey, arg.AccountID, arg.ItemID, arg.LotNumber)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getOrderedQuantityForLine = `-- name: GetOrderedQuantityForLine :many
SELECT
    sol.id AS order_line_id,
    oq.value AS ordered_value,
    COALESCE(SUM(CAST(rq.value AS DECIMAL(20,6))), 0) AS received_total,
    ou.id AS unit_id
FROM sales_order_line sol
JOIN quantity oq ON sol.quantity_id = oq.id
JOIN unit ou ON oq.unit_id = ou.id
LEFT JOIN receiving_order_line stocked_rol ON stocked_rol.sales_order_line_id = sol.id AND stocked_rol.stocked_at IS NOT NULL
LEFT JOIN quantity rq ON stocked_rol.quantity_id = rq.id
WHERE sol.id IN (/*SLICE:order_line_ids*/?)
GROUP BY sol.id, oq.value, ou.id
`

type GetOrderedQuantityForLineRow struct {
	OrderLineID   string
	OrderedValue  string
	ReceivedTotal interface{}
	UnitID        string
}

func (q *Queries) GetOrderedQuantityForLine(ctx context.Context, orderLineIds []string) ([]GetOrderedQuantityForLineRow, error) {
	query := getOrderedQuantityForLine
	var queryParams []interface{}
	if len(orderLineIds) > 0 {
		for _, v := range orderLineIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:order_line_ids*/?", strings.Repeat(",?", len(orderLineIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:order_line_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderedQuantityForLineRow
	for rows.Next() {
		var i GetOrderedQuantityForLineRow
		if err := rows.Scan(
			&i.OrderLineID,
			&i.OrderedValue,
			&i.ReceivedTotal,
			&i.UnitID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPurchaseOrderIDForReceivingOrder = `-- name: GetPurchaseOrderIDForReceivingOrder :one
SELECT ro.order_id AS purchase_order_id
FROM receiving_order ro
WHERE ro.id = ?
AND ro.account_id = ?
`

type GetPurchaseOrderIDForReceivingOrderParams struct {
	ReceivingOrderID string
	AccountID        string
}

func (q *Queries) GetPurchaseOrderIDForReceivingOrder(ctx context.Context, arg GetPurchaseOrderIDForReceivingOrderParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getPurchaseOrderIDForReceivingOrder, arg.ReceivingOrderID, arg.AccountID)
	var purchase_order_id string
	err := row.Scan(&purchase_order_id)
	return purchase_order_id, err
}

const getReceivingOrderByID = `-- name: GetReceivingOrderByID :one
SELECT
    ro.id,
    ro.number,
    ro.completed_at,
    ro.created_at,
    ro.updated_at,
    so.id AS purchase_order_id,
    so.number AS purchase_order_number,
    a.id AS supplier_id,
    a.name AS supplier_name,
    ar.external_number AS supplier_number,
    so.note
FROM receiving_order ro
JOIN sales_order so ON ro.order_id = so.id
LEFT JOIN account_relation ar ON so.seller_account_id = ar.counterparty_account_id AND ar.owner_account_id = ro.account_id
LEFT JOIN account a ON ar.counterparty_account_id = a.id
WHERE ro.id = ?
AND ro.account_id = ?
`

type GetReceivingOrderByIDParams struct {
	ID        string
	AccountID string
}

type GetReceivingOrderByIDRow struct {
	ID                  string
	Number              string
	CompletedAt         sql.NullTime
	CreatedAt           time.Time
	UpdatedAt           time.Time
	PurchaseOrderID     string
	PurchaseOrderNumber string
	SupplierID          sql.NullString
	SupplierName        sql.NullString
	SupplierNumber      sql.NullString
	Note                sql.NullString
}

func (q *Queries) GetReceivingOrderByID(ctx context.Context, arg GetReceivingOrderByIDParams) (GetReceivingOrderByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getReceivingOrderByID, arg.ID, arg.AccountID)
	var i GetReceivingOrderByIDRow
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PurchaseOrderID,
		&i.PurchaseOrderNumber,
		&i.SupplierID,
		&i.SupplierName,
		&i.SupplierNumber,
		&i.Note,
	)
	return i, err
}

const getReceivingOrderByOrderID = `-- name: GetReceivingOrderByOrderID :one
SELECT ro.id
FROM receiving_order ro
WHERE ro.order_id = ?
`

func (q *Queries) GetReceivingOrderByOrderID(ctx context.Context, orderID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getReceivingOrderByOrderID, orderID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getReceivingOrderLine = `-- name: GetReceivingOrderLine :one
SELECT
    rol.id,
    rol.stocked_at,
    rol.created_at,
    rol.updated_at,
    q.id AS quantity_id,
    q.value AS quantity_value,
    qu.id AS quantity_unit_id,
    qu.abbreviation AS quantity_unit_abbreviation,
    sol.id AS order_line_id,
    sol.item_id AS order_line_item_id,
    sol.product_id AS order_line_product_id,
    i.sku AS order_line_item_sku,
    i.description AS order_line_item_description,
    oq.value AS order_line_quantity_ordered,
    ou.id AS order_line_unit_id,
    ou.abbreviation AS order_line_unit_abbreviation,
    (SELECT CAST(SUM(rq.value) AS CHAR) FROM delivery_line dl JOIN quantity rq ON dl.quantity_id = rq.id WHERE dl.receiving_order_line_id = rol.id AND dl.rejected_at IS NOT NULL) AS rejected_quantity_value
FROM receiving_order_line rol
JOIN quantity q ON rol.quantity_id = q.id
JOIN unit qu ON q.unit_id = qu.id
JOIN sales_order_line sol ON rol.sales_order_line_id = sol.id
LEFT JOIN item i ON sol.item_id = i.id
JOIN quantity oq ON sol.quantity_id = oq.id
JOIN unit ou ON oq.unit_id = ou.id
WHERE rol.id = ?
`

type GetReceivingOrderLineRow struct {
	ID                        string
	StockedAt                 sql.NullTime
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
	QuantityID                string
	QuantityValue             string
	QuantityUnitID            string
	QuantityUnitAbbreviation  string
	OrderLineID               string
	OrderLineItemID           sql.NullString
	OrderLineProductID        sql.NullString
	OrderLineItemSku          sql.NullString
	OrderLineItemDescription  sql.NullString
	OrderLineQuantityOrdered  string
	OrderLineUnitID           string
	OrderLineUnitAbbreviation string
	RejectedQuantityValue     interface{}
}

func (q *Queries) GetReceivingOrderLine(ctx context.Context, lineID string) (GetReceivingOrderLineRow, error) {
	row := q.db.QueryRowContext(ctx, getReceivingOrderLine, lineID)
	var i GetReceivingOrderLineRow
	err := row.Scan(
		&i.ID,
		&i.StockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QuantityID,
		&i.QuantityValue,
		&i.QuantityUnitID,
		&i.QuantityUnitAbbreviation,
		&i.OrderLineID,
		&i.OrderLineItemID,
		&i.OrderLineProductID,
		&i.OrderLineItemSku,
		&i.OrderLineItemDescription,
		&i.OrderLineQuantityOrdered,
		&i.OrderLineUnitID,
		&i.OrderLineUnitAbbreviation,
		&i.RejectedQuantityValue,
	)
	return i, err
}

const getReceivingOrderLineUnitPrice = `-- name: GetReceivingOrderLineUnitPrice :many
SELECT
    rol.id AS receiving_order_line_id,
    sol.item_id,
    r.value AS unit_price_value,
    r.numerator_unit_id AS unit_price_numerator_unit_id,
    r.denominator_unit_id AS unit_price_denominator_unit_id,
    qu.id AS quantity_unit_id
FROM receiving_order_line rol
JOIN sales_order_line sol ON rol.sales_order_line_id = sol.id
JOIN rate r ON sol.unit_price_id = r.id
JOIN quantity q ON rol.quantity_id = q.id
JOIN unit qu ON q.unit_id = qu.id
WHERE rol.receiving_order_id = ?
`

type GetReceivingOrderLineUnitPriceRow struct {
	ReceivingOrderLineID       string
	ItemID                     sql.NullString
	UnitPriceValue             string
	UnitPriceNumeratorUnitID   string
	UnitPriceDenominatorUnitID string
	QuantityUnitID             string
}

func (q *Queries) GetReceivingOrderLineUnitPrice(ctx context.Context, receivingOrderID string) ([]GetReceivingOrderLineUnitPriceRow, error) {
	rows, err := q.db.QueryContext(ctx, getReceivingOrderLineUnitPrice, receivingOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReceivingOrderLineUnitPriceRow
	for rows.Next() {
		var i GetReceivingOrderLineUnitPriceRow
		if err := rows.Scan(
			&i.ReceivingOrderLineID,
			&i.ItemID,
			&i.UnitPriceValue,
			&i.UnitPriceNumeratorUnitID,
			&i.UnitPriceDenominatorUnitID,
			&i.QuantityUnitID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasUnstockedReceivingOrderLineForOrderLine = `-- name: HasUnstockedReceivingOrderLineForOrderLine :one
SELECT EXISTS(
    SELECT 1 FROM receiving_order_line
    WHERE sales_order_line_id = ?
    AND stocked_at IS NULL
) AS has_unstocked
`

func (q *Queries) HasUnstockedReceivingOrderLineForOrderLine(ctx context.Context, salesOrderLineID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasUnstockedReceivingOrderLineForOrderLine, salesOrderLineID)
	var has_unstocked bool
	err := row.Scan(&has_unstocked)
	return has_unstocked, err
}

const insertDelivery = `-- name: InsertDelivery :exec
INSERT INTO delivery (id, number, sales_order_id, account_id, delivery_status_code, accepted_at, rejected_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, NOW(3), NOW(3))
`

type InsertDeliveryParams struct {
	ID                 string
	Number             string
	SalesOrderID       string
	AccountID          string
	DeliveryStatusCode string
	AcceptedAt         sql.NullTime
	RejectedAt         sql.NullTime
}

func (q *Queries) InsertDelivery(ctx context.Context, arg InsertDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, insertDelivery,
		arg.ID,
		arg.Number,
		arg.SalesOrderID,
		arg.AccountID,
		arg.DeliveryStatusCode,
		arg.AcceptedAt,
		arg.RejectedAt,
	)
	return err
}

const insertDeliveryLine = `-- name: InsertDeliveryLine :exec
INSERT INTO delivery_line (id, delivery_id, receiving_order_line_id, quantity_id, unit_cost_id, storage_location_id, lot_id, accepted_at, rejected_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, NOW(3), NOW(3))
`

type InsertDeliveryLineParams struct {
	ID                   string
	DeliveryID           string
	ReceivingOrderLineID string
	QuantityID           string
	UnitCostID           string
	StorageLocationID    sql.NullString
	LotID                sql.NullString
	AcceptedAt           sql.NullTime
	RejectedAt           sql.NullTime
}

func (q *Queries) InsertDeliveryLine(ctx context.Context, arg InsertDeliveryLineParams) error {
	_, err := q.db.ExecContext(ctx, insertDeliveryLine,
		arg.ID,
		arg.DeliveryID,
		arg.ReceivingOrderLineID,
		arg.QuantityID,
		arg.UnitCostID,
		arg.StorageLocationID,
		arg.LotID,
		arg.AcceptedAt,
		arg.RejectedAt,
	)
	return err
}

const insertInventoryReceiptForDelivery = `-- name: InsertInventoryReceiptForDelivery :exec
INSERT INTO inventory_receipt (
    id, owner_account_id, holder_account_id, item_id,
    quantity_id, unit_cost_id, status_code,
    storage_location_id, lot_id, order_id,
    received_at, created_at, updated_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    'available',
    ?,
    ?,
    ?,
    NOW(3),
    NOW(3),
    NOW(3)
)
`

type InsertInventoryReceiptForDeliveryParams struct {
	ID                string
	AccountID         string
	ItemID            string
	QuantityID        string
	UnitCostID        string
	StorageLocationID sql.NullString
	LotID             sql.NullString
	OrderID           sql.NullString
}

func (q *Queries) InsertInventoryReceiptForDelivery(ctx context.Context, arg InsertInventoryReceiptForDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, insertInventoryReceiptForDelivery,
		arg.ID,
		arg.AccountID,
		arg.AccountID,
		arg.ItemID,
		arg.QuantityID,
		arg.UnitCostID,
		arg.StorageLocationID,
		arg.LotID,
		arg.OrderID,
	)
	return err
}

const isReceivingOrderInAccount = `-- name: IsReceivingOrderInAccount :one
SELECT EXISTS(
    SELECT 1 FROM receiving_order
    WHERE id = ?
    AND account_id = ?
) AS order_exists
`

type IsReceivingOrderInAccountParams struct {
	ReceivingOrderID string
	AccountID        string
}

func (q *Queries) IsReceivingOrderInAccount(ctx context.Context, arg IsReceivingOrderInAccountParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isReceivingOrderInAccount, arg.ReceivingOrderID, arg.AccountID)
	var order_exists bool
	err := row.Scan(&order_exists)
	return order_exists, err
}

const isReceivingOrderLineInOrder = `-- name: IsReceivingOrderLineInOrder :one
SELECT EXISTS(
    SELECT 1 FROM receiving_order_line
    WHERE id = ?
    AND receiving_order_id = ?
) AS line_exists
`

type IsReceivingOrderLineInOrderParams struct {
	LineID           string
	ReceivingOrderID string
}

func (q *Queries) IsReceivingOrderLineInOrder(ctx context.Context, arg IsReceivingOrderLineInOrderParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isReceivingOrderLineInOrder, arg.LineID, arg.ReceivingOrderID)
	var line_exists bool
	err := row.Scan(&line_exists)
	return line_exists, err
}

const listReceivingOrderLinesByOrderID = `-- name: ListReceivingOrderLinesByOrderID :many
SELECT
    rol.id,
    rol.stocked_at,
    rol.created_at,
    rol.updated_at,
    q.id AS quantity_id,
    q.value AS quantity_value,
    qu.id AS quantity_unit_id,
    qu.abbreviation AS quantity_unit_abbreviation,
    sol.id AS order_line_id,
    sol.item_id AS order_line_item_id,
    sol.product_id AS order_line_product_id,
    i.sku AS order_line_item_sku,
    i.description AS order_line_item_description,
    oq.value AS order_line_quantity_ordered,
    ou.id AS order_line_unit_id,
    ou.abbreviation AS order_line_unit_abbreviation,
    (SELECT CAST(SUM(rq.value) AS CHAR) FROM delivery_line dl JOIN quantity rq ON dl.quantity_id = rq.id WHERE dl.receiving_order_line_id = rol.id AND dl.rejected_at IS NOT NULL) AS rejected_quantity_value
FROM receiving_order_line rol
JOIN quantity q ON rol.quantity_id = q.id
JOIN unit qu ON q.unit_id = qu.id
JOIN sales_order_line sol ON rol.sales_order_line_id = sol.id
LEFT JOIN item i ON sol.item_id = i.id
JOIN quantity oq ON sol.quantity_id = oq.id
JOIN unit ou ON oq.unit_id = ou.id
WHERE rol.receiving_order_id = ?
ORDER BY rol.created_at ASC, rol.id ASC
`

type ListReceivingOrderLinesByOrderIDRow struct {
	ID                        string
	StockedAt                 sql.NullTime
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
	QuantityID                string
	QuantityValue             string
	QuantityUnitID            string
	QuantityUnitAbbreviation  string
	OrderLineID               string
	OrderLineItemID           sql.NullString
	OrderLineProductID        sql.NullString
	OrderLineItemSku          sql.NullString
	OrderLineItemDescription  sql.NullString
	OrderLineQuantityOrdered  string
	OrderLineUnitID           string
	OrderLineUnitAbbreviation string
	RejectedQuantityValue     interface{}
}

func (q *Queries) ListReceivingOrderLinesByOrderID(ctx context.Context, receivingOrderID string) ([]ListReceivingOrderLinesByOrderIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listReceivingOrderLinesByOrderID, receivingOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReceivingOrderLinesByOrderIDRow
	for rows.Next() {
		var i ListReceivingOrderLinesByOrderIDRow
		if err := rows.Scan(
			&i.ID,
			&i.StockedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.QuantityID,
			&i.QuantityValue,
			&i.QuantityUnitID,
			&i.QuantityUnitAbbreviation,
			&i.OrderLineID,
			&i.OrderLineItemID,
			&i.OrderLineProductID,
			&i.OrderLineItemSku,
			&i.OrderLineItemDescription,
			&i.OrderLineQuantityOrdered,
			&i.OrderLineUnitID,
			&i.OrderLineUnitAbbreviation,
			&i.RejectedQuantityValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceivingOrdersBackward = `-- name: ListReceivingOrdersBackward :many
SELECT
    ro.id,
    ro.number,
    ro.completed_at,
    ro.created_at,
    ro.updated_at,
    so.id AS purchase_order_id,
    so.number AS purchase_order_number,
    a.id AS supplier_id,
    a.name AS supplier_name,
    ar.external_number AS supplier_number,
    COUNT(rol.id) AS line_count,
    CASE
        WHEN COUNT(rol.id) = 0 THEN 0
        ELSE ROUND(COUNT(CASE WHEN rol.stocked_at IS NOT NULL THEN 1 END) * 100.0 / COUNT(rol.id), 2)
    END AS completion_percentage
FROM receiving_order ro
JOIN sales_order so ON ro.order_id = so.id
LEFT JOIN account_relation ar ON so.seller_account_id = ar.counterparty_account_id AND ar.owner_account_id = ro.account_id
LEFT JOIN account a ON ar.counterparty_account_id = a.id
LEFT JOIN receiving_order_line rol ON rol.receiving_order_id = ro.id
WHERE ro.account_id = ?
AND (
    ? IS NULL
    OR ro.number LIKE ?
    OR so.number LIKE ?
)
AND (
    ? IS NULL
    OR (? = 'open' AND ro.completed_at IS NULL)
    OR (? = 'completed' AND ro.completed_at IS NOT NULL)
)
AND (
    ? = false
    OR EXISTS (
        SELECT 1 FROM receiving_order_line rol2
        JOIN sales_order_line sol ON rol2.sales_order_line_id = sol.id
        WHERE rol2.receiving_order_id = ro.id
        AND sol.item_id IN (/*SLICE:item_ids*/?)
    )
)
AND (
    ? = false
    OR so.seller_account_id IN (/*SLICE:supplier_ids*/?)
)
AND (
    ? IS NULL
    OR ro.created_at >= ?
)
AND (
    ? IS NULL
    OR ro.created_at <= ?
)
AND (
    ro.created_at > ?
    OR (ro.created_at = ? AND ro.id > ?)
)
GROUP BY ro.id, ro.number, ro.completed_at, ro.created_at, ro.updated_at, so.id, so.number, a.id, a.name, ar.external_number
ORDER BY ro.created_at ASC, ro.id ASC
LIMIT ?
`

type ListReceivingOrdersBackwardParams struct {
	AccountID             string
	SearchQuery           sql.NullString
	Status                interface{}
	IncludeItemFilter     interface{}
	ItemIds               []sql.NullString
	IncludeSupplierFilter interface{}
	SupplierIds           []string
	StartDate             sql.NullTime
	EndDate               sql.NullTime
	CursorCreatedAt       time.Time
	CursorID              string
	Limit                 int32
}

type ListReceivingOrdersBackwardRow struct {
	ID                   string
	Number               string
	CompletedAt          sql.NullTime
	CreatedAt            time.Time
	UpdatedAt            time.Time
	PurchaseOrderID      string
	PurchaseOrderNumber  string
	SupplierID           sql.NullString
	SupplierName         sql.NullString
	SupplierNumber       sql.NullString
	LineCount            int64
	CompletionPercentage interface{}
}

func (q *Queries) ListReceivingOrdersBackward(ctx context.Context, arg ListReceivingOrdersBackwardParams) ([]ListReceivingOrdersBackwardRow, error) {
	query := listReceivingOrdersBackward
	var queryParams []interface{}
	queryParams = append(queryParams, arg.AccountID)
	queryParams = append(queryParams, arg.SearchQuery)
	queryParams = append(queryParams, arg.SearchQuery)
	queryParams = append(queryParams, arg.SearchQuery)
	queryParams = append(queryParams, arg.Status)
	queryParams = append(queryParams, arg.Status)
	queryParams = append(queryParams, arg.Status)
	queryParams = append(queryParams, arg.IncludeItemFilter)
	if len(arg.ItemIds) > 0 {
		for _, v := range arg.ItemIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:item_ids*/?", strings.Repeat(",?", len(arg.ItemIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:item_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.IncludeSupplierFilter)
	if len(arg.SupplierIds) > 0 {
		for _, v := range arg.SupplierIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:supplier_ids*/?", strings.Repeat(",?", len(arg.SupplierIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:supplier_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.StartDate)
	queryParams = append(queryParams, arg.StartDate)
	queryParams = append(queryParams, arg.EndDate)
	queryParams = append(queryParams, arg.EndDate)
	queryParams = append(queryParams, arg.CursorCreatedAt)
	queryParams = append(queryParams, arg.CursorCreatedAt)
	queryParams = append(queryParams, arg.CursorID)
	queryParams = append(queryParams, arg.Limit)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReceivingOrdersBackwardRow
	for rows.Next() {
		var i ListReceivingOrdersBackwardRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PurchaseOrderID,
			&i.PurchaseOrderNumber,
			&i.SupplierID,
			&i.SupplierName,
			&i.SupplierNumber,
			&i.LineCount,
			&i.CompletionPercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceivingOrdersForward = `-- name: ListReceivingOrdersForward :many
SELECT
    ro.id,
    ro.number,
    ro.completed_at,
    ro.created_at,
    ro.updated_at,
    so.id AS purchase_order_id,
    so.number AS purchase_order_number,
    a.id AS supplier_id,
    a.name AS supplier_name,
    ar.external_number AS supplier_number,
    COUNT(rol.id) AS line_count,
    CASE
        WHEN COUNT(rol.id) = 0 THEN 0
        ELSE ROUND(COUNT(CASE WHEN rol.stocked_at IS NOT NULL THEN 1 END) * 100.0 / COUNT(rol.id), 2)
    END AS completion_percentage
FROM receiving_order ro
JOIN sales_order so ON ro.order_id = so.id
LEFT JOIN account_relation ar ON so.seller_account_id = ar.counterparty_account_id AND ar.owner_account_id = ro.account_id
LEFT JOIN account a ON ar.counterparty_account_id = a.id
LEFT JOIN receiving_order_line rol ON rol.receiving_order_id = ro.id
WHERE ro.account_id = ?
AND (
    ? IS NULL
    OR ro.number LIKE ?
    OR so.number LIKE ?
)
AND (
    ? IS NULL
    OR (? = 'open' AND ro.completed_at IS NULL)
    OR (? = 'completed' AND ro.completed_at IS NOT NULL)
)
AND (
    ? = false
    OR EXISTS (
        SELECT 1 FROM receiving_order_line rol2
        JOIN sales_order_line sol ON rol2.sales_order_line_id = sol.id
        WHERE rol2.receiving_order_id = ro.id
        AND sol.item_id IN (/*SLICE:item_ids*/?)
    )
)
AND (
    ? = false
    OR so.seller_account_id IN (/*SLICE:supplier_ids*/?)
)
AND (
    ? IS NULL
    OR ro.created_at >= ?
)
AND (
    ? IS NULL
    OR ro.created_at <= ?
)
AND (
    ? IS NULL
    OR ro.created_at < ?
    OR (ro.created_at = ? AND ro.id < ?)
)
GROUP BY ro.id, ro.number, ro.completed_at, ro.created_at, ro.updated_at, so.id, so.number, a.id, a.name, ar.external_number
ORDER BY ro.created_at DESC, ro.id DESC
LIMIT ?
`

type ListReceivingOrdersForwardParams struct {
	AccountID             string
	SearchQuery           sql.NullString
	Status                interface{}
	IncludeItemFilter     interface{}
	ItemIds               []sql.NullString
	IncludeSupplierFilter interface{}
	SupplierIds           []string
	StartDate             sql.NullTime
	EndDate               sql.NullTime
	CursorCreatedAt       sql.NullTime
	CursorID              sql.NullString
	Limit                 int32
}

type ListReceivingOrdersForwardRow struct {
	ID                   string
	Number               string
	CompletedAt          sql.NullTime
	CreatedAt            time.Time
	UpdatedAt            time.Time
	PurchaseOrderID      string
	PurchaseOrderNumber  string
	SupplierID           sql.NullString
	SupplierName         sql.NullString
	SupplierNumber       sql.NullString
	LineCount            int64
	CompletionPercentage interface{}
}

func (q *Queries) ListReceivingOrdersForward(ctx context.Context, arg ListReceivingOrdersForwardParams) ([]ListReceivingOrdersForwardRow, error) {
	query := listReceivingOrdersForward
	var queryParams []interface{}
	queryParams = append(queryParams, arg.AccountID)
	queryParams = append(queryParams, arg.SearchQuery)
	queryParams = append(queryParams, arg.SearchQuery)
	queryParams = append(queryParams, arg.SearchQuery)
	queryParams = append(queryParams, arg.Status)
	queryParams = append(queryParams, arg.Status)
	queryParams = append(queryParams, arg.Status)
	queryParams = append(queryParams, arg.IncludeItemFilter)
	if len(arg.ItemIds) > 0 {
		for _, v := range arg.ItemIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:item_ids*/?", strings.Repeat(",?", len(arg.ItemIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:item_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.IncludeSupplierFilter)
	if len(arg.SupplierIds) > 0 {
		for _, v := range arg.SupplierIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:supplier_ids*/?", strings.Repeat(",?", len(arg.SupplierIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:supplier_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.StartDate)
	queryParams = append(queryParams, arg.StartDate)
	queryParams = append(queryParams, arg.EndDate)
	queryParams = append(queryParams, arg.EndDate)
	queryParams = append(queryParams, arg.CursorCreatedAt)
	queryParams = append(queryParams, arg.CursorCreatedAt)
	queryParams = append(queryParams, arg.CursorCreatedAt)
	queryParams = append(queryParams, arg.CursorID)
	queryParams = append(queryParams, arg.Limit)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReceivingOrdersForwardRow
	for rows.Next() {
		var i ListReceivingOrdersForwardRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PurchaseOrderID,
			&i.PurchaseOrderNumber,
			&i.SupplierID,
			&i.SupplierName,
			&i.SupplierNumber,
			&i.LineCount,
			&i.CompletionPercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPurchaseOrderFulfilled = `-- name: MarkPurchaseOrderFulfilled :exec
UPDATE sales_order
SET sales_order_status_code = 'fulfilled',
    completed_at = NOW(3),
    updated_at = NOW(3)
WHERE id = ?
AND buyer_account_id = ?
AND sales_order_type_code = 'purchase_order'
`

type MarkPurchaseOrderFulfilledParams struct {
	ID        string
	AccountID string
}

func (q *Queries) MarkPurchaseOrderFulfilled(ctx context.Context, arg MarkPurchaseOrderFulfilledParams) error {
	_, err := q.db.ExecContext(ctx, markPurchaseOrderFulfilled, arg.ID, arg.AccountID)
	return err
}

const markReceivingOrderComplete = `-- name: MarkReceivingOrderComplete :exec
UPDATE receiving_order SET
    completed_at = NOW(3),
    updated_at = NOW(3)
WHERE order_id = ?
`

func (q *Queries) MarkReceivingOrderComplete(ctx context.Context, orderID string) error {
	_, err := q.db.ExecContext(ctx, markReceivingOrderComplete, orderID)
	return err
}

const markReceivingOrderCompleteByID = `-- name: MarkReceivingOrderCompleteByID :exec
UPDATE receiving_order
SET completed_at = NOW(3)
WHERE id = ?
AND account_id = ?
`

type MarkReceivingOrderCompleteByIDParams struct {
	ID        string
	AccountID string
}

func (q *Queries) MarkReceivingOrderCompleteByID(ctx context.Context, arg MarkReceivingOrderCompleteByIDParams) error {
	_, err := q.db.ExecContext(ctx, markReceivingOrderCompleteByID, arg.ID, arg.AccountID)
	return err
}

const markReceivingOrderIncomplete = `-- name: MarkReceivingOrderIncomplete :exec
UPDATE receiving_order SET
    completed_at = NULL,
    updated_at = NOW(3)
WHERE order_id = ?
`

func (q *Queries) MarkReceivingOrderIncomplete(ctx context.Context, orderID string) error {
	_, err := q.db.ExecContext(ctx, markReceivingOrderIncomplete, orderID)
	return err
}

const markReceivingOrderIncompleteByID = `-- name: MarkReceivingOrderIncompleteByID :exec
UPDATE receiving_order
SET completed_at = NULL
WHERE id = ?
AND account_id = ?
`

type MarkReceivingOrderIncompleteByIDParams struct {
	ID        string
	AccountID string
}

func (q *Queries) MarkReceivingOrderIncompleteByID(ctx context.Context, arg MarkReceivingOrderIncompleteByIDParams) error {
	_, err := q.db.ExecContext(ctx, markReceivingOrderIncompleteByID, arg.ID, arg.AccountID)
	return err
}

const stockReceivingOrderLines = `-- name: StockReceivingOrderLines :exec
UPDATE receiving_order_line
SET stocked_at = NOW(3)
WHERE id IN (/*SLICE:line_ids*/?)
`

func (q *Queries) StockReceivingOrderLines(ctx context.Context, lineIds []string) error {
	query := stockReceivingOrderLines
	var queryParams []interface{}
	if len(lineIds) > 0 {
		for _, v := range lineIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:line_ids*/?", strings.Repeat(",?", len(lineIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:line_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const updateReceivingOrderLineQuantity = `-- name: UpdateReceivingOrderLineQuantity :exec
UPDATE quantity q
JOIN receiving_order_line rol ON q.id = rol.quantity_id
SET q.value = ?
WHERE rol.id = ?
`

type UpdateReceivingOrderLineQuantityParams struct {
	QuantityValue string
	LineID        string
}

func (q *Queries) UpdateReceivingOrderLineQuantity(ctx context.Context, arg UpdateReceivingOrderLineQuantityParams) error {
	_, err := q.db.ExecContext(ctx, updateReceivingOrderLineQuantity, arg.QuantityValue, arg.LineID)
	return err
}

const upsertLot = `-- name: UpsertLot :exec
INSERT IGNORE INTO lot (id, account_id, item_id, lot_number, created_at, updated_at)
VALUES (?, ?, ?, ?, NOW(3), NOW(3))
`

type UpsertLotParams struct {
	ID        string
	AccountID string
	ItemID    string
	LotNumber string
}

func (q *Queries) UpsertLot(ctx context.Context, arg UpsertLotParams) error {
	_, err := q.db.ExecContext(ctx, upsertLot,
		arg.ID,
		arg.AccountID,
		arg.ItemID,
		arg.LotNumber,
	)
	return err
}

const voidAllReceivingOrderLines = `-- name: VoidAllReceivingOrderLines :exec
UPDATE receiving_order_line rol
JOIN quantity q ON rol.quantity_id = q.id
JOIN receiving_order ro ON rol.receiving_order_id = ro.id
SET q.value = '0', rol.stocked_at = NULL
WHERE rol.receiving_order_id = ?
AND ro.account_id = ?
AND ro.completed_at IS NULL
`

type VoidAllReceivingOrderLinesParams struct {
	ReceivingOrderID string
	AccountID        string
}

func (q *Queries) VoidAllReceivingOrderLines(ctx context.Context, arg VoidAllReceivingOrderLinesParams) error {
	_, err := q.db.ExecContext(ctx, voidAllReceivingOrderLines, arg.ReceivingOrderID, arg.AccountID)
	return err
}

const voidReceivingOrderLine = `-- name: VoidReceivingOrderLine :exec
UPDATE receiving_order_line rol
JOIN quantity q ON rol.quantity_id = q.id
JOIN receiving_order ro ON rol.receiving_order_id = ro.id
SET q.value = '0', rol.stocked_at = NULL
WHERE rol.id = ?
AND ro.account_id = ?
`

type VoidReceivingOrderLineParams struct {
	LineID    string
	AccountID string
}

func (q *Queries) VoidReceivingOrderLine(ctx context.Context, arg VoidReceivingOrderLineParams) error {
	_, err := q.db.ExecContext(ctx, voidReceivingOrderLine, arg.LineID, arg.AccountID)
	return err
}
