// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sales_target.sql

package sqlc

import (
	"context"
	"time"
)

const countSalesTargets = `-- name: CountSalesTargets :one
SELECT COUNT(*) AS cnt
FROM target t
INNER JOIN quantity q ON q.id = t.amount_id
WHERE t.sales_rep_id = ? AND t.account_id = ?
AND (
    ? IS NULL
    OR t.id LIKE CONCAT('%', ?, '%')
    OR q.value LIKE CONCAT('%', ?, '%')
)
`

type CountSalesTargetsParams struct {
	SalesRepID string
	AccountID  string
	Search     interface{}
}

func (q *Queries) CountSalesTargets(ctx context.Context, arg CountSalesTargetsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSalesTargets,
		arg.SalesRepID,
		arg.AccountID,
		arg.Search,
		arg.Search,
		arg.Search,
	)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const getSalesTarget = `-- name: GetSalesTarget :one
SELECT t.id, t.start_date, t.end_date, t.sales_rep_id, t.account_id,
       t.amount_id, t.created_at, t.updated_at,
       q.value AS amount_value, q.unit_id AS amount_unit_id
FROM target t
INNER JOIN quantity q ON q.id = t.amount_id
WHERE t.id = ?
`

type GetSalesTargetRow struct {
	ID           string
	StartDate    time.Time
	EndDate      time.Time
	SalesRepID   string
	AccountID    string
	AmountID     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	AmountValue  string
	AmountUnitID string
}

func (q *Queries) GetSalesTarget(ctx context.Context, id string) (GetSalesTargetRow, error) {
	row := q.db.QueryRowContext(ctx, getSalesTarget, id)
	var i GetSalesTargetRow
	err := row.Scan(
		&i.ID,
		&i.StartDate,
		&i.EndDate,
		&i.SalesRepID,
		&i.AccountID,
		&i.AmountID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AmountValue,
		&i.AmountUnitID,
	)
	return i, err
}

const insertSalesTarget = `-- name: InsertSalesTarget :exec
INSERT INTO target (id, start_date, end_date, sales_rep_id, account_id, amount_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, NOW(3), NOW(3))
`

type InsertSalesTargetParams struct {
	ID         string
	StartDate  time.Time
	EndDate    time.Time
	SalesRepID string
	AccountID  string
	AmountID   string
}

func (q *Queries) InsertSalesTarget(ctx context.Context, arg InsertSalesTargetParams) error {
	_, err := q.db.ExecContext(ctx, insertSalesTarget,
		arg.ID,
		arg.StartDate,
		arg.EndDate,
		arg.SalesRepID,
		arg.AccountID,
		arg.AmountID,
	)
	return err
}

const listSalesTargets = `-- name: ListSalesTargets :many
SELECT t.id, t.start_date, t.end_date, t.sales_rep_id, t.account_id,
       t.amount_id, t.created_at, t.updated_at,
       q.value AS amount_value, q.unit_id AS amount_unit_id
FROM target t
INNER JOIN quantity q ON q.id = t.amount_id
WHERE t.sales_rep_id = ? AND t.account_id = ?
AND (
    ? IS NULL
    OR t.id LIKE CONCAT('%', ?, '%')
    OR q.value LIKE CONCAT('%', ?, '%')
)
ORDER BY t.start_date DESC
LIMIT ? OFFSET ?
`

type ListSalesTargetsParams struct {
	SalesRepID string
	AccountID  string
	Search     interface{}
	Limit      int32
	Offset     int32
}

type ListSalesTargetsRow struct {
	ID           string
	StartDate    time.Time
	EndDate      time.Time
	SalesRepID   string
	AccountID    string
	AmountID     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	AmountValue  string
	AmountUnitID string
}

func (q *Queries) ListSalesTargets(ctx context.Context, arg ListSalesTargetsParams) ([]ListSalesTargetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSalesTargets,
		arg.SalesRepID,
		arg.AccountID,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSalesTargetsRow
	for rows.Next() {
		var i ListSalesTargetsRow
		if err := rows.Scan(
			&i.ID,
			&i.StartDate,
			&i.EndDate,
			&i.SalesRepID,
			&i.AccountID,
			&i.AmountID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AmountValue,
			&i.AmountUnitID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesRepExistsInAccount = `-- name: SalesRepExistsInAccount :one
SELECT EXISTS(
    SELECT 1 FROM account_user
    WHERE id = ? AND account_id = ?
        AND (status_code = 'active' OR status_code IS NULL)
) AS does_exist
`

type SalesRepExistsInAccountParams struct {
	ID        string
	AccountID string
}

func (q *Queries) SalesRepExistsInAccount(ctx context.Context, arg SalesRepExistsInAccountParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, salesRepExistsInAccount, arg.ID, arg.AccountID)
	var does_exist bool
	err := row.Scan(&does_exist)
	return does_exist, err
}

const salesTargetExists = `-- name: SalesTargetExists :one
SELECT EXISTS(SELECT 1 FROM target WHERE id = ?) AS does_exist
`

func (q *Queries) SalesTargetExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, salesTargetExists, id)
	var does_exist bool
	err := row.Scan(&does_exist)
	return does_exist, err
}

const salesTargetIsInAccount = `-- name: SalesTargetIsInAccount :one
SELECT EXISTS(SELECT 1 FROM target WHERE id = ? AND account_id = ?) AS is_in_account
`

type SalesTargetIsInAccountParams struct {
	ID        string
	AccountID string
}

func (q *Queries) SalesTargetIsInAccount(ctx context.Context, arg SalesTargetIsInAccountParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, salesTargetIsInAccount, arg.ID, arg.AccountID)
	var is_in_account bool
	err := row.Scan(&is_in_account)
	return is_in_account, err
}

const updateSalesTarget = `-- name: UpdateSalesTarget :exec
UPDATE target SET
    start_date = ?,
    end_date = ?,
    updated_at = NOW(3)
WHERE id = ?
`

type UpdateSalesTargetParams struct {
	StartDate time.Time
	EndDate   time.Time
	ID        string
}

func (q *Queries) UpdateSalesTarget(ctx context.Context, arg UpdateSalesTargetParams) error {
	_, err := q.db.ExecContext(ctx, updateSalesTarget, arg.StartDate, arg.EndDate, arg.ID)
	return err
}
