// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedule_attainment.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const countDeviationsForBaselines = `-- name: CountDeviationsForBaselines :many
SELECT
    d.production_schedule_id,
    COUNT(*) AS deviation_count,
    SUM(CASE WHEN d.deviation_type_code = 'line_added' THEN 1 ELSE 0 END) AS added_count,
    COALESCE(SUM(ABS(d.delta_quantity)), 0) AS abs_delta_quantity
FROM production_schedule_deviation d
WHERE d.account_id = ?
AND d.production_schedule_id IN (/*SLICE:schedule_ids*/?)
AND d.is_frozen_week = true
GROUP BY d.production_schedule_id
`

type CountDeviationsForBaselinesParams struct {
	AccountID   string
	ScheduleIds []string
}

type CountDeviationsForBaselinesRow struct {
	ProductionScheduleID string
	DeviationCount       int64
	AddedCount           interface{}
	AbsDeltaQuantity     interface{}
}

// CountDeviationsForBaselines counts frozen-week changes per baseline version, which is the numerator of frozen adherence.
func (q *Queries) CountDeviationsForBaselines(ctx context.Context, arg CountDeviationsForBaselinesParams) ([]CountDeviationsForBaselinesRow, error) {
	query := countDeviationsForBaselines
	var queryParams []interface{}
	queryParams = append(queryParams, arg.AccountID)
	if len(arg.ScheduleIds) > 0 {
		for _, v := range arg.ScheduleIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:schedule_ids*/?", strings.Repeat(",?", len(arg.ScheduleIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:schedule_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountDeviationsForBaselinesRow
	for rows.Next() {
		var i CountDeviationsForBaselinesRow
		if err := rows.Scan(
			&i.ProductionScheduleID,
			&i.DeviationCount,
			&i.AddedCount,
			&i.AbsDeltaQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectAttainmentBaselines = `-- name: SelectAttainmentBaselines :many

SELECT
    s.id AS schedule_id,
    s.version,
    s.horizon_start_date,
    s.horizon_end_date,
    s.published_at,
    s.frozen_through_date,
    s.frozen_line_count,
    s.frozen_planned_quantity
FROM production_schedule s
WHERE s.account_id = ?
AND s.status_code IN ('published', 'superseded', 'archived')
AND s.published_at IS NOT NULL
AND s.horizon_start_date <= ?
AND s.horizon_end_date >= ?
ORDER BY s.published_at DESC, s.id DESC
`

type SelectAttainmentBaselinesParams struct {
	AccountID   string
	WindowEnd   time.Time
	WindowStart time.Time
}

type SelectAttainmentBaselinesRow struct {
	ScheduleID            string
	Version               int32
	HorizonStartDate      time.Time
	HorizonEndDate        time.Time
	PublishedAt           sql.NullTime
	FrozenThroughDate     sql.NullTime
	FrozenLineCount       int32
	FrozenPlannedQuantity string
}

// Schedule attainment: what was planned versus what the floor actually built.
//
// Every query here is scoped by the *baseline* schedule chosen per week, never by "the current schedule". Measuring against whatever happens to be live now would let a republish rewrite last month's performance.
// SelectAttainmentBaselines returns every published version whose horizon overlaps the window; baselineFor (in Go) then picks the one that governed each week.
//
// The per-week choice is the version that froze the week — the plan committed for it — so a version published after the week ended cannot rewrite history, while a plan published on the week's own start day still counts as the plan it froze. frozen_through_date is selected for exactly that test.
func (q *Queries) SelectAttainmentBaselines(ctx context.Context, arg SelectAttainmentBaselinesParams) ([]SelectAttainmentBaselinesRow, error) {
	rows, err := q.db.QueryContext(ctx, selectAttainmentBaselines, arg.AccountID, arg.WindowEnd, arg.WindowStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectAttainmentBaselinesRow
	for rows.Next() {
		var i SelectAttainmentBaselinesRow
		if err := rows.Scan(
			&i.ScheduleID,
			&i.Version,
			&i.HorizonStartDate,
			&i.HorizonEndDate,
			&i.PublishedAt,
			&i.FrozenThroughDate,
			&i.FrozenLineCount,
			&i.FrozenPlannedQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumActualsByWeek = `-- name: SumActualsByWeek :many
SELECT
    DATE(DATE_SUB(b.scanned_at, INTERVAL ((DAYOFWEEK(b.scanned_at) + 6 - CAST(? AS SIGNED)) % 7) DAY)) AS week_start_date,
    bm.B AS machine_id,
    b.item_id,
    m.department_id,
    COALESCE(SUM(bq.value), 0) AS actual_quantity,
    COALESCE(SUM(wq.value), 0) AS waste_quantity,
    COUNT(*) AS batch_count
FROM batch b
JOIN quantity bq ON bq.id = b.quantity_id
LEFT JOIN quantity wq ON wq.id = b.waste_quantity_id
LEFT JOIN _batches_machines bm ON bm.A = b.id
LEFT JOIN machine m ON m.id = bm.B
WHERE b.account_id = ?
AND b.scanned_at >= ?
AND b.scanned_at < ?
GROUP BY week_start_date, bm.B, b.item_id, m.department_id
`

type SumActualsByWeekParams struct {
	WeekStartDay int64
	AccountID    string
	WindowStart  sql.NullTime
	WindowEnd    sql.NullTime
}

type SumActualsByWeekRow struct {
	WeekStartDate  time.Time
	MachineID      sql.NullString
	ItemID         string
	DepartmentID   sql.NullString
	ActualQuantity interface{}
	WasteQuantity  interface{}
	BatchCount     int64
}

// SumActualsByWeek returns what was actually produced, bucketed to the start of the scan's production week so it lines up with a schedule line's week_start_date.
//
// The week start follows the account's configured week_start_day (0 = Sunday through 6 = Saturday), the same day schedule horizons are built on. A fixed Monday here would split one schedule week's scans across two buckets for any plant whose week does not start on Monday, and its planned quantity would then be judged against a fraction of its own output.
//
// Department comes from the batch's machine (machine.department_id), the same source writeSolvedPlan populates a plan line's department from, so actuals and plan bucket into identical departments. It is deliberately NOT the scanning station AnalyzeOee uses, and deliberately not production_step.department_id: that column is nullable and unset in practice, which left every actual department blank and broke the department roll-up. The machine's department is NOT NULL and is exactly what the plan was expressed in.
func (q *Queries) SumActualsByWeek(ctx context.Context, arg SumActualsByWeekParams) ([]SumActualsByWeekRow, error) {
	rows, err := q.db.QueryContext(ctx, sumActualsByWeek,
		arg.WeekStartDay,
		arg.AccountID,
		arg.WindowStart,
		arg.WindowEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumActualsByWeekRow
	for rows.Next() {
		var i SumActualsByWeekRow
		if err := rows.Scan(
			&i.WeekStartDate,
			&i.MachineID,
			&i.ItemID,
			&i.DepartmentID,
			&i.ActualQuantity,
			&i.WasteQuantity,
			&i.BatchCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumPlannedByWeek = `-- name: SumPlannedByWeek :many
SELECT
    l.week_start_date,
    l.machine_id,
    l.item_id,
    l.department_id,
    SUM(l.planned_quantity) AS planned_quantity,
    SUM(l.planned_run_hours) AS planned_run_hours,
    COUNT(*) AS line_count
FROM production_schedule_line l
WHERE l.account_id = ?
AND l.production_schedule_id = ?
AND l.week_start_date >= ?
AND l.week_start_date <= ?
AND l.status_code != 'cancelled'
GROUP BY l.week_start_date, l.machine_id, l.item_id, l.department_id
`

type SumPlannedByWeekParams struct {
	AccountID            string
	ProductionScheduleID string
	WindowStart          time.Time
	WindowEnd            time.Time
}

type SumPlannedByWeekRow struct {
	WeekStartDate   time.Time
	MachineID       string
	ItemID          string
	DepartmentID    sql.NullString
	PlannedQuantity interface{}
	PlannedRunHours interface{}
	LineCount       int64
}

// SumPlannedByWeek returns planned quantity and run hours per (week, machine, item) for one baseline version.
func (q *Queries) SumPlannedByWeek(ctx context.Context, arg SumPlannedByWeekParams) ([]SumPlannedByWeekRow, error) {
	rows, err := q.db.QueryContext(ctx, sumPlannedByWeek,
		arg.AccountID,
		arg.ProductionScheduleID,
		arg.WindowStart,
		arg.WindowEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumPlannedByWeekRow
	for rows.Next() {
		var i SumPlannedByWeekRow
		if err := rows.Scan(
			&i.WeekStartDate,
			&i.MachineID,
			&i.ItemID,
			&i.DepartmentID,
			&i.PlannedQuantity,
			&i.PlannedRunHours,
			&i.LineCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumScheduledHoursByDepartmentWeek = `-- name: SumScheduledHoursByDepartmentWeek :many
SELECT
    l.week_start_date,
    l.department_id,
    CAST(COALESCE(SUM(l.planned_run_hours), 0) AS DECIMAL(65,30)) AS planned_run_hours,
    CAST(COALESCE(SUM(l.planned_changeover_minutes), 0) AS DECIMAL(65,30)) AS planned_changeover_minutes
FROM production_schedule_line l
WHERE l.account_id = ?
AND l.production_schedule_id = ?
AND l.week_start_date >= ?
AND l.week_start_date <= ?
AND l.status_code != 'cancelled'
AND l.department_id IS NOT NULL
AND l.department_id != ''
GROUP BY l.week_start_date, l.department_id
`

type SumScheduledHoursByDepartmentWeekParams struct {
	AccountID            string
	ProductionScheduleID string
	WindowStart          time.Time
	WindowEnd            time.Time
}

type SumScheduledHoursByDepartmentWeekRow struct {
	WeekStartDate            time.Time
	DepartmentID             sql.NullString
	PlannedRunHours          string
	PlannedChangeoverMinutes string
}

// SumScheduledHoursByDepartmentWeek returns the scheduled machine time per department per week for one baseline version. It is the denominator OEE availability is measured against: the hours the plant actually put on the schedule, not a shift pattern multiplied out over the whole window.
//
// planned_run_hours is a campaign's run time and planned_changeover_minutes the setup between campaigns; both are time a machine was scheduled to be working, so both belong in Planned Production Time, and logged downtime — changeover included — is charged against that total. Cancelled lines are excluded, matching SumPlannedByWeek: a line nobody will run was never scheduled time. Lines with no department are dropped rather than pooled into one bucket, because OEE has no availability for an unassigned department.
func (q *Queries) SumScheduledHoursByDepartmentWeek(ctx context.Context, arg SumScheduledHoursByDepartmentWeekParams) ([]SumScheduledHoursByDepartmentWeekRow, error) {
	rows, err := q.db.QueryContext(ctx, sumScheduledHoursByDepartmentWeek,
		arg.AccountID,
		arg.ProductionScheduleID,
		arg.WindowStart,
		arg.WindowEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumScheduledHoursByDepartmentWeekRow
	for rows.Next() {
		var i SumScheduledHoursByDepartmentWeekRow
		if err := rows.Scan(
			&i.WeekStartDate,
			&i.DepartmentID,
			&i.PlannedRunHours,
			&i.PlannedChangeoverMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
