// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: supplier_material.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createSupplierMaterial = `-- name: CreateSupplierMaterial :exec
INSERT INTO supplier_material (
    id, material_id, supplier_account_id, supplier_part_number, supplier_description,
    is_active, owner_account_id, created_at, updated_at
) VALUES (
    ?, ?, ?,
    ?, ?,
    ?, ?, NOW(3), NOW(3)
)
`

type CreateSupplierMaterialParams struct {
	ID                  string
	MaterialID          string
	SupplierAccountID   string
	SupplierPartNumber  string
	SupplierDescription sql.NullString
	IsActive            bool
	OwnerAccountID      string
}

func (q *Queries) CreateSupplierMaterial(ctx context.Context, arg CreateSupplierMaterialParams) error {
	_, err := q.db.ExecContext(ctx, createSupplierMaterial,
		arg.ID,
		arg.MaterialID,
		arg.SupplierAccountID,
		arg.SupplierPartNumber,
		arg.SupplierDescription,
		arg.IsActive,
		arg.OwnerAccountID,
	)
	return err
}

const deleteSupplierMaterial = `-- name: DeleteSupplierMaterial :execresult
DELETE FROM supplier_material
WHERE id = ?
  AND owner_account_id = ?
`

type DeleteSupplierMaterialParams struct {
	ID             string
	OwnerAccountID string
}

func (q *Queries) DeleteSupplierMaterial(ctx context.Context, arg DeleteSupplierMaterialParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteSupplierMaterial, arg.ID, arg.OwnerAccountID)
}

const existsSupplierMaterialByMaterialAndSupplier = `-- name: ExistsSupplierMaterialByMaterialAndSupplier :one
SELECT COUNT(*) AS total
FROM supplier_material
WHERE material_id = ?
  AND supplier_account_id = ?
  AND owner_account_id = ?
`

type ExistsSupplierMaterialByMaterialAndSupplierParams struct {
	MaterialID        string
	SupplierAccountID string
	OwnerAccountID    string
}

func (q *Queries) ExistsSupplierMaterialByMaterialAndSupplier(ctx context.Context, arg ExistsSupplierMaterialByMaterialAndSupplierParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, existsSupplierMaterialByMaterialAndSupplier, arg.MaterialID, arg.SupplierAccountID, arg.OwnerAccountID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getItemIDByMaterialID = `-- name: GetItemIDByMaterialID :one
SELECT m.item_id
FROM material m
WHERE m.id = ?
`

func (q *Queries) GetItemIDByMaterialID(ctx context.Context, materialID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getItemIDByMaterialID, materialID)
	var item_id string
	err := row.Scan(&item_id)
	return item_id, err
}

const getMaterialIDByItemID = `-- name: GetMaterialIDByItemID :one
SELECT m.id
FROM material m
JOIN item i ON i.id = m.item_id
WHERE m.item_id = ?
  AND i.account_id = ?
  AND i.deleted_at IS NULL
`

type GetMaterialIDByItemIDParams struct {
	ItemID    string
	AccountID string
}

func (q *Queries) GetMaterialIDByItemID(ctx context.Context, arg GetMaterialIDByItemIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getMaterialIDByItemID, arg.ItemID, arg.AccountID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getSupplierMaterialBySupplierAndMaterialID = `-- name: GetSupplierMaterialBySupplierAndMaterialID :one
SELECT
    sm.id,
    sm.material_id,
    sm.supplier_account_id,
    sm.supplier_part_number,
    sm.supplier_description,
    sm.is_active,
    sm.owner_account_id,
    sm.created_at,
    sm.updated_at,
    m.id AS material_type_id,
    m.item_id,
    m.order_point_id,
    m.lead_time_id,
    m.created_at AS material_created_at,
    m.updated_at AS material_updated_at,
    i.sku,
    i.description AS item_description,
    i.notes AS item_notes,
    i.item_type_code,
    i.item_category_id,
    i.unit_value_id,
    i.unit_cost_id,
    i.burn_rate_id,
    i.account_id AS item_account_id,
    i.is_dirty,
    i.created_at AS item_created_at,
    i.updated_at AS item_updated_at,
    ic.name AS category_name,
    ic.item_category_type_code,
    ic.unit_group_id AS category_unit_group_id,
    op.value AS order_point_value,
    op.unit_id AS order_point_unit_id,
    op_u.abbreviation AS order_point_unit_abbreviation,
    op_u.unit_dimension_code AS order_point_unit_type,
    lt.value AS lead_time_value,
    lt.unit_id AS lead_time_unit_id,
    lt_u.abbreviation AS lead_time_unit_abbreviation,
    lt_u.unit_dimension_code AS lead_time_unit_type,
    rv.id AS unit_value_rate_id,
    rv.value AS unit_value_rate_value,
    rv.numerator_unit_id AS unit_value_numerator_unit_id,
    rv.denominator_unit_id AS unit_value_denominator_unit_id,
    rv.created_at AS unit_value_created_at,
    rv.updated_at AS unit_value_updated_at,
    rc.id AS unit_cost_rate_id,
    rc.value AS unit_cost_rate_value,
    rc.numerator_unit_id AS unit_cost_numerator_unit_id,
    rc.denominator_unit_id AS unit_cost_denominator_unit_id,
    rc.created_at AS unit_cost_created_at,
    rc.updated_at AS unit_cost_updated_at,
    rb.id AS burn_rate_id_joined,
    rb.value AS burn_rate_value,
    rb.numerator_unit_id AS burn_rate_numerator_unit_id,
    rb.denominator_unit_id AS burn_rate_denominator_unit_id,
    rb.created_at AS burn_rate_created_at,
    rb.updated_at AS burn_rate_updated_at
FROM supplier_material sm
JOIN material m ON m.id = sm.material_id
JOIN item i ON i.id = m.item_id
JOIN item_category ic ON ic.id = i.item_category_id
LEFT JOIN quantity op ON op.id = m.order_point_id
LEFT JOIN unit op_u ON op_u.id = op.unit_id
LEFT JOIN quantity lt ON lt.id = m.lead_time_id
LEFT JOIN unit lt_u ON lt_u.id = lt.unit_id
JOIN rate rv ON rv.id = i.unit_value_id
JOIN rate rc ON rc.id = i.unit_cost_id
JOIN rate rb ON rb.id = i.burn_rate_id
WHERE sm.supplier_account_id = ?
  AND sm.material_id = ?
  AND sm.owner_account_id = ?
  AND i.deleted_at IS NULL
`

type GetSupplierMaterialBySupplierAndMaterialIDParams struct {
	SupplierAccountID string
	MaterialID        string
	OwnerAccountID    string
}

type GetSupplierMaterialBySupplierAndMaterialIDRow struct {
	ID                         string
	MaterialID                 string
	SupplierAccountID          string
	SupplierPartNumber         string
	SupplierDescription        sql.NullString
	IsActive                   bool
	OwnerAccountID             string
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	MaterialTypeID             string
	ItemID                     string
	OrderPointID               string
	LeadTimeID                 string
	MaterialCreatedAt          time.Time
	MaterialUpdatedAt          time.Time
	Sku                        string
	ItemDescription            sql.NullString
	ItemNotes                  sql.NullString
	ItemTypeCode               string
	ItemCategoryID             string
	UnitValueID                string
	UnitCostID                 string
	BurnRateID                 string
	ItemAccountID              string
	IsDirty                    bool
	ItemCreatedAt              time.Time
	ItemUpdatedAt              time.Time
	CategoryName               string
	ItemCategoryTypeCode       string
	CategoryUnitGroupID        string
	OrderPointValue            sql.NullString
	OrderPointUnitID           sql.NullString
	OrderPointUnitAbbreviation sql.NullString
	OrderPointUnitType         sql.NullString
	LeadTimeValue              sql.NullString
	LeadTimeUnitID             sql.NullString
	LeadTimeUnitAbbreviation   sql.NullString
	LeadTimeUnitType           sql.NullString
	UnitValueRateID            string
	UnitValueRateValue         string
	UnitValueNumeratorUnitID   string
	UnitValueDenominatorUnitID string
	UnitValueCreatedAt         time.Time
	UnitValueUpdatedAt         time.Time
	UnitCostRateID             string
	UnitCostRateValue          string
	UnitCostNumeratorUnitID    string
	UnitCostDenominatorUnitID  string
	UnitCostCreatedAt          time.Time
	UnitCostUpdatedAt          time.Time
	BurnRateIDJoined           string
	BurnRateValue              string
	BurnRateNumeratorUnitID    string
	BurnRateDenominatorUnitID  string
	BurnRateCreatedAt          time.Time
	BurnRateUpdatedAt          time.Time
}

func (q *Queries) GetSupplierMaterialBySupplierAndMaterialID(ctx context.Context, arg GetSupplierMaterialBySupplierAndMaterialIDParams) (GetSupplierMaterialBySupplierAndMaterialIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSupplierMaterialBySupplierAndMaterialID, arg.SupplierAccountID, arg.MaterialID, arg.OwnerAccountID)
	var i GetSupplierMaterialBySupplierAndMaterialIDRow
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.SupplierAccountID,
		&i.SupplierPartNumber,
		&i.SupplierDescription,
		&i.IsActive,
		&i.OwnerAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaterialTypeID,
		&i.ItemID,
		&i.OrderPointID,
		&i.LeadTimeID,
		&i.MaterialCreatedAt,
		&i.MaterialUpdatedAt,
		&i.Sku,
		&i.ItemDescription,
		&i.ItemNotes,
		&i.ItemTypeCode,
		&i.ItemCategoryID,
		&i.UnitValueID,
		&i.UnitCostID,
		&i.BurnRateID,
		&i.ItemAccountID,
		&i.IsDirty,
		&i.ItemCreatedAt,
		&i.ItemUpdatedAt,
		&i.CategoryName,
		&i.ItemCategoryTypeCode,
		&i.CategoryUnitGroupID,
		&i.OrderPointValue,
		&i.OrderPointUnitID,
		&i.OrderPointUnitAbbreviation,
		&i.OrderPointUnitType,
		&i.LeadTimeValue,
		&i.LeadTimeUnitID,
		&i.LeadTimeUnitAbbreviation,
		&i.LeadTimeUnitType,
		&i.UnitValueRateID,
		&i.UnitValueRateValue,
		&i.UnitValueNumeratorUnitID,
		&i.UnitValueDenominatorUnitID,
		&i.UnitValueCreatedAt,
		&i.UnitValueUpdatedAt,
		&i.UnitCostRateID,
		&i.UnitCostRateValue,
		&i.UnitCostNumeratorUnitID,
		&i.UnitCostDenominatorUnitID,
		&i.UnitCostCreatedAt,
		&i.UnitCostUpdatedAt,
		&i.BurnRateIDJoined,
		&i.BurnRateValue,
		&i.BurnRateNumeratorUnitID,
		&i.BurnRateDenominatorUnitID,
		&i.BurnRateCreatedAt,
		&i.BurnRateUpdatedAt,
	)
	return i, err
}

const listSupplierMaterialsBackward = `-- name: ListSupplierMaterialsBackward :many
SELECT
    sm.id,
    sm.material_id,
    sm.supplier_account_id,
    sm.supplier_part_number,
    sm.supplier_description,
    sm.is_active,
    sm.owner_account_id,
    sm.created_at,
    sm.updated_at,
    m.id AS material_type_id,
    m.item_id,
    m.order_point_id,
    m.lead_time_id,
    m.created_at AS material_created_at,
    m.updated_at AS material_updated_at,
    i.sku,
    i.description AS item_description,
    i.notes AS item_notes,
    i.item_type_code,
    i.item_category_id,
    i.unit_value_id,
    i.unit_cost_id,
    i.burn_rate_id,
    i.account_id AS item_account_id,
    i.is_dirty,
    i.created_at AS item_created_at,
    i.updated_at AS item_updated_at,
    ic.name AS category_name,
    ic.item_category_type_code,
    ic.unit_group_id AS category_unit_group_id,
    op.value AS order_point_value,
    op.unit_id AS order_point_unit_id,
    op_u.abbreviation AS order_point_unit_abbreviation,
    op_u.unit_dimension_code AS order_point_unit_type,
    lt.value AS lead_time_value,
    lt.unit_id AS lead_time_unit_id,
    lt_u.abbreviation AS lead_time_unit_abbreviation,
    lt_u.unit_dimension_code AS lead_time_unit_type,
    rv.id AS unit_value_rate_id,
    rv.value AS unit_value_rate_value,
    rv.numerator_unit_id AS unit_value_numerator_unit_id,
    rv.denominator_unit_id AS unit_value_denominator_unit_id,
    rv.created_at AS unit_value_created_at,
    rv.updated_at AS unit_value_updated_at,
    rc.id AS unit_cost_rate_id,
    rc.value AS unit_cost_rate_value,
    rc.numerator_unit_id AS unit_cost_numerator_unit_id,
    rc.denominator_unit_id AS unit_cost_denominator_unit_id,
    rc.created_at AS unit_cost_created_at,
    rc.updated_at AS unit_cost_updated_at,
    rb.id AS burn_rate_id_joined,
    rb.value AS burn_rate_value,
    rb.numerator_unit_id AS burn_rate_numerator_unit_id,
    rb.denominator_unit_id AS burn_rate_denominator_unit_id,
    rb.created_at AS burn_rate_created_at,
    rb.updated_at AS burn_rate_updated_at
FROM supplier_material sm
JOIN material m ON m.id = sm.material_id
JOIN item i ON i.id = m.item_id
JOIN item_category ic ON ic.id = i.item_category_id
LEFT JOIN quantity op ON op.id = m.order_point_id
LEFT JOIN unit op_u ON op_u.id = op.unit_id
LEFT JOIN quantity lt ON lt.id = m.lead_time_id
LEFT JOIN unit lt_u ON lt_u.id = lt.unit_id
JOIN rate rv ON rv.id = i.unit_value_id
JOIN rate rc ON rc.id = i.unit_cost_id
JOIN rate rb ON rb.id = i.burn_rate_id
WHERE sm.supplier_account_id = ?
  AND sm.owner_account_id = ?
  AND i.deleted_at IS NULL
  AND (
    ? IS NULL
    OR sm.supplier_part_number LIKE ?
    OR sm.supplier_description LIKE ?
    OR i.sku LIKE ?
    OR i.description LIKE ?
  )
  AND (
    sm.created_at > ?
    OR (sm.created_at = ? AND sm.id > ?)
  )
ORDER BY sm.created_at ASC, sm.id ASC
LIMIT ?
`

type ListSupplierMaterialsBackwardParams struct {
	SupplierAccountID string
	OwnerAccountID    string
	SearchQuery       sql.NullString
	CursorCreatedAt   time.Time
	CursorID          string
	Limit             int32
}

type ListSupplierMaterialsBackwardRow struct {
	ID                         string
	MaterialID                 string
	SupplierAccountID          string
	SupplierPartNumber         string
	SupplierDescription        sql.NullString
	IsActive                   bool
	OwnerAccountID             string
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	MaterialTypeID             string
	ItemID                     string
	OrderPointID               string
	LeadTimeID                 string
	MaterialCreatedAt          time.Time
	MaterialUpdatedAt          time.Time
	Sku                        string
	ItemDescription            sql.NullString
	ItemNotes                  sql.NullString
	ItemTypeCode               string
	ItemCategoryID             string
	UnitValueID                string
	UnitCostID                 string
	BurnRateID                 string
	ItemAccountID              string
	IsDirty                    bool
	ItemCreatedAt              time.Time
	ItemUpdatedAt              time.Time
	CategoryName               string
	ItemCategoryTypeCode       string
	CategoryUnitGroupID        string
	OrderPointValue            sql.NullString
	OrderPointUnitID           sql.NullString
	OrderPointUnitAbbreviation sql.NullString
	OrderPointUnitType         sql.NullString
	LeadTimeValue              sql.NullString
	LeadTimeUnitID             sql.NullString
	LeadTimeUnitAbbreviation   sql.NullString
	LeadTimeUnitType           sql.NullString
	UnitValueRateID            string
	UnitValueRateValue         string
	UnitValueNumeratorUnitID   string
	UnitValueDenominatorUnitID string
	UnitValueCreatedAt         time.Time
	UnitValueUpdatedAt         time.Time
	UnitCostRateID             string
	UnitCostRateValue          string
	UnitCostNumeratorUnitID    string
	UnitCostDenominatorUnitID  string
	UnitCostCreatedAt          time.Time
	UnitCostUpdatedAt          time.Time
	BurnRateIDJoined           string
	BurnRateValue              string
	BurnRateNumeratorUnitID    string
	BurnRateDenominatorUnitID  string
	BurnRateCreatedAt          time.Time
	BurnRateUpdatedAt          time.Time
}

func (q *Queries) ListSupplierMaterialsBackward(ctx context.Context, arg ListSupplierMaterialsBackwardParams) ([]ListSupplierMaterialsBackwardRow, error) {
	rows, err := q.db.QueryContext(ctx, listSupplierMaterialsBackward,
		arg.SupplierAccountID,
		arg.OwnerAccountID,
		arg.SearchQuery,
		arg.SearchQuery,
		arg.SearchQuery,
		arg.SearchQuery,
		arg.SearchQuery,
		arg.CursorCreatedAt,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSupplierMaterialsBackwardRow
	for rows.Next() {
		var i ListSupplierMaterialsBackwardRow
		if err := rows.Scan(
			&i.ID,
			&i.MaterialID,
			&i.SupplierAccountID,
			&i.SupplierPartNumber,
			&i.SupplierDescription,
			&i.IsActive,
			&i.OwnerAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MaterialTypeID,
			&i.ItemID,
			&i.OrderPointID,
			&i.LeadTimeID,
			&i.MaterialCreatedAt,
			&i.MaterialUpdatedAt,
			&i.Sku,
			&i.ItemDescription,
			&i.ItemNotes,
			&i.ItemTypeCode,
			&i.ItemCategoryID,
			&i.UnitValueID,
			&i.UnitCostID,
			&i.BurnRateID,
			&i.ItemAccountID,
			&i.IsDirty,
			&i.ItemCreatedAt,
			&i.ItemUpdatedAt,
			&i.CategoryName,
			&i.ItemCategoryTypeCode,
			&i.CategoryUnitGroupID,
			&i.OrderPointValue,
			&i.OrderPointUnitID,
			&i.OrderPointUnitAbbreviation,
			&i.OrderPointUnitType,
			&i.LeadTimeValue,
			&i.LeadTimeUnitID,
			&i.LeadTimeUnitAbbreviation,
			&i.LeadTimeUnitType,
			&i.UnitValueRateID,
			&i.UnitValueRateValue,
			&i.UnitValueNumeratorUnitID,
			&i.UnitValueDenominatorUnitID,
			&i.UnitValueCreatedAt,
			&i.UnitValueUpdatedAt,
			&i.UnitCostRateID,
			&i.UnitCostRateValue,
			&i.UnitCostNumeratorUnitID,
			&i.UnitCostDenominatorUnitID,
			&i.UnitCostCreatedAt,
			&i.UnitCostUpdatedAt,
			&i.BurnRateIDJoined,
			&i.BurnRateValue,
			&i.BurnRateNumeratorUnitID,
			&i.BurnRateDenominatorUnitID,
			&i.BurnRateCreatedAt,
			&i.BurnRateUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierMaterialsForward = `-- name: ListSupplierMaterialsForward :many
SELECT
    sm.id,
    sm.material_id,
    sm.supplier_account_id,
    sm.supplier_part_number,
    sm.supplier_description,
    sm.is_active,
    sm.owner_account_id,
    sm.created_at,
    sm.updated_at,
    m.id AS material_type_id,
    m.item_id,
    m.order_point_id,
    m.lead_time_id,
    m.created_at AS material_created_at,
    m.updated_at AS material_updated_at,
    i.sku,
    i.description AS item_description,
    i.notes AS item_notes,
    i.item_type_code,
    i.item_category_id,
    i.unit_value_id,
    i.unit_cost_id,
    i.burn_rate_id,
    i.account_id AS item_account_id,
    i.is_dirty,
    i.created_at AS item_created_at,
    i.updated_at AS item_updated_at,
    ic.name AS category_name,
    ic.item_category_type_code,
    ic.unit_group_id AS category_unit_group_id,
    op.value AS order_point_value,
    op.unit_id AS order_point_unit_id,
    op_u.abbreviation AS order_point_unit_abbreviation,
    op_u.unit_dimension_code AS order_point_unit_type,
    lt.value AS lead_time_value,
    lt.unit_id AS lead_time_unit_id,
    lt_u.abbreviation AS lead_time_unit_abbreviation,
    lt_u.unit_dimension_code AS lead_time_unit_type,
    rv.id AS unit_value_rate_id,
    rv.value AS unit_value_rate_value,
    rv.numerator_unit_id AS unit_value_numerator_unit_id,
    rv.denominator_unit_id AS unit_value_denominator_unit_id,
    rv.created_at AS unit_value_created_at,
    rv.updated_at AS unit_value_updated_at,
    rc.id AS unit_cost_rate_id,
    rc.value AS unit_cost_rate_value,
    rc.numerator_unit_id AS unit_cost_numerator_unit_id,
    rc.denominator_unit_id AS unit_cost_denominator_unit_id,
    rc.created_at AS unit_cost_created_at,
    rc.updated_at AS unit_cost_updated_at,
    rb.id AS burn_rate_id_joined,
    rb.value AS burn_rate_value,
    rb.numerator_unit_id AS burn_rate_numerator_unit_id,
    rb.denominator_unit_id AS burn_rate_denominator_unit_id,
    rb.created_at AS burn_rate_created_at,
    rb.updated_at AS burn_rate_updated_at
FROM supplier_material sm
JOIN material m ON m.id = sm.material_id
JOIN item i ON i.id = m.item_id
JOIN item_category ic ON ic.id = i.item_category_id
LEFT JOIN quantity op ON op.id = m.order_point_id
LEFT JOIN unit op_u ON op_u.id = op.unit_id
LEFT JOIN quantity lt ON lt.id = m.lead_time_id
LEFT JOIN unit lt_u ON lt_u.id = lt.unit_id
JOIN rate rv ON rv.id = i.unit_value_id
JOIN rate rc ON rc.id = i.unit_cost_id
JOIN rate rb ON rb.id = i.burn_rate_id
WHERE sm.supplier_account_id = ?
  AND sm.owner_account_id = ?
  AND i.deleted_at IS NULL
  AND (
    ? IS NULL
    OR sm.supplier_part_number LIKE ?
    OR sm.supplier_description LIKE ?
    OR i.sku LIKE ?
    OR i.description LIKE ?
  )
  AND (
    ? IS NULL
    OR sm.created_at < ?
    OR (sm.created_at = ? AND sm.id < ?)
  )
ORDER BY sm.created_at DESC, sm.id DESC
LIMIT ?
`

type ListSupplierMaterialsForwardParams struct {
	SupplierAccountID string
	OwnerAccountID    string
	SearchQuery       sql.NullString
	CursorCreatedAt   sql.NullTime
	CursorID          sql.NullString
	Limit             int32
}

type ListSupplierMaterialsForwardRow struct {
	ID                         string
	MaterialID                 string
	SupplierAccountID          string
	SupplierPartNumber         string
	SupplierDescription        sql.NullString
	IsActive                   bool
	OwnerAccountID             string
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	MaterialTypeID             string
	ItemID                     string
	OrderPointID               string
	LeadTimeID                 string
	MaterialCreatedAt          time.Time
	MaterialUpdatedAt          time.Time
	Sku                        string
	ItemDescription            sql.NullString
	ItemNotes                  sql.NullString
	ItemTypeCode               string
	ItemCategoryID             string
	UnitValueID                string
	UnitCostID                 string
	BurnRateID                 string
	ItemAccountID              string
	IsDirty                    bool
	ItemCreatedAt              time.Time
	ItemUpdatedAt              time.Time
	CategoryName               string
	ItemCategoryTypeCode       string
	CategoryUnitGroupID        string
	OrderPointValue            sql.NullString
	OrderPointUnitID           sql.NullString
	OrderPointUnitAbbreviation sql.NullString
	OrderPointUnitType         sql.NullString
	LeadTimeValue              sql.NullString
	LeadTimeUnitID             sql.NullString
	LeadTimeUnitAbbreviation   sql.NullString
	LeadTimeUnitType           sql.NullString
	UnitValueRateID            string
	UnitValueRateValue         string
	UnitValueNumeratorUnitID   string
	UnitValueDenominatorUnitID string
	UnitValueCreatedAt         time.Time
	UnitValueUpdatedAt         time.Time
	UnitCostRateID             string
	UnitCostRateValue          string
	UnitCostNumeratorUnitID    string
	UnitCostDenominatorUnitID  string
	UnitCostCreatedAt          time.Time
	UnitCostUpdatedAt          time.Time
	BurnRateIDJoined           string
	BurnRateValue              string
	BurnRateNumeratorUnitID    string
	BurnRateDenominatorUnitID  string
	BurnRateCreatedAt          time.Time
	BurnRateUpdatedAt          time.Time
}

func (q *Queries) ListSupplierMaterialsForward(ctx context.Context, arg ListSupplierMaterialsForwardParams) ([]ListSupplierMaterialsForwardRow, error) {
	rows, err := q.db.QueryContext(ctx, listSupplierMaterialsForward,
		arg.SupplierAccountID,
		arg.OwnerAccountID,
		arg.SearchQuery,
		arg.SearchQuery,
		arg.SearchQuery,
		arg.SearchQuery,
		arg.SearchQuery,
		arg.CursorCreatedAt,
		arg.CursorCreatedAt,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSupplierMaterialsForwardRow
	for rows.Next() {
		var i ListSupplierMaterialsForwardRow
		if err := rows.Scan(
			&i.ID,
			&i.MaterialID,
			&i.SupplierAccountID,
			&i.SupplierPartNumber,
			&i.SupplierDescription,
			&i.IsActive,
			&i.OwnerAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MaterialTypeID,
			&i.ItemID,
			&i.OrderPointID,
			&i.LeadTimeID,
			&i.MaterialCreatedAt,
			&i.MaterialUpdatedAt,
			&i.Sku,
			&i.ItemDescription,
			&i.ItemNotes,
			&i.ItemTypeCode,
			&i.ItemCategoryID,
			&i.UnitValueID,
			&i.UnitCostID,
			&i.BurnRateID,
			&i.ItemAccountID,
			&i.IsDirty,
			&i.ItemCreatedAt,
			&i.ItemUpdatedAt,
			&i.CategoryName,
			&i.ItemCategoryTypeCode,
			&i.CategoryUnitGroupID,
			&i.OrderPointValue,
			&i.OrderPointUnitID,
			&i.OrderPointUnitAbbreviation,
			&i.OrderPointUnitType,
			&i.LeadTimeValue,
			&i.LeadTimeUnitID,
			&i.LeadTimeUnitAbbreviation,
			&i.LeadTimeUnitType,
			&i.UnitValueRateID,
			&i.UnitValueRateValue,
			&i.UnitValueNumeratorUnitID,
			&i.UnitValueDenominatorUnitID,
			&i.UnitValueCreatedAt,
			&i.UnitValueUpdatedAt,
			&i.UnitCostRateID,
			&i.UnitCostRateValue,
			&i.UnitCostNumeratorUnitID,
			&i.UnitCostDenominatorUnitID,
			&i.UnitCostCreatedAt,
			&i.UnitCostUpdatedAt,
			&i.BurnRateIDJoined,
			&i.BurnRateValue,
			&i.BurnRateNumeratorUnitID,
			&i.BurnRateDenominatorUnitID,
			&i.BurnRateCreatedAt,
			&i.BurnRateUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSupplierMaterial = `-- name: UpdateSupplierMaterial :execresult
UPDATE supplier_material SET
    supplier_part_number = COALESCE(?, supplier_part_number),
    supplier_description = CASE WHEN ? THEN ? ELSE supplier_description END,
    is_active = COALESCE(?, is_active),
    updated_at = NOW(3)
WHERE id = ?
  AND owner_account_id = ?
`

type UpdateSupplierMaterialParams struct {
	SupplierPartNumber  sql.NullString
	UpdateDescription   sql.NullString
	SupplierDescription sql.NullString
	IsActive            sql.NullBool
	ID                  string
	OwnerAccountID      string
}

func (q *Queries) UpdateSupplierMaterial(ctx context.Context, arg UpdateSupplierMaterialParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateSupplierMaterial,
		arg.SupplierPartNumber,
		arg.UpdateDescription,
		arg.SupplierDescription,
		arg.IsActive,
		arg.ID,
		arg.OwnerAccountID,
	)
}
