// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pricing_plan.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const getPlanByCode = `-- name: GetPlanByCode :one
SELECT id, created_at, type_id, name, plan_type_code, price_per_seat, price_per_month,
       seat_minimum, display_features, display_order, is_highlighted,
       button_text, includes_previous_plan, stripe_pricing_plan_id
FROM account_plan
WHERE plan_type_code = ?
  AND (expires_at IS NULL OR expires_at > NOW(3))
  AND effective_at <= NOW(3)
LIMIT 1
`

type GetPlanByCodeRow struct {
	ID                   int64
	CreatedAt            time.Time
	TypeID               string
	Name                 string
	PlanTypeCode         string
	PricePerSeat         string
	PricePerMonth        sql.NullString
	SeatMinimum          sql.NullInt32
	DisplayFeatures      json.RawMessage
	DisplayOrder         int32
	IsHighlighted        bool
	ButtonText           string
	IncludesPreviousPlan sql.NullString
	StripePricingPlanID  sql.NullString
}

func (q *Queries) GetPlanByCode(ctx context.Context, planTypeCode string) (GetPlanByCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getPlanByCode, planTypeCode)
	var i GetPlanByCodeRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.TypeID,
		&i.Name,
		&i.PlanTypeCode,
		&i.PricePerSeat,
		&i.PricePerMonth,
		&i.SeatMinimum,
		&i.DisplayFeatures,
		&i.DisplayOrder,
		&i.IsHighlighted,
		&i.ButtonText,
		&i.IncludesPreviousPlan,
		&i.StripePricingPlanID,
	)
	return i, err
}

const getPlanByTypeID = `-- name: GetPlanByTypeID :one
SELECT id, created_at, type_id, name, plan_type_code, price_per_seat, price_per_month,
       seat_minimum, display_features, display_order, is_highlighted,
       button_text, includes_previous_plan, stripe_pricing_plan_id
FROM account_plan
WHERE type_id = ?
  AND (expires_at IS NULL OR expires_at > NOW(3))
  AND effective_at <= NOW(3)
LIMIT 1
`

type GetPlanByTypeIDRow struct {
	ID                   int64
	CreatedAt            time.Time
	TypeID               string
	Name                 string
	PlanTypeCode         string
	PricePerSeat         string
	PricePerMonth        sql.NullString
	SeatMinimum          sql.NullInt32
	DisplayFeatures      json.RawMessage
	DisplayOrder         int32
	IsHighlighted        bool
	ButtonText           string
	IncludesPreviousPlan sql.NullString
	StripePricingPlanID  sql.NullString
}

func (q *Queries) GetPlanByTypeID(ctx context.Context, typeID string) (GetPlanByTypeIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPlanByTypeID, typeID)
	var i GetPlanByTypeIDRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.TypeID,
		&i.Name,
		&i.PlanTypeCode,
		&i.PricePerSeat,
		&i.PricePerMonth,
		&i.SeatMinimum,
		&i.DisplayFeatures,
		&i.DisplayOrder,
		&i.IsHighlighted,
		&i.ButtonText,
		&i.IncludesPreviousPlan,
		&i.StripePricingPlanID,
	)
	return i, err
}

const getPlanLimitsByTypeID = `-- name: GetPlanLimitsByTypeID :many
SELECT ` + "`" + `key` + "`" + `, value
FROM account_plan_limit
WHERE account_plan_id = ?
ORDER BY ` + "`" + `key` + "`" + ` ASC
`

type GetPlanLimitsByTypeIDRow struct {
	Key   string
	Value sql.NullInt32
}

func (q *Queries) GetPlanLimitsByTypeID(ctx context.Context, accountPlanID string) ([]GetPlanLimitsByTypeIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlanLimitsByTypeID, accountPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlanLimitsByTypeIDRow
	for rows.Next() {
		var i GetPlanLimitsByTypeIDRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPricingPlansBackward = `-- name: ListPricingPlansBackward :many
SELECT id, created_at, type_id, name, plan_type_code, price_per_seat, price_per_month,
       seat_minimum, display_features, display_order, is_highlighted,
       button_text, includes_previous_plan, stripe_pricing_plan_id
FROM account_plan
WHERE (expires_at IS NULL OR expires_at > NOW(3))
  AND effective_at <= NOW(3)
  AND plan_type_code != 'enterprise'
  AND (
    account_plan.created_at > ?
    OR (account_plan.created_at = ? AND account_plan.id > ?)
  )
  AND (
    ? IS NULL
    OR account_plan.name LIKE ?
  )
ORDER BY account_plan.created_at ASC, account_plan.id ASC
LIMIT ?
`

type ListPricingPlansBackwardParams struct {
	CursorCreatedAt time.Time
	CursorID        int64
	SearchQuery     sql.NullString
	Limit           int32
}

type ListPricingPlansBackwardRow struct {
	ID                   int64
	CreatedAt            time.Time
	TypeID               string
	Name                 string
	PlanTypeCode         string
	PricePerSeat         string
	PricePerMonth        sql.NullString
	SeatMinimum          sql.NullInt32
	DisplayFeatures      json.RawMessage
	DisplayOrder         int32
	IsHighlighted        bool
	ButtonText           string
	IncludesPreviousPlan sql.NullString
	StripePricingPlanID  sql.NullString
}

func (q *Queries) ListPricingPlansBackward(ctx context.Context, arg ListPricingPlansBackwardParams) ([]ListPricingPlansBackwardRow, error) {
	rows, err := q.db.QueryContext(ctx, listPricingPlansBackward,
		arg.CursorCreatedAt,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.SearchQuery,
		arg.SearchQuery,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPricingPlansBackwardRow
	for rows.Next() {
		var i ListPricingPlansBackwardRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.TypeID,
			&i.Name,
			&i.PlanTypeCode,
			&i.PricePerSeat,
			&i.PricePerMonth,
			&i.SeatMinimum,
			&i.DisplayFeatures,
			&i.DisplayOrder,
			&i.IsHighlighted,
			&i.ButtonText,
			&i.IncludesPreviousPlan,
			&i.StripePricingPlanID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPricingPlansForward = `-- name: ListPricingPlansForward :many
SELECT id, created_at, type_id, name, plan_type_code, price_per_seat, price_per_month,
       seat_minimum, display_features, display_order, is_highlighted,
       button_text, includes_previous_plan, stripe_pricing_plan_id
FROM account_plan
WHERE (expires_at IS NULL OR expires_at > NOW(3))
  AND effective_at <= NOW(3)
  AND plan_type_code != 'enterprise'
  AND (
    ? IS NULL
    OR account_plan.created_at < ?
    OR (account_plan.created_at = ? AND account_plan.id < ?)
  )
  AND (
    ? IS NULL
    OR account_plan.name LIKE ?
  )
ORDER BY account_plan.created_at DESC, account_plan.id DESC
LIMIT ?
`

type ListPricingPlansForwardParams struct {
	CursorCreatedAt sql.NullTime
	CursorID        sql.NullInt64
	SearchQuery     sql.NullString
	Limit           int32
}

type ListPricingPlansForwardRow struct {
	ID                   int64
	CreatedAt            time.Time
	TypeID               string
	Name                 string
	PlanTypeCode         string
	PricePerSeat         string
	PricePerMonth        sql.NullString
	SeatMinimum          sql.NullInt32
	DisplayFeatures      json.RawMessage
	DisplayOrder         int32
	IsHighlighted        bool
	ButtonText           string
	IncludesPreviousPlan sql.NullString
	StripePricingPlanID  sql.NullString
}

func (q *Queries) ListPricingPlansForward(ctx context.Context, arg ListPricingPlansForwardParams) ([]ListPricingPlansForwardRow, error) {
	rows, err := q.db.QueryContext(ctx, listPricingPlansForward,
		arg.CursorCreatedAt,
		arg.CursorCreatedAt,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.SearchQuery,
		arg.SearchQuery,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPricingPlansForwardRow
	for rows.Next() {
		var i ListPricingPlansForwardRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.TypeID,
			&i.Name,
			&i.PlanTypeCode,
			&i.PricePerSeat,
			&i.PricePerMonth,
			&i.SeatMinimum,
			&i.DisplayFeatures,
			&i.DisplayOrder,
			&i.IsHighlighted,
			&i.ButtonText,
			&i.IncludesPreviousPlan,
			&i.StripePricingPlanID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
