// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.0
// source: notification/notification_messaging.proto

// MessagingService is the in-app notifications + messaging (chat) contract for the
// notification-service. This file covers the Phase-1 surface: the per-user notification
// "bell" feed (list, unread count, seen/read/dismiss) and admin/system notification
// sends (targeted or broadcast). Conversations, messages, participants, and the realtime
// path are added in later phases.
//
// Caller identity is propagated over gRPC metadata (see shared/rpc, shared/appctx); the
// service derives the recipient from identity.actor.id and the tenant from
// identity.target.account_id. Requests therefore do not embed the recipient/account.

package notification

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessagingService_SendNotification_FullMethodName             = "/notification.MessagingService/SendNotification"
	MessagingService_ListNotifications_FullMethodName            = "/notification.MessagingService/ListNotifications"
	MessagingService_GetNotification_FullMethodName              = "/notification.MessagingService/GetNotification"
	MessagingService_GetUnreadCount_FullMethodName               = "/notification.MessagingService/GetUnreadCount"
	MessagingService_GetUnreadSummary_FullMethodName             = "/notification.MessagingService/GetUnreadSummary"
	MessagingService_MarkNotificationSeen_FullMethodName         = "/notification.MessagingService/MarkNotificationSeen"
	MessagingService_MarkNotificationRead_FullMethodName         = "/notification.MessagingService/MarkNotificationRead"
	MessagingService_MarkNotificationDismissed_FullMethodName    = "/notification.MessagingService/MarkNotificationDismissed"
	MessagingService_MarkAllNotificationsSeen_FullMethodName     = "/notification.MessagingService/MarkAllNotificationsSeen"
	MessagingService_ListAnnouncements_FullMethodName            = "/notification.MessagingService/ListAnnouncements"
	MessagingService_GetAnnouncement_FullMethodName              = "/notification.MessagingService/GetAnnouncement"
	MessagingService_MarkAnnouncementSeen_FullMethodName         = "/notification.MessagingService/MarkAnnouncementSeen"
	MessagingService_MarkAnnouncementRead_FullMethodName         = "/notification.MessagingService/MarkAnnouncementRead"
	MessagingService_MarkAnnouncementDismissed_FullMethodName    = "/notification.MessagingService/MarkAnnouncementDismissed"
	MessagingService_ListNotificationPreferences_FullMethodName  = "/notification.MessagingService/ListNotificationPreferences"
	MessagingService_UpsertNotificationPreference_FullMethodName = "/notification.MessagingService/UpsertNotificationPreference"
)

// MessagingServiceClient is the client API for MessagingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessagingServiceClient interface {
	// SendNotification creates a notification for a single target user, or fans out a
	// broadcast to all active users in the account. Admin/system only.
	SendNotification(ctx context.Context, in *SendNotificationRequest, opts ...grpc.CallOption) (*SendNotificationResponse, error)
	// ListNotifications returns the caller's notification feed (cursor-paginated).
	ListNotifications(ctx context.Context, in *ListNotificationsRequest, opts ...grpc.CallOption) (*ListNotificationsResponse, error)
	// GetNotification returns a single notification owned by the caller.
	GetNotification(ctx context.Context, in *GetNotificationRequest, opts ...grpc.CallOption) (*NotificationInfo, error)
	// GetUnreadCount returns the caller's unread tallies (bell + conversations + total).
	GetUnreadCount(ctx context.Context, in *GetUnreadCountRequest, opts ...grpc.CallOption) (*GetUnreadCountResponse, error)
	// GetUnreadSummary returns the caller's unread totals across every account they belong to.
	GetUnreadSummary(ctx context.Context, in *GetUnreadSummaryRequest, opts ...grpc.CallOption) (*GetUnreadSummaryResponse, error)
	// MarkNotificationSeen sets seen_at (idempotent). "Seen" = surfaced in the dropdown.
	MarkNotificationSeen(ctx context.Context, in *MarkNotificationRequest, opts ...grpc.CallOption) (*NotificationInfo, error)
	// MarkNotificationRead sets read_at (idempotent). "Read" = explicitly opened.
	MarkNotificationRead(ctx context.Context, in *MarkNotificationRequest, opts ...grpc.CallOption) (*NotificationInfo, error)
	// MarkNotificationDismissed sets dismissed_at (idempotent). "Dismissed" = swiped away.
	MarkNotificationDismissed(ctx context.Context, in *MarkNotificationRequest, opts ...grpc.CallOption) (*NotificationInfo, error)
	// MarkAllNotificationsSeen marks every unseen notification for the caller as seen.
	MarkAllNotificationsSeen(ctx context.Context, in *MarkAllNotificationsSeenRequest, opts ...grpc.CallOption) (*MarkAllNotificationsSeenResponse, error)
	// ListAnnouncements returns the caller's active broadcast announcements (cursor-paginated).
	ListAnnouncements(ctx context.Context, in *ListAnnouncementsRequest, opts ...grpc.CallOption) (*ListAnnouncementsResponse, error)
	// GetAnnouncement returns a single active announcement visible to the caller.
	GetAnnouncement(ctx context.Context, in *GetAnnouncementRequest, opts ...grpc.CallOption) (*AnnouncementInfo, error)
	// MarkAnnouncementSeen/Read/Dismissed transition the caller's per-user receipt (idempotent).
	MarkAnnouncementSeen(ctx context.Context, in *MarkAnnouncementRequest, opts ...grpc.CallOption) (*AnnouncementInfo, error)
	MarkAnnouncementRead(ctx context.Context, in *MarkAnnouncementRequest, opts ...grpc.CallOption) (*AnnouncementInfo, error)
	MarkAnnouncementDismissed(ctx context.Context, in *MarkAnnouncementRequest, opts ...grpc.CallOption) (*AnnouncementInfo, error)
	// ── Phase 4: notification channel preferences ──
	// ListNotificationPreferences returns the caller's channel preferences (global + per-category).
	ListNotificationPreferences(ctx context.Context, in *ListNotificationPreferencesRequest, opts ...grpc.CallOption) (*ListNotificationPreferencesResponse, error)
	// UpsertNotificationPreference creates or replaces the caller's preference for a category.
	UpsertNotificationPreference(ctx context.Context, in *UpsertNotificationPreferenceRequest, opts ...grpc.CallOption) (*NotificationPreferenceInfo, error)
}

type messagingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessagingServiceClient(cc grpc.ClientConnInterface) MessagingServiceClient {
	return &messagingServiceClient{cc}
}

func (c *messagingServiceClient) SendNotification(ctx context.Context, in *SendNotificationRequest, opts ...grpc.CallOption) (*SendNotificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendNotificationResponse)
	err := c.cc.Invoke(ctx, MessagingService_SendNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingServiceClient) ListNotifications(ctx context.Context, in *ListNotificationsRequest, opts ...grpc.CallOption) (*ListNotificationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNotificationsResponse)
	err := c.cc.Invoke(ctx, MessagingService_ListNotifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingServiceClient) GetNotification(ctx context.Context, in *GetNotificationRequest, opts ...grpc.CallOption) (*NotificationInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotificationInfo)
	err := c.cc.Invoke(ctx, MessagingService_GetNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingServiceClient) GetUnreadCount(ctx context.Context, in *GetUnreadCountRequest, opts ...grpc.CallOption) (*GetUnreadCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUnreadCountResponse)
	err := c.cc.Invoke(ctx, MessagingService_GetUnreadCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingServiceClient) GetUnreadSummary(ctx context.Context, in *GetUnreadSummaryRequest, opts ...grpc.CallOption) (*GetUnreadSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUnreadSummaryResponse)
	err := c.cc.Invoke(ctx, MessagingService_GetUnreadSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingServiceClient) MarkNotificationSeen(ctx context.Context, in *MarkNotificationRequest, opts ...grpc.CallOption) (*NotificationInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotificationInfo)
	err := c.cc.Invoke(ctx, MessagingService_MarkNotificationSeen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingServiceClient) MarkNotificationRead(ctx context.Context, in *MarkNotificationRequest, opts ...grpc.CallOption) (*NotificationInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotificationInfo)
	err := c.cc.Invoke(ctx, MessagingService_MarkNotificationRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingServiceClient) MarkNotificationDismissed(ctx context.Context, in *MarkNotificationRequest, opts ...grpc.CallOption) (*NotificationInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotificationInfo)
	err := c.cc.Invoke(ctx, MessagingService_MarkNotificationDismissed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingServiceClient) MarkAllNotificationsSeen(ctx context.Context, in *MarkAllNotificationsSeenRequest, opts ...grpc.CallOption) (*MarkAllNotificationsSeenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkAllNotificationsSeenResponse)
	err := c.cc.Invoke(ctx, MessagingService_MarkAllNotificationsSeen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingServiceClient) ListAnnouncements(ctx context.Context, in *ListAnnouncementsRequest, opts ...grpc.CallOption) (*ListAnnouncementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAnnouncementsResponse)
	err := c.cc.Invoke(ctx, MessagingService_ListAnnouncements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingServiceClient) GetAnnouncement(ctx context.Context, in *GetAnnouncementRequest, opts ...grpc.CallOption) (*AnnouncementInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnnouncementInfo)
	err := c.cc.Invoke(ctx, MessagingService_GetAnnouncement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingServiceClient) MarkAnnouncementSeen(ctx context.Context, in *MarkAnnouncementRequest, opts ...grpc.CallOption) (*AnnouncementInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnnouncementInfo)
	err := c.cc.Invoke(ctx, MessagingService_MarkAnnouncementSeen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingServiceClient) MarkAnnouncementRead(ctx context.Context, in *MarkAnnouncementRequest, opts ...grpc.CallOption) (*AnnouncementInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnnouncementInfo)
	err := c.cc.Invoke(ctx, MessagingService_MarkAnnouncementRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingServiceClient) MarkAnnouncementDismissed(ctx context.Context, in *MarkAnnouncementRequest, opts ...grpc.CallOption) (*AnnouncementInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnnouncementInfo)
	err := c.cc.Invoke(ctx, MessagingService_MarkAnnouncementDismissed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingServiceClient) ListNotificationPreferences(ctx context.Context, in *ListNotificationPreferencesRequest, opts ...grpc.CallOption) (*ListNotificationPreferencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNotificationPreferencesResponse)
	err := c.cc.Invoke(ctx, MessagingService_ListNotificationPreferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingServiceClient) UpsertNotificationPreference(ctx context.Context, in *UpsertNotificationPreferenceRequest, opts ...grpc.CallOption) (*NotificationPreferenceInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotificationPreferenceInfo)
	err := c.cc.Invoke(ctx, MessagingService_UpsertNotificationPreference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessagingServiceServer is the server API for MessagingService service.
// All implementations must embed UnimplementedMessagingServiceServer
// for forward compatibility.
type MessagingServiceServer interface {
	// SendNotification creates a notification for a single target user, or fans out a
	// broadcast to all active users in the account. Admin/system only.
	SendNotification(context.Context, *SendNotificationRequest) (*SendNotificationResponse, error)
	// ListNotifications returns the caller's notification feed (cursor-paginated).
	ListNotifications(context.Context, *ListNotificationsRequest) (*ListNotificationsResponse, error)
	// GetNotification returns a single notification owned by the caller.
	GetNotification(context.Context, *GetNotificationRequest) (*NotificationInfo, error)
	// GetUnreadCount returns the caller's unread tallies (bell + conversations + total).
	GetUnreadCount(context.Context, *GetUnreadCountRequest) (*GetUnreadCountResponse, error)
	// GetUnreadSummary returns the caller's unread totals across every account they belong to.
	GetUnreadSummary(context.Context, *GetUnreadSummaryRequest) (*GetUnreadSummaryResponse, error)
	// MarkNotificationSeen sets seen_at (idempotent). "Seen" = surfaced in the dropdown.
	MarkNotificationSeen(context.Context, *MarkNotificationRequest) (*NotificationInfo, error)
	// MarkNotificationRead sets read_at (idempotent). "Read" = explicitly opened.
	MarkNotificationRead(context.Context, *MarkNotificationRequest) (*NotificationInfo, error)
	// MarkNotificationDismissed sets dismissed_at (idempotent). "Dismissed" = swiped away.
	MarkNotificationDismissed(context.Context, *MarkNotificationRequest) (*NotificationInfo, error)
	// MarkAllNotificationsSeen marks every unseen notification for the caller as seen.
	MarkAllNotificationsSeen(context.Context, *MarkAllNotificationsSeenRequest) (*MarkAllNotificationsSeenResponse, error)
	// ListAnnouncements returns the caller's active broadcast announcements (cursor-paginated).
	ListAnnouncements(context.Context, *ListAnnouncementsRequest) (*ListAnnouncementsResponse, error)
	// GetAnnouncement returns a single active announcement visible to the caller.
	GetAnnouncement(context.Context, *GetAnnouncementRequest) (*AnnouncementInfo, error)
	// MarkAnnouncementSeen/Read/Dismissed transition the caller's per-user receipt (idempotent).
	MarkAnnouncementSeen(context.Context, *MarkAnnouncementRequest) (*AnnouncementInfo, error)
	MarkAnnouncementRead(context.Context, *MarkAnnouncementRequest) (*AnnouncementInfo, error)
	MarkAnnouncementDismissed(context.Context, *MarkAnnouncementRequest) (*AnnouncementInfo, error)
	// ── Phase 4: notification channel preferences ──
	// ListNotificationPreferences returns the caller's channel preferences (global + per-category).
	ListNotificationPreferences(context.Context, *ListNotificationPreferencesRequest) (*ListNotificationPreferencesResponse, error)
	// UpsertNotificationPreference creates or replaces the caller's preference for a category.
	UpsertNotificationPreference(context.Context, *UpsertNotificationPreferenceRequest) (*NotificationPreferenceInfo, error)
	mustEmbedUnimplementedMessagingServiceServer()
}

// UnimplementedMessagingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessagingServiceServer struct{}

func (UnimplementedMessagingServiceServer) SendNotification(context.Context, *SendNotificationRequest) (*SendNotificationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendNotification not implemented")
}
func (UnimplementedMessagingServiceServer) ListNotifications(context.Context, *ListNotificationsRequest) (*ListNotificationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNotifications not implemented")
}
func (UnimplementedMessagingServiceServer) GetNotification(context.Context, *GetNotificationRequest) (*NotificationInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNotification not implemented")
}
func (UnimplementedMessagingServiceServer) GetUnreadCount(context.Context, *GetUnreadCountRequest) (*GetUnreadCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUnreadCount not implemented")
}
func (UnimplementedMessagingServiceServer) GetUnreadSummary(context.Context, *GetUnreadSummaryRequest) (*GetUnreadSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUnreadSummary not implemented")
}
func (UnimplementedMessagingServiceServer) MarkNotificationSeen(context.Context, *MarkNotificationRequest) (*NotificationInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkNotificationSeen not implemented")
}
func (UnimplementedMessagingServiceServer) MarkNotificationRead(context.Context, *MarkNotificationRequest) (*NotificationInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkNotificationRead not implemented")
}
func (UnimplementedMessagingServiceServer) MarkNotificationDismissed(context.Context, *MarkNotificationRequest) (*NotificationInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkNotificationDismissed not implemented")
}
func (UnimplementedMessagingServiceServer) MarkAllNotificationsSeen(context.Context, *MarkAllNotificationsSeenRequest) (*MarkAllNotificationsSeenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkAllNotificationsSeen not implemented")
}
func (UnimplementedMessagingServiceServer) ListAnnouncements(context.Context, *ListAnnouncementsRequest) (*ListAnnouncementsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAnnouncements not implemented")
}
func (UnimplementedMessagingServiceServer) GetAnnouncement(context.Context, *GetAnnouncementRequest) (*AnnouncementInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAnnouncement not implemented")
}
func (UnimplementedMessagingServiceServer) MarkAnnouncementSeen(context.Context, *MarkAnnouncementRequest) (*AnnouncementInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkAnnouncementSeen not implemented")
}
func (UnimplementedMessagingServiceServer) MarkAnnouncementRead(context.Context, *MarkAnnouncementRequest) (*AnnouncementInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkAnnouncementRead not implemented")
}
func (UnimplementedMessagingServiceServer) MarkAnnouncementDismissed(context.Context, *MarkAnnouncementRequest) (*AnnouncementInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkAnnouncementDismissed not implemented")
}
func (UnimplementedMessagingServiceServer) ListNotificationPreferences(context.Context, *ListNotificationPreferencesRequest) (*ListNotificationPreferencesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNotificationPreferences not implemented")
}
func (UnimplementedMessagingServiceServer) UpsertNotificationPreference(context.Context, *UpsertNotificationPreferenceRequest) (*NotificationPreferenceInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertNotificationPreference not implemented")
}
func (UnimplementedMessagingServiceServer) mustEmbedUnimplementedMessagingServiceServer() {}
func (UnimplementedMessagingServiceServer) testEmbeddedByValue()                          {}

// UnsafeMessagingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessagingServiceServer will
// result in compilation errors.
type UnsafeMessagingServiceServer interface {
	mustEmbedUnimplementedMessagingServiceServer()
}

func RegisterMessagingServiceServer(s grpc.ServiceRegistrar, srv MessagingServiceServer) {
	// If the following call panics, it indicates UnimplementedMessagingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessagingService_ServiceDesc, srv)
}

func _MessagingService_SendNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServiceServer).SendNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagingService_SendNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServiceServer).SendNotification(ctx, req.(*SendNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagingService_ListNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServiceServer).ListNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagingService_ListNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServiceServer).ListNotifications(ctx, req.(*ListNotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagingService_GetNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServiceServer).GetNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagingService_GetNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServiceServer).GetNotification(ctx, req.(*GetNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagingService_GetUnreadCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnreadCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServiceServer).GetUnreadCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagingService_GetUnreadCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServiceServer).GetUnreadCount(ctx, req.(*GetUnreadCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagingService_GetUnreadSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnreadSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServiceServer).GetUnreadSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagingService_GetUnreadSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServiceServer).GetUnreadSummary(ctx, req.(*GetUnreadSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagingService_MarkNotificationSeen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServiceServer).MarkNotificationSeen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagingService_MarkNotificationSeen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServiceServer).MarkNotificationSeen(ctx, req.(*MarkNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagingService_MarkNotificationRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServiceServer).MarkNotificationRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagingService_MarkNotificationRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServiceServer).MarkNotificationRead(ctx, req.(*MarkNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagingService_MarkNotificationDismissed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServiceServer).MarkNotificationDismissed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagingService_MarkNotificationDismissed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServiceServer).MarkNotificationDismissed(ctx, req.(*MarkNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagingService_MarkAllNotificationsSeen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkAllNotificationsSeenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServiceServer).MarkAllNotificationsSeen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagingService_MarkAllNotificationsSeen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServiceServer).MarkAllNotificationsSeen(ctx, req.(*MarkAllNotificationsSeenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagingService_ListAnnouncements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAnnouncementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServiceServer).ListAnnouncements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagingService_ListAnnouncements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServiceServer).ListAnnouncements(ctx, req.(*ListAnnouncementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagingService_GetAnnouncement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnnouncementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServiceServer).GetAnnouncement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagingService_GetAnnouncement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServiceServer).GetAnnouncement(ctx, req.(*GetAnnouncementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagingService_MarkAnnouncementSeen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkAnnouncementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServiceServer).MarkAnnouncementSeen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagingService_MarkAnnouncementSeen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServiceServer).MarkAnnouncementSeen(ctx, req.(*MarkAnnouncementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagingService_MarkAnnouncementRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkAnnouncementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServiceServer).MarkAnnouncementRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagingService_MarkAnnouncementRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServiceServer).MarkAnnouncementRead(ctx, req.(*MarkAnnouncementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagingService_MarkAnnouncementDismissed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkAnnouncementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServiceServer).MarkAnnouncementDismissed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagingService_MarkAnnouncementDismissed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServiceServer).MarkAnnouncementDismissed(ctx, req.(*MarkAnnouncementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagingService_ListNotificationPreferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNotificationPreferencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServiceServer).ListNotificationPreferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagingService_ListNotificationPreferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServiceServer).ListNotificationPreferences(ctx, req.(*ListNotificationPreferencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagingService_UpsertNotificationPreference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertNotificationPreferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServiceServer).UpsertNotificationPreference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessagingService_UpsertNotificationPreference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServiceServer).UpsertNotificationPreference(ctx, req.(*UpsertNotificationPreferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessagingService_ServiceDesc is the grpc.ServiceDesc for MessagingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessagingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.MessagingService",
	HandlerType: (*MessagingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendNotification",
			Handler:    _MessagingService_SendNotification_Handler,
		},
		{
			MethodName: "ListNotifications",
			Handler:    _MessagingService_ListNotifications_Handler,
		},
		{
			MethodName: "GetNotification",
			Handler:    _MessagingService_GetNotification_Handler,
		},
		{
			MethodName: "GetUnreadCount",
			Handler:    _MessagingService_GetUnreadCount_Handler,
		},
		{
			MethodName: "GetUnreadSummary",
			Handler:    _MessagingService_GetUnreadSummary_Handler,
		},
		{
			MethodName: "MarkNotificationSeen",
			Handler:    _MessagingService_MarkNotificationSeen_Handler,
		},
		{
			MethodName: "MarkNotificationRead",
			Handler:    _MessagingService_MarkNotificationRead_Handler,
		},
		{
			MethodName: "MarkNotificationDismissed",
			Handler:    _MessagingService_MarkNotificationDismissed_Handler,
		},
		{
			MethodName: "MarkAllNotificationsSeen",
			Handler:    _MessagingService_MarkAllNotificationsSeen_Handler,
		},
		{
			MethodName: "ListAnnouncements",
			Handler:    _MessagingService_ListAnnouncements_Handler,
		},
		{
			MethodName: "GetAnnouncement",
			Handler:    _MessagingService_GetAnnouncement_Handler,
		},
		{
			MethodName: "MarkAnnouncementSeen",
			Handler:    _MessagingService_MarkAnnouncementSeen_Handler,
		},
		{
			MethodName: "MarkAnnouncementRead",
			Handler:    _MessagingService_MarkAnnouncementRead_Handler,
		},
		{
			MethodName: "MarkAnnouncementDismissed",
			Handler:    _MessagingService_MarkAnnouncementDismissed_Handler,
		},
		{
			MethodName: "ListNotificationPreferences",
			Handler:    _MessagingService_ListNotificationPreferences_Handler,
		},
		{
			MethodName: "UpsertNotificationPreference",
			Handler:    _MessagingService_UpsertNotificationPreference_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification/notification_messaging.proto",
}
