apiVersion: v1
kind: ConfigMap
metadata:
    name: app-config
data:
    PLATFORM: "development"
    PORT: "8081"
    AWS_REGION: "us-east-2"
    FRONTEND_URL: "http://localhost:4200"
    ACCOUNT_PHOTOS_BUCKET: "augno-org-logos-dev"
    USER_PHOTOS_BUCKET: "augno-user-photos-dev"
    SHIPPING_LABELS_BUCKET: "augno-shipping-labels-dev"
    AUTH_SERVICE_URL: "auth-service:9092"
    CORE_SERVICE_URL: "core-service:9092"
    NOTIFICATION_SERVICE_URL: "notification-service:9092"
    BILLING_SERVICE_URL: "billing-service:9092"
    PLATFORM_SERVICE_URL: "platform-service:9092"
    AGENT_SERVICE_URL: "agent-service:9092"
