// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/augno/api/services/auth-service/internal/domain (interfaces: IdempotencyMed)
//
// Generated by this command:
//
//	mockgen -destination /Users/dane/Code/augno/core/api/services/auth-service/internal/domain/mock/mediator/idempotency_med_mock.go -package mediatormock github.com/augno/api/services/auth-service/internal/domain IdempotencyMed
//

// Package mediatormock is a generated GoMock package.
package mediatormock

import (
	context "context"
	reflect "reflect"

	domain "github.com/augno/api/services/auth-service/internal/domain"
	apierror "github.com/augno/api/shared/errors"
	gomock "go.uber.org/mock/gomock"
)

// MockIdempotencyMed is a mock of IdempotencyMed interface.
type MockIdempotencyMed struct {
	ctrl     *gomock.Controller
	recorder *MockIdempotencyMedMockRecorder
	isgomock struct{}
}

// MockIdempotencyMedMockRecorder is the mock recorder for MockIdempotencyMed.
type MockIdempotencyMedMockRecorder struct {
	mock *MockIdempotencyMed
}

// NewMockIdempotencyMed creates a new mock instance.
func NewMockIdempotencyMed(ctrl *gomock.Controller) *MockIdempotencyMed {
	mock := &MockIdempotencyMed{ctrl: ctrl}
	mock.recorder = &MockIdempotencyMedMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdempotencyMed) EXPECT() *MockIdempotencyMedMockRecorder {
	return m.recorder
}

// CacheErrorResponse mocks base method.
func (m *MockIdempotencyMed) CacheErrorResponse(ctx context.Context, typeID string, apiErr *apierror.APIError) *apierror.APIError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CacheErrorResponse", ctx, typeID, apiErr)
	ret0, _ := ret[0].(*apierror.APIError)
	return ret0
}

// CacheErrorResponse indicates an expected call of CacheErrorResponse.
func (mr *MockIdempotencyMedMockRecorder) CacheErrorResponse(ctx, typeID, apiErr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CacheErrorResponse", reflect.TypeOf((*MockIdempotencyMed)(nil).CacheErrorResponse), ctx, typeID, apiErr)
}

// CacheSuccessResponse mocks base method.
func (m *MockIdempotencyMed) CacheSuccessResponse(ctx context.Context, typeID string, data any) *apierror.APIError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CacheSuccessResponse", ctx, typeID, data)
	ret0, _ := ret[0].(*apierror.APIError)
	return ret0
}

// CacheSuccessResponse indicates an expected call of CacheSuccessResponse.
func (mr *MockIdempotencyMedMockRecorder) CacheSuccessResponse(ctx, typeID, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CacheSuccessResponse", reflect.TypeOf((*MockIdempotencyMed)(nil).CacheSuccessResponse), ctx, typeID, data)
}

// UpsertIdempotencyKey mocks base method.
func (m *MockIdempotencyMed) UpsertIdempotencyKey(ctx context.Context, identity *domain.RequestIdentity) (*domain.IdempotencyKey, *apierror.APIError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertIdempotencyKey", ctx, identity)
	ret0, _ := ret[0].(*domain.IdempotencyKey)
	ret1, _ := ret[1].(*apierror.APIError)
	return ret0, ret1
}

// UpsertIdempotencyKey indicates an expected call of UpsertIdempotencyKey.
func (mr *MockIdempotencyMedMockRecorder) UpsertIdempotencyKey(ctx, identity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertIdempotencyKey", reflect.TypeOf((*MockIdempotencyMed)(nil).UpsertIdempotencyKey), ctx, identity)
}
