// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: request_log.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createRequestLog = `-- name: CreateRequestLog :exec
INSERT INTO request_log (
        id,
        method,
        host,
        path,
        normalized_route,
        status_code,
        latency_us,
        account_id,
        target_account_id,
        client_ip,
        client_ip_string,
        user_agent,
        referrer,
        error_code,
        error_message,
        occurred_at,
        created_at,
        idempotency_key_id,
        actor_id,
        actor_type,
        internal_error_message,
        identity_type,
        api_version,
        trace_id,
        public_endpoint,
        hidden,
        payload_key
    )
VALUES (
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?
    )
`

type CreateRequestLogParams struct {
	ID                   string
	Method               string
	Host                 string
	Path                 string
	NormalizedRoute      string
	StatusCode           int32
	LatencyUs            int64
	AccountID            sql.NullString
	TargetAccountID      sql.NullString
	ClientIp             sql.NullString
	ClientIpString       sql.NullString
	UserAgent            sql.NullString
	Referrer             sql.NullString
	ErrorCode            sql.NullString
	ErrorMessage         sql.NullString
	OccurredAt           time.Time
	CreatedAt            time.Time
	IdempotencyKeyID     sql.NullString
	ActorID              sql.NullString
	ActorType            sql.NullString
	InternalErrorMessage sql.NullString
	IdentityType         sql.NullString
	ApiVersion           sql.NullString
	TraceID              sql.NullString
	PublicEndpoint       bool
	Hidden               bool
	PayloadKey           sql.NullString
}

func (q *Queries) CreateRequestLog(ctx context.Context, arg CreateRequestLogParams) error {
	_, err := q.db.ExecContext(ctx, createRequestLog,
		arg.ID,
		arg.Method,
		arg.Host,
		arg.Path,
		arg.NormalizedRoute,
		arg.StatusCode,
		arg.LatencyUs,
		arg.AccountID,
		arg.TargetAccountID,
		arg.ClientIp,
		arg.ClientIpString,
		arg.UserAgent,
		arg.Referrer,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.OccurredAt,
		arg.CreatedAt,
		arg.IdempotencyKeyID,
		arg.ActorID,
		arg.ActorType,
		arg.InternalErrorMessage,
		arg.IdentityType,
		arg.ApiVersion,
		arg.TraceID,
		arg.PublicEndpoint,
		arg.Hidden,
		arg.PayloadKey,
	)
	return err
}

const deleteExpiredRequestLogs = `-- name: DeleteExpiredRequestLogs :execresult
DELETE FROM request_log
WHERE occurred_at < DATE_SUB(NOW(3), INTERVAL 7 YEAR)
LIMIT ?
`

func (q *Queries) DeleteExpiredRequestLogs(ctx context.Context, limit int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteExpiredRequestLogs, limit)
}

const findRequestLogBaseByID = `-- name: FindRequestLogBaseByID :one

SELECT rl.id, rl.method, rl.host, rl.path, rl.normalized_route,
       rl.status_code, rl.latency_us, rl.api_version, rl.actor_id AS actor_id,
       rl.actor_type, rl.identity_type, rl.client_ip_string, rl.user_agent,
       rl.referrer, rl.error_code, rl.error_message, rl.occurred_at, rl.created_at,
       rl.idempotency_key_id, rl.payload_key,
       rl.target_account_id,
       ik.idempotency_key
FROM request_log rl
LEFT JOIN idempotency_key ik ON rl.idempotency_key_id = ik.type_id
WHERE rl.id = ?
  AND (rl.account_id = ? OR rl.target_account_id = ?)
`

type FindRequestLogBaseByIDParams struct {
	ID              string
	CallerAccountID sql.NullString
}

type FindRequestLogBaseByIDRow struct {
	ID               string
	Method           string
	Host             string
	Path             string
	NormalizedRoute  string
	StatusCode       int32
	LatencyUs        int64
	ApiVersion       sql.NullString
	ActorID          sql.NullString
	ActorType        sql.NullString
	IdentityType     sql.NullString
	ClientIpString   sql.NullString
	UserAgent        sql.NullString
	Referrer         sql.NullString
	ErrorCode        sql.NullString
	ErrorMessage     sql.NullString
	OccurredAt       time.Time
	CreatedAt        time.Time
	IdempotencyKeyID sql.NullString
	PayloadKey       sql.NullString
	TargetAccountID  sql.NullString
	IdempotencyKey   sql.NullString
}

// Request log list queries are built dynamically in Go — see
// repository/request_log_list_query.go. Filter predicates are only emitted
// when the caller supplied a value. The actor-or-target security scope is an OR
// over account_id / target_account_id, satisfied by index_merge over the
// per-side (…, occurred_at DESC, id DESC) cursor indexes.
// Visible when the caller's account is either the acting account or the target.
func (q *Queries) FindRequestLogBaseByID(ctx context.Context, arg FindRequestLogBaseByIDParams) (FindRequestLogBaseByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findRequestLogBaseByID, arg.ID, arg.CallerAccountID, arg.CallerAccountID)
	var i FindRequestLogBaseByIDRow
	err := row.Scan(
		&i.ID,
		&i.Method,
		&i.Host,
		&i.Path,
		&i.NormalizedRoute,
		&i.StatusCode,
		&i.LatencyUs,
		&i.ApiVersion,
		&i.ActorID,
		&i.ActorType,
		&i.IdentityType,
		&i.ClientIpString,
		&i.UserAgent,
		&i.Referrer,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.IdempotencyKeyID,
		&i.PayloadKey,
		&i.TargetAccountID,
		&i.IdempotencyKey,
	)
	return i, err
}

const findRequestLogByID = `-- name: FindRequestLogByID :one
SELECT rl.id, rl.method, rl.host, rl.path, rl.normalized_route,
       rl.status_code, rl.latency_us, rl.api_version, rl.actor_id AS actor_id,
       rl.actor_type, rl.identity_type, rl.client_ip_string, rl.user_agent,
       rl.referrer, rl.error_code, rl.error_message, rl.occurred_at, rl.created_at,
       rl.idempotency_key_id, rl.payload_key,
       u.email AS user_email, u.name AS user_name,
       ak.type_id AS api_key_type_id, ak.redacted_value AS api_key_redacted_value,
       ak.name AS api_key_name,
       au.role_id AS user_role_id,
       r_user.name AS user_role_name, r_user.role_type_code AS user_role_type_code,
       r_key.id AS api_key_role_id, r_key.name AS api_key_role_name, r_key.role_type_code AS api_key_role_type_code,
       rl.target_account_id, a.name AS account_name,
       a.created_at AS account_created_at, a.updated_at AS account_updated_at,
       ik.idempotency_key
FROM request_log rl
LEFT JOIN ` + "`" + `user` + "`" + ` u ON rl.actor_id = u.id AND rl.identity_type = 'user'
LEFT JOIN api_key ak ON rl.actor_id = ak.type_id AND rl.identity_type = 'api_key'
LEFT JOIN account_user au ON au.user_id = rl.actor_id
  AND au.account_id = rl.target_account_id AND rl.identity_type = 'user'
LEFT JOIN role r_user ON au.role_id = r_user.id
LEFT JOIN role r_key ON ak.role_id = r_key.id
LEFT JOIN account a ON rl.target_account_id = a.id
LEFT JOIN idempotency_key ik ON rl.idempotency_key_id = ik.type_id
WHERE rl.id = ?
  AND (rl.account_id = ? OR rl.target_account_id = ?)
`

type FindRequestLogByIDParams struct {
	ID              string
	CallerAccountID sql.NullString
}

type FindRequestLogByIDRow struct {
	ID                  string
	Method              string
	Host                string
	Path                string
	NormalizedRoute     string
	StatusCode          int32
	LatencyUs           int64
	ApiVersion          sql.NullString
	ActorID             sql.NullString
	ActorType           sql.NullString
	IdentityType        sql.NullString
	ClientIpString      sql.NullString
	UserAgent           sql.NullString
	Referrer            sql.NullString
	ErrorCode           sql.NullString
	ErrorMessage        sql.NullString
	OccurredAt          time.Time
	CreatedAt           time.Time
	IdempotencyKeyID    sql.NullString
	PayloadKey          sql.NullString
	UserEmail           sql.NullString
	UserName            sql.NullString
	ApiKeyTypeID        sql.NullString
	ApiKeyRedactedValue sql.NullString
	ApiKeyName          sql.NullString
	UserRoleID          sql.NullString
	UserRoleName        sql.NullString
	UserRoleTypeCode    sql.NullString
	ApiKeyRoleID        sql.NullString
	ApiKeyRoleName      sql.NullString
	ApiKeyRoleTypeCode  sql.NullString
	TargetAccountID     sql.NullString
	AccountName         sql.NullString
	AccountCreatedAt    sql.NullTime
	AccountUpdatedAt    sql.NullTime
	IdempotencyKey      sql.NullString
}

// actor_id stores the raw actor key (user_id for user actors, api_key.type_id
// for api_key actors) — the value the API exposes directly. Enrichment joins key
// on it: user by id, api_key by type_id, and account_user (for the role) by
// (user_id, target account).
// Visible when the caller's account is either the acting account or the target.
func (q *Queries) FindRequestLogByID(ctx context.Context, arg FindRequestLogByIDParams) (FindRequestLogByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findRequestLogByID, arg.ID, arg.CallerAccountID, arg.CallerAccountID)
	var i FindRequestLogByIDRow
	err := row.Scan(
		&i.ID,
		&i.Method,
		&i.Host,
		&i.Path,
		&i.NormalizedRoute,
		&i.StatusCode,
		&i.LatencyUs,
		&i.ApiVersion,
		&i.ActorID,
		&i.ActorType,
		&i.IdentityType,
		&i.ClientIpString,
		&i.UserAgent,
		&i.Referrer,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.IdempotencyKeyID,
		&i.PayloadKey,
		&i.UserEmail,
		&i.UserName,
		&i.ApiKeyTypeID,
		&i.ApiKeyRedactedValue,
		&i.ApiKeyName,
		&i.UserRoleID,
		&i.UserRoleName,
		&i.UserRoleTypeCode,
		&i.ApiKeyRoleID,
		&i.ApiKeyRoleName,
		&i.ApiKeyRoleTypeCode,
		&i.TargetAccountID,
		&i.AccountName,
		&i.AccountCreatedAt,
		&i.AccountUpdatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}
