// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/dane/Code/augno/core/api/services/platform-service/internal/domain/services.go
//
// Generated by this command:
//
//	mockgen -source=/Users/dane/Code/augno/core/api/services/platform-service/internal/domain/services.go -destination=/Users/dane/Code/augno/core/api/services/platform-service/internal/domain/mock/service/services_mock.go -package=servicemock
//

// Package servicemock is a generated GoMock package.
package servicemock

import (
	context "context"
	reflect "reflect"

	domain "github.com/augno/api/services/platform-service/internal/domain"
	apierror "github.com/augno/api/shared/errors"
	gomock "go.uber.org/mock/gomock"
)

// MockLoggingSvc is a mock of LoggingSvc interface.
type MockLoggingSvc struct {
	ctrl     *gomock.Controller
	recorder *MockLoggingSvcMockRecorder
	isgomock struct{}
}

// MockLoggingSvcMockRecorder is the mock recorder for MockLoggingSvc.
type MockLoggingSvcMockRecorder struct {
	mock *MockLoggingSvc
}

// NewMockLoggingSvc creates a new mock instance.
func NewMockLoggingSvc(ctrl *gomock.Controller) *MockLoggingSvc {
	mock := &MockLoggingSvc{ctrl: ctrl}
	mock.recorder = &MockLoggingSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoggingSvc) EXPECT() *MockLoggingSvcMockRecorder {
	return m.recorder
}

// GetRequestLog mocks base method.
func (m *MockLoggingSvc) GetRequestLog(ctx context.Context, id string, includes []string) (*domain.RequestLogRead, *apierror.APIError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequestLog", ctx, id, includes)
	ret0, _ := ret[0].(*domain.RequestLogRead)
	ret1, _ := ret[1].(*apierror.APIError)
	return ret0, ret1
}

// GetRequestLog indicates an expected call of GetRequestLog.
func (mr *MockLoggingSvcMockRecorder) GetRequestLog(ctx, id, includes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequestLog", reflect.TypeOf((*MockLoggingSvc)(nil).GetRequestLog), ctx, id, includes)
}

// ListRequestLogs mocks base method.
func (m *MockLoggingSvc) ListRequestLogs(ctx context.Context, filter *domain.ListRequestLogsFilter, includes []string) (*domain.ListRequestLogsResult, *apierror.APIError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRequestLogs", ctx, filter, includes)
	ret0, _ := ret[0].(*domain.ListRequestLogsResult)
	ret1, _ := ret[1].(*apierror.APIError)
	return ret0, ret1
}

// ListRequestLogs indicates an expected call of ListRequestLogs.
func (mr *MockLoggingSvcMockRecorder) ListRequestLogs(ctx, filter, includes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRequestLogs", reflect.TypeOf((*MockLoggingSvc)(nil).ListRequestLogs), ctx, filter, includes)
}

// SaveRequestLog mocks base method.
func (m *MockLoggingSvc) SaveRequestLog(ctx context.Context, rl *domain.RequestLog) *apierror.APIError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRequestLog", ctx, rl)
	ret0, _ := ret[0].(*apierror.APIError)
	return ret0
}

// SaveRequestLog indicates an expected call of SaveRequestLog.
func (mr *MockLoggingSvcMockRecorder) SaveRequestLog(ctx, rl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRequestLog", reflect.TypeOf((*MockLoggingSvc)(nil).SaveRequestLog), ctx, rl)
}

// MockAuditEventSvc is a mock of AuditEventSvc interface.
type MockAuditEventSvc struct {
	ctrl     *gomock.Controller
	recorder *MockAuditEventSvcMockRecorder
	isgomock struct{}
}

// MockAuditEventSvcMockRecorder is the mock recorder for MockAuditEventSvc.
type MockAuditEventSvcMockRecorder struct {
	mock *MockAuditEventSvc
}

// NewMockAuditEventSvc creates a new mock instance.
func NewMockAuditEventSvc(ctrl *gomock.Controller) *MockAuditEventSvc {
	mock := &MockAuditEventSvc{ctrl: ctrl}
	mock.recorder = &MockAuditEventSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditEventSvc) EXPECT() *MockAuditEventSvcMockRecorder {
	return m.recorder
}

// BatchGetResourceCreators mocks base method.
func (m *MockAuditEventSvc) BatchGetResourceCreators(ctx context.Context, resourceType string, resourceIDs []string) ([]domain.ResourceCreator, *apierror.APIError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGetResourceCreators", ctx, resourceType, resourceIDs)
	ret0, _ := ret[0].([]domain.ResourceCreator)
	ret1, _ := ret[1].(*apierror.APIError)
	return ret0, ret1
}

// BatchGetResourceCreators indicates an expected call of BatchGetResourceCreators.
func (mr *MockAuditEventSvcMockRecorder) BatchGetResourceCreators(ctx, resourceType, resourceIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetResourceCreators", reflect.TypeOf((*MockAuditEventSvc)(nil).BatchGetResourceCreators), ctx, resourceType, resourceIDs)
}

// GetAuditEvent mocks base method.
func (m *MockAuditEventSvc) GetAuditEvent(ctx context.Context, id string, includes []string) (*domain.AuditEventRead, *apierror.APIError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuditEvent", ctx, id, includes)
	ret0, _ := ret[0].(*domain.AuditEventRead)
	ret1, _ := ret[1].(*apierror.APIError)
	return ret0, ret1
}

// GetAuditEvent indicates an expected call of GetAuditEvent.
func (mr *MockAuditEventSvcMockRecorder) GetAuditEvent(ctx, id, includes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuditEvent", reflect.TypeOf((*MockAuditEventSvc)(nil).GetAuditEvent), ctx, id, includes)
}

// ListAuditEventResourceTypes mocks base method.
func (m *MockAuditEventSvc) ListAuditEventResourceTypes(ctx context.Context) ([]string, *apierror.APIError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAuditEventResourceTypes", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(*apierror.APIError)
	return ret0, ret1
}

// ListAuditEventResourceTypes indicates an expected call of ListAuditEventResourceTypes.
func (mr *MockAuditEventSvcMockRecorder) ListAuditEventResourceTypes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAuditEventResourceTypes", reflect.TypeOf((*MockAuditEventSvc)(nil).ListAuditEventResourceTypes), ctx)
}

// ListAuditEvents mocks base method.
func (m *MockAuditEventSvc) ListAuditEvents(ctx context.Context, filter *domain.ListAuditEventsFilter, includes []string) (*domain.ListAuditEventsResult, *apierror.APIError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAuditEvents", ctx, filter, includes)
	ret0, _ := ret[0].(*domain.ListAuditEventsResult)
	ret1, _ := ret[1].(*apierror.APIError)
	return ret0, ret1
}

// ListAuditEvents indicates an expected call of ListAuditEvents.
func (mr *MockAuditEventSvcMockRecorder) ListAuditEvents(ctx, filter, includes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAuditEvents", reflect.TypeOf((*MockAuditEventSvc)(nil).ListAuditEvents), ctx, filter, includes)
}

// SaveAuditEvent mocks base method.
func (m *MockAuditEventSvc) SaveAuditEvent(ctx context.Context, event *domain.AuditEvent) *apierror.APIError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAuditEvent", ctx, event)
	ret0, _ := ret[0].(*apierror.APIError)
	return ret0
}

// SaveAuditEvent indicates an expected call of SaveAuditEvent.
func (mr *MockAuditEventSvcMockRecorder) SaveAuditEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAuditEvent", reflect.TypeOf((*MockAuditEventSvc)(nil).SaveAuditEvent), ctx, event)
}
