// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.2
// source: core/core_production_schedule.proto

// Package core defines additional gRPC services for the core-service.
// CoreProductionScheduleService exposes the production scheduling solver.

package core

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoreProductionScheduleService_PreviewProductionSchedule_FullMethodName               = "/core.CoreProductionScheduleService/PreviewProductionSchedule"
	CoreProductionScheduleService_GenerateProductionSchedule_FullMethodName              = "/core.CoreProductionScheduleService/GenerateProductionSchedule"
	CoreProductionScheduleService_PreviewRegenerateProductionSchedule_FullMethodName     = "/core.CoreProductionScheduleService/PreviewRegenerateProductionSchedule"
	CoreProductionScheduleService_RegenerateProductionSchedule_FullMethodName            = "/core.CoreProductionScheduleService/RegenerateProductionSchedule"
	CoreProductionScheduleService_GetProductionSchedule_FullMethodName                   = "/core.CoreProductionScheduleService/GetProductionSchedule"
	CoreProductionScheduleService_GetCurrentProductionSchedule_FullMethodName            = "/core.CoreProductionScheduleService/GetCurrentProductionSchedule"
	CoreProductionScheduleService_ListProductionSchedules_FullMethodName                 = "/core.CoreProductionScheduleService/ListProductionSchedules"
	CoreProductionScheduleService_ListProductionScheduleLines_FullMethodName             = "/core.CoreProductionScheduleService/ListProductionScheduleLines"
	CoreProductionScheduleService_ListProductionScheduleItemPolicies_FullMethodName      = "/core.CoreProductionScheduleService/ListProductionScheduleItemPolicies"
	CoreProductionScheduleService_ListProductionScheduleFinishedPolicies_FullMethodName  = "/core.CoreProductionScheduleService/ListProductionScheduleFinishedPolicies"
	CoreProductionScheduleService_GetProductionScheduleSettings_FullMethodName           = "/core.CoreProductionScheduleService/GetProductionScheduleSettings"
	CoreProductionScheduleService_UpdateProductionScheduleSettings_FullMethodName        = "/core.CoreProductionScheduleService/UpdateProductionScheduleSettings"
	CoreProductionScheduleService_ListProductionScheduleResourceSettings_FullMethodName  = "/core.CoreProductionScheduleService/ListProductionScheduleResourceSettings"
	CoreProductionScheduleService_UpsertProductionScheduleResourceSetting_FullMethodName = "/core.CoreProductionScheduleService/UpsertProductionScheduleResourceSetting"
	CoreProductionScheduleService_DeleteProductionScheduleResourceSetting_FullMethodName = "/core.CoreProductionScheduleService/DeleteProductionScheduleResourceSetting"
	CoreProductionScheduleService_ListProductionScheduleDerivedLines_FullMethodName      = "/core.CoreProductionScheduleService/ListProductionScheduleDerivedLines"
	CoreProductionScheduleService_ListScheduleDeviationTypes_FullMethodName              = "/core.CoreProductionScheduleService/ListScheduleDeviationTypes"
	CoreProductionScheduleService_ListProductionScheduleDeviations_FullMethodName        = "/core.CoreProductionScheduleService/ListProductionScheduleDeviations"
	CoreProductionScheduleService_CreateProductionScheduleLine_FullMethodName            = "/core.CoreProductionScheduleService/CreateProductionScheduleLine"
	CoreProductionScheduleService_UpdateProductionScheduleLine_FullMethodName            = "/core.CoreProductionScheduleService/UpdateProductionScheduleLine"
	CoreProductionScheduleService_DeleteProductionScheduleLine_FullMethodName            = "/core.CoreProductionScheduleService/DeleteProductionScheduleLine"
	CoreProductionScheduleService_PublishProductionSchedule_FullMethodName               = "/core.CoreProductionScheduleService/PublishProductionSchedule"
	CoreProductionScheduleService_ReleaseProductionScheduleWeek_FullMethodName           = "/core.CoreProductionScheduleService/ReleaseProductionScheduleWeek"
	CoreProductionScheduleService_PreviewReleaseProductionScheduleWeek_FullMethodName    = "/core.CoreProductionScheduleService/PreviewReleaseProductionScheduleWeek"
	CoreProductionScheduleService_ArchiveProductionSchedule_FullMethodName               = "/core.CoreProductionScheduleService/ArchiveProductionSchedule"
	CoreProductionScheduleService_DeleteProductionSchedule_FullMethodName                = "/core.CoreProductionScheduleService/DeleteProductionSchedule"
)

// CoreProductionScheduleServiceClient is the client API for CoreProductionScheduleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoreProductionScheduleServiceClient interface {
	// PreviewProductionSchedule runs the solver and returns the plan without persisting it.
	PreviewProductionSchedule(ctx context.Context, in *PreviewProductionScheduleRequest, opts ...grpc.CallOption) (*PreviewProductionScheduleResponse, error)
	// GenerateProductionSchedule solves and persists a new draft version.
	GenerateProductionSchedule(ctx context.Context, in *GenerateProductionScheduleRequest, opts ...grpc.CallOption) (*GenerateProductionScheduleResponse, error)
	// PreviewRegenerateProductionSchedule says what a re-solve would change about a draft,
	// without changing it.
	PreviewRegenerateProductionSchedule(ctx context.Context, in *RegenerateProductionScheduleRequest, opts ...grpc.CallOption) (*PreviewRegenerateProductionScheduleResponse, error)
	// RegenerateProductionSchedule re-solves a draft in place, keeping its version number.
	RegenerateProductionSchedule(ctx context.Context, in *RegenerateProductionScheduleRequest, opts ...grpc.CallOption) (*RegenerateProductionScheduleResponse, error)
	// GetProductionSchedule returns one version by ID.
	GetProductionSchedule(ctx context.Context, in *GetProductionScheduleRequest, opts ...grpc.CallOption) (*GetProductionScheduleResponse, error)
	// GetCurrentProductionSchedule returns the published version covering today.
	GetCurrentProductionSchedule(ctx context.Context, in *GetCurrentProductionScheduleRequest, opts ...grpc.CallOption) (*GetProductionScheduleResponse, error)
	// ListProductionSchedules returns a paginated list of versions.
	ListProductionSchedules(ctx context.Context, in *ListProductionSchedulesRequest, opts ...grpc.CallOption) (*ListProductionSchedulesResponse, error)
	// ListProductionScheduleLines returns the planned campaigns for a version.
	ListProductionScheduleLines(ctx context.Context, in *ListProductionScheduleLinesRequest, opts ...grpc.CallOption) (*ListProductionScheduleLinesResponse, error)
	// ListProductionScheduleItemPolicies returns the per-item policy snapshot for a version.
	ListProductionScheduleItemPolicies(ctx context.Context, in *ListProductionScheduleItemPoliciesRequest, opts ...grpc.CallOption) (*ListProductionScheduleItemPoliciesResponse, error)
	// ListProductionScheduleFinishedPolicies returns the per-finished-SKU decomposition of
	// the pooled constraint buffers.
	ListProductionScheduleFinishedPolicies(ctx context.Context, in *ListProductionScheduleFinishedPoliciesRequest, opts ...grpc.CallOption) (*ListProductionScheduleFinishedPoliciesResponse, error)
	// GetProductionScheduleSettings returns the merchant's planning assumptions.
	GetProductionScheduleSettings(ctx context.Context, in *GetProductionScheduleSettingsRequest, opts ...grpc.CallOption) (*GetProductionScheduleSettingsResponse, error)
	// UpdateProductionScheduleSettings replaces the merchant's planning assumptions.
	UpdateProductionScheduleSettings(ctx context.Context, in *UpdateProductionScheduleSettingsRequest, opts ...grpc.CallOption) (*GetProductionScheduleSettingsResponse, error)
	// ListProductionScheduleResourceSettings returns per-resource overrides.
	ListProductionScheduleResourceSettings(ctx context.Context, in *ListProductionScheduleResourceSettingsRequest, opts ...grpc.CallOption) (*ListProductionScheduleResourceSettingsResponse, error)
	// UpsertProductionScheduleResourceSetting writes one per-resource override.
	UpsertProductionScheduleResourceSetting(ctx context.Context, in *UpsertProductionScheduleResourceSettingRequest, opts ...grpc.CallOption) (*UpsertProductionScheduleResourceSettingResponse, error)
	// DeleteProductionScheduleResourceSetting removes one per-resource override.
	DeleteProductionScheduleResourceSetting(ctx context.Context, in *DeleteProductionScheduleResourceSettingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListProductionScheduleDerivedLines returns derived downstream department work.
	ListProductionScheduleDerivedLines(ctx context.Context, in *ListProductionScheduleDerivedLinesRequest, opts ...grpc.CallOption) (*ListProductionScheduleDerivedLinesResponse, error)
	// ListScheduleDeviationTypes returns the global deviation taxonomy.
	ListScheduleDeviationTypes(ctx context.Context, in *ListScheduleDeviationTypesRequest, opts ...grpc.CallOption) (*ListScheduleDeviationTypesResponse, error)
	// ListProductionScheduleDeviations returns the append-only log of hand changes.
	ListProductionScheduleDeviations(ctx context.Context, in *ListProductionScheduleDeviationsRequest, opts ...grpc.CallOption) (*ListProductionScheduleDeviationsResponse, error)
	// CreateProductionScheduleLine adds a campaign by hand.
	CreateProductionScheduleLine(ctx context.Context, in *CreateProductionScheduleLineRequest, opts ...grpc.CallOption) (*CreateProductionScheduleLineResponse, error)
	// UpdateProductionScheduleLine edits a campaign.
	UpdateProductionScheduleLine(ctx context.Context, in *UpdateProductionScheduleLineRequest, opts ...grpc.CallOption) (*UpdateProductionScheduleLineResponse, error)
	// DeleteProductionScheduleLine removes a campaign.
	DeleteProductionScheduleLine(ctx context.Context, in *DeleteProductionScheduleLineRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// PublishProductionSchedule freezes the first weeks and supersedes what it replaces.
	PublishProductionSchedule(ctx context.Context, in *PublishProductionScheduleRequest, opts ...grpc.CallOption) (*PublishProductionScheduleResponse, error)
	// ReleaseProductionScheduleWeek turns one planned week into a production run.
	ReleaseProductionScheduleWeek(ctx context.Context, in *ReleaseProductionScheduleWeekRequest, opts ...grpc.CallOption) (*ReleaseProductionScheduleWeekResponse, error)
	// PreviewReleaseProductionScheduleWeek says what releasing a week would create.
	PreviewReleaseProductionScheduleWeek(ctx context.Context, in *PreviewReleaseProductionScheduleWeekRequest, opts ...grpc.CallOption) (*ReleaseProductionScheduleWeekPreviewResponse, error)
	// ArchiveProductionSchedule retires a version.
	ArchiveProductionSchedule(ctx context.Context, in *ArchiveProductionScheduleRequest, opts ...grpc.CallOption) (*ArchiveProductionScheduleResponse, error)
	// DeleteProductionSchedule removes a draft version.
	DeleteProductionSchedule(ctx context.Context, in *DeleteProductionScheduleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type coreProductionScheduleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreProductionScheduleServiceClient(cc grpc.ClientConnInterface) CoreProductionScheduleServiceClient {
	return &coreProductionScheduleServiceClient{cc}
}

func (c *coreProductionScheduleServiceClient) PreviewProductionSchedule(ctx context.Context, in *PreviewProductionScheduleRequest, opts ...grpc.CallOption) (*PreviewProductionScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreviewProductionScheduleResponse)
	err := c.cc.Invoke(ctx, CoreProductionScheduleService_PreviewProductionSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreProductionScheduleServiceClient) GenerateProductionSchedule(ctx context.Context, in *GenerateProductionScheduleRequest, opts ...grpc.CallOption) (*GenerateProductionScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateProductionScheduleResponse)
	err := c.cc.Invoke(ctx, CoreProductionScheduleService_GenerateProductionSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreProductionScheduleServiceClient) PreviewRegenerateProductionSchedule(ctx context.Context, in *RegenerateProductionScheduleRequest, opts ...grpc.CallOption) (*PreviewRegenerateProductionScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreviewRegenerateProductionScheduleResponse)
	err := c.cc.Invoke(ctx, CoreProductionScheduleService_PreviewRegenerateProductionSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreProductionScheduleServiceClient) RegenerateProductionSchedule(ctx context.Context, in *RegenerateProductionScheduleRequest, opts ...grpc.CallOption) (*RegenerateProductionScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegenerateProductionScheduleResponse)
	err := c.cc.Invoke(ctx, CoreProductionScheduleService_RegenerateProductionSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreProductionScheduleServiceClient) GetProductionSchedule(ctx context.Context, in *GetProductionScheduleRequest, opts ...grpc.CallOption) (*GetProductionScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductionScheduleResponse)
	err := c.cc.Invoke(ctx, CoreProductionScheduleService_GetProductionSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreProductionScheduleServiceClient) GetCurrentProductionSchedule(ctx context.Context, in *GetCurrentProductionScheduleRequest, opts ...grpc.CallOption) (*GetProductionScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductionScheduleResponse)
	err := c.cc.Invoke(ctx, CoreProductionScheduleService_GetCurrentProductionSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreProductionScheduleServiceClient) ListProductionSchedules(ctx context.Context, in *ListProductionSchedulesRequest, opts ...grpc.CallOption) (*ListProductionSchedulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductionSchedulesResponse)
	err := c.cc.Invoke(ctx, CoreProductionScheduleService_ListProductionSchedules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreProductionScheduleServiceClient) ListProductionScheduleLines(ctx context.Context, in *ListProductionScheduleLinesRequest, opts ...grpc.CallOption) (*ListProductionScheduleLinesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductionScheduleLinesResponse)
	err := c.cc.Invoke(ctx, CoreProductionScheduleService_ListProductionScheduleLines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreProductionScheduleServiceClient) ListProductionScheduleItemPolicies(ctx context.Context, in *ListProductionScheduleItemPoliciesRequest, opts ...grpc.CallOption) (*ListProductionScheduleItemPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductionScheduleItemPoliciesResponse)
	err := c.cc.Invoke(ctx, CoreProductionScheduleService_ListProductionScheduleItemPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreProductionScheduleServiceClient) ListProductionScheduleFinishedPolicies(ctx context.Context, in *ListProductionScheduleFinishedPoliciesRequest, opts ...grpc.CallOption) (*ListProductionScheduleFinishedPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductionScheduleFinishedPoliciesResponse)
	err := c.cc.Invoke(ctx, CoreProductionScheduleService_ListProductionScheduleFinishedPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreProductionScheduleServiceClient) GetProductionScheduleSettings(ctx context.Context, in *GetProductionScheduleSettingsRequest, opts ...grpc.CallOption) (*GetProductionScheduleSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductionScheduleSettingsResponse)
	err := c.cc.Invoke(ctx, CoreProductionScheduleService_GetProductionScheduleSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreProductionScheduleServiceClient) UpdateProductionScheduleSettings(ctx context.Context, in *UpdateProductionScheduleSettingsRequest, opts ...grpc.CallOption) (*GetProductionScheduleSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductionScheduleSettingsResponse)
	err := c.cc.Invoke(ctx, CoreProductionScheduleService_UpdateProductionScheduleSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreProductionScheduleServiceClient) ListProductionScheduleResourceSettings(ctx context.Context, in *ListProductionScheduleResourceSettingsRequest, opts ...grpc.CallOption) (*ListProductionScheduleResourceSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductionScheduleResourceSettingsResponse)
	err := c.cc.Invoke(ctx, CoreProductionScheduleService_ListProductionScheduleResourceSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreProductionScheduleServiceClient) UpsertProductionScheduleResourceSetting(ctx context.Context, in *UpsertProductionScheduleResourceSettingRequest, opts ...grpc.CallOption) (*UpsertProductionScheduleResourceSettingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertProductionScheduleResourceSettingResponse)
	err := c.cc.Invoke(ctx, CoreProductionScheduleService_UpsertProductionScheduleResourceSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreProductionScheduleServiceClient) DeleteProductionScheduleResourceSetting(ctx context.Context, in *DeleteProductionScheduleResourceSettingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CoreProductionScheduleService_DeleteProductionScheduleResourceSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreProductionScheduleServiceClient) ListProductionScheduleDerivedLines(ctx context.Context, in *ListProductionScheduleDerivedLinesRequest, opts ...grpc.CallOption) (*ListProductionScheduleDerivedLinesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductionScheduleDerivedLinesResponse)
	err := c.cc.Invoke(ctx, CoreProductionScheduleService_ListProductionScheduleDerivedLines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreProductionScheduleServiceClient) ListScheduleDeviationTypes(ctx context.Context, in *ListScheduleDeviationTypesRequest, opts ...grpc.CallOption) (*ListScheduleDeviationTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListScheduleDeviationTypesResponse)
	err := c.cc.Invoke(ctx, CoreProductionScheduleService_ListScheduleDeviationTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreProductionScheduleServiceClient) ListProductionScheduleDeviations(ctx context.Context, in *ListProductionScheduleDeviationsRequest, opts ...grpc.CallOption) (*ListProductionScheduleDeviationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductionScheduleDeviationsResponse)
	err := c.cc.Invoke(ctx, CoreProductionScheduleService_ListProductionScheduleDeviations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreProductionScheduleServiceClient) CreateProductionScheduleLine(ctx context.Context, in *CreateProductionScheduleLineRequest, opts ...grpc.CallOption) (*CreateProductionScheduleLineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProductionScheduleLineResponse)
	err := c.cc.Invoke(ctx, CoreProductionScheduleService_CreateProductionScheduleLine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreProductionScheduleServiceClient) UpdateProductionScheduleLine(ctx context.Context, in *UpdateProductionScheduleLineRequest, opts ...grpc.CallOption) (*UpdateProductionScheduleLineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProductionScheduleLineResponse)
	err := c.cc.Invoke(ctx, CoreProductionScheduleService_UpdateProductionScheduleLine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreProductionScheduleServiceClient) DeleteProductionScheduleLine(ctx context.Context, in *DeleteProductionScheduleLineRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CoreProductionScheduleService_DeleteProductionScheduleLine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreProductionScheduleServiceClient) PublishProductionSchedule(ctx context.Context, in *PublishProductionScheduleRequest, opts ...grpc.CallOption) (*PublishProductionScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishProductionScheduleResponse)
	err := c.cc.Invoke(ctx, CoreProductionScheduleService_PublishProductionSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreProductionScheduleServiceClient) ReleaseProductionScheduleWeek(ctx context.Context, in *ReleaseProductionScheduleWeekRequest, opts ...grpc.CallOption) (*ReleaseProductionScheduleWeekResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseProductionScheduleWeekResponse)
	err := c.cc.Invoke(ctx, CoreProductionScheduleService_ReleaseProductionScheduleWeek_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreProductionScheduleServiceClient) PreviewReleaseProductionScheduleWeek(ctx context.Context, in *PreviewReleaseProductionScheduleWeekRequest, opts ...grpc.CallOption) (*ReleaseProductionScheduleWeekPreviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseProductionScheduleWeekPreviewResponse)
	err := c.cc.Invoke(ctx, CoreProductionScheduleService_PreviewReleaseProductionScheduleWeek_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreProductionScheduleServiceClient) ArchiveProductionSchedule(ctx context.Context, in *ArchiveProductionScheduleRequest, opts ...grpc.CallOption) (*ArchiveProductionScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArchiveProductionScheduleResponse)
	err := c.cc.Invoke(ctx, CoreProductionScheduleService_ArchiveProductionSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreProductionScheduleServiceClient) DeleteProductionSchedule(ctx context.Context, in *DeleteProductionScheduleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CoreProductionScheduleService_DeleteProductionSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreProductionScheduleServiceServer is the server API for CoreProductionScheduleService service.
// All implementations must embed UnimplementedCoreProductionScheduleServiceServer
// for forward compatibility.
type CoreProductionScheduleServiceServer interface {
	// PreviewProductionSchedule runs the solver and returns the plan without persisting it.
	PreviewProductionSchedule(context.Context, *PreviewProductionScheduleRequest) (*PreviewProductionScheduleResponse, error)
	// GenerateProductionSchedule solves and persists a new draft version.
	GenerateProductionSchedule(context.Context, *GenerateProductionScheduleRequest) (*GenerateProductionScheduleResponse, error)
	// PreviewRegenerateProductionSchedule says what a re-solve would change about a draft,
	// without changing it.
	PreviewRegenerateProductionSchedule(context.Context, *RegenerateProductionScheduleRequest) (*PreviewRegenerateProductionScheduleResponse, error)
	// RegenerateProductionSchedule re-solves a draft in place, keeping its version number.
	RegenerateProductionSchedule(context.Context, *RegenerateProductionScheduleRequest) (*RegenerateProductionScheduleResponse, error)
	// GetProductionSchedule returns one version by ID.
	GetProductionSchedule(context.Context, *GetProductionScheduleRequest) (*GetProductionScheduleResponse, error)
	// GetCurrentProductionSchedule returns the published version covering today.
	GetCurrentProductionSchedule(context.Context, *GetCurrentProductionScheduleRequest) (*GetProductionScheduleResponse, error)
	// ListProductionSchedules returns a paginated list of versions.
	ListProductionSchedules(context.Context, *ListProductionSchedulesRequest) (*ListProductionSchedulesResponse, error)
	// ListProductionScheduleLines returns the planned campaigns for a version.
	ListProductionScheduleLines(context.Context, *ListProductionScheduleLinesRequest) (*ListProductionScheduleLinesResponse, error)
	// ListProductionScheduleItemPolicies returns the per-item policy snapshot for a version.
	ListProductionScheduleItemPolicies(context.Context, *ListProductionScheduleItemPoliciesRequest) (*ListProductionScheduleItemPoliciesResponse, error)
	// ListProductionScheduleFinishedPolicies returns the per-finished-SKU decomposition of
	// the pooled constraint buffers.
	ListProductionScheduleFinishedPolicies(context.Context, *ListProductionScheduleFinishedPoliciesRequest) (*ListProductionScheduleFinishedPoliciesResponse, error)
	// GetProductionScheduleSettings returns the merchant's planning assumptions.
	GetProductionScheduleSettings(context.Context, *GetProductionScheduleSettingsRequest) (*GetProductionScheduleSettingsResponse, error)
	// UpdateProductionScheduleSettings replaces the merchant's planning assumptions.
	UpdateProductionScheduleSettings(context.Context, *UpdateProductionScheduleSettingsRequest) (*GetProductionScheduleSettingsResponse, error)
	// ListProductionScheduleResourceSettings returns per-resource overrides.
	ListProductionScheduleResourceSettings(context.Context, *ListProductionScheduleResourceSettingsRequest) (*ListProductionScheduleResourceSettingsResponse, error)
	// UpsertProductionScheduleResourceSetting writes one per-resource override.
	UpsertProductionScheduleResourceSetting(context.Context, *UpsertProductionScheduleResourceSettingRequest) (*UpsertProductionScheduleResourceSettingResponse, error)
	// DeleteProductionScheduleResourceSetting removes one per-resource override.
	DeleteProductionScheduleResourceSetting(context.Context, *DeleteProductionScheduleResourceSettingRequest) (*emptypb.Empty, error)
	// ListProductionScheduleDerivedLines returns derived downstream department work.
	ListProductionScheduleDerivedLines(context.Context, *ListProductionScheduleDerivedLinesRequest) (*ListProductionScheduleDerivedLinesResponse, error)
	// ListScheduleDeviationTypes returns the global deviation taxonomy.
	ListScheduleDeviationTypes(context.Context, *ListScheduleDeviationTypesRequest) (*ListScheduleDeviationTypesResponse, error)
	// ListProductionScheduleDeviations returns the append-only log of hand changes.
	ListProductionScheduleDeviations(context.Context, *ListProductionScheduleDeviationsRequest) (*ListProductionScheduleDeviationsResponse, error)
	// CreateProductionScheduleLine adds a campaign by hand.
	CreateProductionScheduleLine(context.Context, *CreateProductionScheduleLineRequest) (*CreateProductionScheduleLineResponse, error)
	// UpdateProductionScheduleLine edits a campaign.
	UpdateProductionScheduleLine(context.Context, *UpdateProductionScheduleLineRequest) (*UpdateProductionScheduleLineResponse, error)
	// DeleteProductionScheduleLine removes a campaign.
	DeleteProductionScheduleLine(context.Context, *DeleteProductionScheduleLineRequest) (*emptypb.Empty, error)
	// PublishProductionSchedule freezes the first weeks and supersedes what it replaces.
	PublishProductionSchedule(context.Context, *PublishProductionScheduleRequest) (*PublishProductionScheduleResponse, error)
	// ReleaseProductionScheduleWeek turns one planned week into a production run.
	ReleaseProductionScheduleWeek(context.Context, *ReleaseProductionScheduleWeekRequest) (*ReleaseProductionScheduleWeekResponse, error)
	// PreviewReleaseProductionScheduleWeek says what releasing a week would create.
	PreviewReleaseProductionScheduleWeek(context.Context, *PreviewReleaseProductionScheduleWeekRequest) (*ReleaseProductionScheduleWeekPreviewResponse, error)
	// ArchiveProductionSchedule retires a version.
	ArchiveProductionSchedule(context.Context, *ArchiveProductionScheduleRequest) (*ArchiveProductionScheduleResponse, error)
	// DeleteProductionSchedule removes a draft version.
	DeleteProductionSchedule(context.Context, *DeleteProductionScheduleRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedCoreProductionScheduleServiceServer()
}

// UnimplementedCoreProductionScheduleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreProductionScheduleServiceServer struct{}

func (UnimplementedCoreProductionScheduleServiceServer) PreviewProductionSchedule(context.Context, *PreviewProductionScheduleRequest) (*PreviewProductionScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PreviewProductionSchedule not implemented")
}
func (UnimplementedCoreProductionScheduleServiceServer) GenerateProductionSchedule(context.Context, *GenerateProductionScheduleRequest) (*GenerateProductionScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateProductionSchedule not implemented")
}
func (UnimplementedCoreProductionScheduleServiceServer) PreviewRegenerateProductionSchedule(context.Context, *RegenerateProductionScheduleRequest) (*PreviewRegenerateProductionScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PreviewRegenerateProductionSchedule not implemented")
}
func (UnimplementedCoreProductionScheduleServiceServer) RegenerateProductionSchedule(context.Context, *RegenerateProductionScheduleRequest) (*RegenerateProductionScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegenerateProductionSchedule not implemented")
}
func (UnimplementedCoreProductionScheduleServiceServer) GetProductionSchedule(context.Context, *GetProductionScheduleRequest) (*GetProductionScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductionSchedule not implemented")
}
func (UnimplementedCoreProductionScheduleServiceServer) GetCurrentProductionSchedule(context.Context, *GetCurrentProductionScheduleRequest) (*GetProductionScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentProductionSchedule not implemented")
}
func (UnimplementedCoreProductionScheduleServiceServer) ListProductionSchedules(context.Context, *ListProductionSchedulesRequest) (*ListProductionSchedulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProductionSchedules not implemented")
}
func (UnimplementedCoreProductionScheduleServiceServer) ListProductionScheduleLines(context.Context, *ListProductionScheduleLinesRequest) (*ListProductionScheduleLinesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProductionScheduleLines not implemented")
}
func (UnimplementedCoreProductionScheduleServiceServer) ListProductionScheduleItemPolicies(context.Context, *ListProductionScheduleItemPoliciesRequest) (*ListProductionScheduleItemPoliciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProductionScheduleItemPolicies not implemented")
}
func (UnimplementedCoreProductionScheduleServiceServer) ListProductionScheduleFinishedPolicies(context.Context, *ListProductionScheduleFinishedPoliciesRequest) (*ListProductionScheduleFinishedPoliciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProductionScheduleFinishedPolicies not implemented")
}
func (UnimplementedCoreProductionScheduleServiceServer) GetProductionScheduleSettings(context.Context, *GetProductionScheduleSettingsRequest) (*GetProductionScheduleSettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductionScheduleSettings not implemented")
}
func (UnimplementedCoreProductionScheduleServiceServer) UpdateProductionScheduleSettings(context.Context, *UpdateProductionScheduleSettingsRequest) (*GetProductionScheduleSettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProductionScheduleSettings not implemented")
}
func (UnimplementedCoreProductionScheduleServiceServer) ListProductionScheduleResourceSettings(context.Context, *ListProductionScheduleResourceSettingsRequest) (*ListProductionScheduleResourceSettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProductionScheduleResourceSettings not implemented")
}
func (UnimplementedCoreProductionScheduleServiceServer) UpsertProductionScheduleResourceSetting(context.Context, *UpsertProductionScheduleResourceSettingRequest) (*UpsertProductionScheduleResourceSettingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertProductionScheduleResourceSetting not implemented")
}
func (UnimplementedCoreProductionScheduleServiceServer) DeleteProductionScheduleResourceSetting(context.Context, *DeleteProductionScheduleResourceSettingRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProductionScheduleResourceSetting not implemented")
}
func (UnimplementedCoreProductionScheduleServiceServer) ListProductionScheduleDerivedLines(context.Context, *ListProductionScheduleDerivedLinesRequest) (*ListProductionScheduleDerivedLinesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProductionScheduleDerivedLines not implemented")
}
func (UnimplementedCoreProductionScheduleServiceServer) ListScheduleDeviationTypes(context.Context, *ListScheduleDeviationTypesRequest) (*ListScheduleDeviationTypesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListScheduleDeviationTypes not implemented")
}
func (UnimplementedCoreProductionScheduleServiceServer) ListProductionScheduleDeviations(context.Context, *ListProductionScheduleDeviationsRequest) (*ListProductionScheduleDeviationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProductionScheduleDeviations not implemented")
}
func (UnimplementedCoreProductionScheduleServiceServer) CreateProductionScheduleLine(context.Context, *CreateProductionScheduleLineRequest) (*CreateProductionScheduleLineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProductionScheduleLine not implemented")
}
func (UnimplementedCoreProductionScheduleServiceServer) UpdateProductionScheduleLine(context.Context, *UpdateProductionScheduleLineRequest) (*UpdateProductionScheduleLineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProductionScheduleLine not implemented")
}
func (UnimplementedCoreProductionScheduleServiceServer) DeleteProductionScheduleLine(context.Context, *DeleteProductionScheduleLineRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProductionScheduleLine not implemented")
}
func (UnimplementedCoreProductionScheduleServiceServer) PublishProductionSchedule(context.Context, *PublishProductionScheduleRequest) (*PublishProductionScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishProductionSchedule not implemented")
}
func (UnimplementedCoreProductionScheduleServiceServer) ReleaseProductionScheduleWeek(context.Context, *ReleaseProductionScheduleWeekRequest) (*ReleaseProductionScheduleWeekResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseProductionScheduleWeek not implemented")
}
func (UnimplementedCoreProductionScheduleServiceServer) PreviewReleaseProductionScheduleWeek(context.Context, *PreviewReleaseProductionScheduleWeekRequest) (*ReleaseProductionScheduleWeekPreviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PreviewReleaseProductionScheduleWeek not implemented")
}
func (UnimplementedCoreProductionScheduleServiceServer) ArchiveProductionSchedule(context.Context, *ArchiveProductionScheduleRequest) (*ArchiveProductionScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ArchiveProductionSchedule not implemented")
}
func (UnimplementedCoreProductionScheduleServiceServer) DeleteProductionSchedule(context.Context, *DeleteProductionScheduleRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProductionSchedule not implemented")
}
func (UnimplementedCoreProductionScheduleServiceServer) mustEmbedUnimplementedCoreProductionScheduleServiceServer() {
}
func (UnimplementedCoreProductionScheduleServiceServer) testEmbeddedByValue() {}

// UnsafeCoreProductionScheduleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreProductionScheduleServiceServer will
// result in compilation errors.
type UnsafeCoreProductionScheduleServiceServer interface {
	mustEmbedUnimplementedCoreProductionScheduleServiceServer()
}

func RegisterCoreProductionScheduleServiceServer(s grpc.ServiceRegistrar, srv CoreProductionScheduleServiceServer) {
	// If the following call panics, it indicates UnimplementedCoreProductionScheduleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreProductionScheduleService_ServiceDesc, srv)
}

func _CoreProductionScheduleService_PreviewProductionSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreviewProductionScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreProductionScheduleServiceServer).PreviewProductionSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreProductionScheduleService_PreviewProductionSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreProductionScheduleServiceServer).PreviewProductionSchedule(ctx, req.(*PreviewProductionScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreProductionScheduleService_GenerateProductionSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateProductionScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreProductionScheduleServiceServer).GenerateProductionSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreProductionScheduleService_GenerateProductionSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreProductionScheduleServiceServer).GenerateProductionSchedule(ctx, req.(*GenerateProductionScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreProductionScheduleService_PreviewRegenerateProductionSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegenerateProductionScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreProductionScheduleServiceServer).PreviewRegenerateProductionSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreProductionScheduleService_PreviewRegenerateProductionSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreProductionScheduleServiceServer).PreviewRegenerateProductionSchedule(ctx, req.(*RegenerateProductionScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreProductionScheduleService_RegenerateProductionSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegenerateProductionScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreProductionScheduleServiceServer).RegenerateProductionSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreProductionScheduleService_RegenerateProductionSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreProductionScheduleServiceServer).RegenerateProductionSchedule(ctx, req.(*RegenerateProductionScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreProductionScheduleService_GetProductionSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductionScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreProductionScheduleServiceServer).GetProductionSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreProductionScheduleService_GetProductionSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreProductionScheduleServiceServer).GetProductionSchedule(ctx, req.(*GetProductionScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreProductionScheduleService_GetCurrentProductionSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentProductionScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreProductionScheduleServiceServer).GetCurrentProductionSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreProductionScheduleService_GetCurrentProductionSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreProductionScheduleServiceServer).GetCurrentProductionSchedule(ctx, req.(*GetCurrentProductionScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreProductionScheduleService_ListProductionSchedules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductionSchedulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreProductionScheduleServiceServer).ListProductionSchedules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreProductionScheduleService_ListProductionSchedules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreProductionScheduleServiceServer).ListProductionSchedules(ctx, req.(*ListProductionSchedulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreProductionScheduleService_ListProductionScheduleLines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductionScheduleLinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreProductionScheduleServiceServer).ListProductionScheduleLines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreProductionScheduleService_ListProductionScheduleLines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreProductionScheduleServiceServer).ListProductionScheduleLines(ctx, req.(*ListProductionScheduleLinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreProductionScheduleService_ListProductionScheduleItemPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductionScheduleItemPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreProductionScheduleServiceServer).ListProductionScheduleItemPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreProductionScheduleService_ListProductionScheduleItemPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreProductionScheduleServiceServer).ListProductionScheduleItemPolicies(ctx, req.(*ListProductionScheduleItemPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreProductionScheduleService_ListProductionScheduleFinishedPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductionScheduleFinishedPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreProductionScheduleServiceServer).ListProductionScheduleFinishedPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreProductionScheduleService_ListProductionScheduleFinishedPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreProductionScheduleServiceServer).ListProductionScheduleFinishedPolicies(ctx, req.(*ListProductionScheduleFinishedPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreProductionScheduleService_GetProductionScheduleSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductionScheduleSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreProductionScheduleServiceServer).GetProductionScheduleSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreProductionScheduleService_GetProductionScheduleSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreProductionScheduleServiceServer).GetProductionScheduleSettings(ctx, req.(*GetProductionScheduleSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreProductionScheduleService_UpdateProductionScheduleSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductionScheduleSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreProductionScheduleServiceServer).UpdateProductionScheduleSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreProductionScheduleService_UpdateProductionScheduleSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreProductionScheduleServiceServer).UpdateProductionScheduleSettings(ctx, req.(*UpdateProductionScheduleSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreProductionScheduleService_ListProductionScheduleResourceSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductionScheduleResourceSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreProductionScheduleServiceServer).ListProductionScheduleResourceSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreProductionScheduleService_ListProductionScheduleResourceSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreProductionScheduleServiceServer).ListProductionScheduleResourceSettings(ctx, req.(*ListProductionScheduleResourceSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreProductionScheduleService_UpsertProductionScheduleResourceSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertProductionScheduleResourceSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreProductionScheduleServiceServer).UpsertProductionScheduleResourceSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreProductionScheduleService_UpsertProductionScheduleResourceSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreProductionScheduleServiceServer).UpsertProductionScheduleResourceSetting(ctx, req.(*UpsertProductionScheduleResourceSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreProductionScheduleService_DeleteProductionScheduleResourceSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductionScheduleResourceSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreProductionScheduleServiceServer).DeleteProductionScheduleResourceSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreProductionScheduleService_DeleteProductionScheduleResourceSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreProductionScheduleServiceServer).DeleteProductionScheduleResourceSetting(ctx, req.(*DeleteProductionScheduleResourceSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreProductionScheduleService_ListProductionScheduleDerivedLines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductionScheduleDerivedLinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreProductionScheduleServiceServer).ListProductionScheduleDerivedLines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreProductionScheduleService_ListProductionScheduleDerivedLines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreProductionScheduleServiceServer).ListProductionScheduleDerivedLines(ctx, req.(*ListProductionScheduleDerivedLinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreProductionScheduleService_ListScheduleDeviationTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScheduleDeviationTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreProductionScheduleServiceServer).ListScheduleDeviationTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreProductionScheduleService_ListScheduleDeviationTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreProductionScheduleServiceServer).ListScheduleDeviationTypes(ctx, req.(*ListScheduleDeviationTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreProductionScheduleService_ListProductionScheduleDeviations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductionScheduleDeviationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreProductionScheduleServiceServer).ListProductionScheduleDeviations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreProductionScheduleService_ListProductionScheduleDeviations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreProductionScheduleServiceServer).ListProductionScheduleDeviations(ctx, req.(*ListProductionScheduleDeviationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreProductionScheduleService_CreateProductionScheduleLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductionScheduleLineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreProductionScheduleServiceServer).CreateProductionScheduleLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreProductionScheduleService_CreateProductionScheduleLine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreProductionScheduleServiceServer).CreateProductionScheduleLine(ctx, req.(*CreateProductionScheduleLineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreProductionScheduleService_UpdateProductionScheduleLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductionScheduleLineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreProductionScheduleServiceServer).UpdateProductionScheduleLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreProductionScheduleService_UpdateProductionScheduleLine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreProductionScheduleServiceServer).UpdateProductionScheduleLine(ctx, req.(*UpdateProductionScheduleLineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreProductionScheduleService_DeleteProductionScheduleLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductionScheduleLineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreProductionScheduleServiceServer).DeleteProductionScheduleLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreProductionScheduleService_DeleteProductionScheduleLine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreProductionScheduleServiceServer).DeleteProductionScheduleLine(ctx, req.(*DeleteProductionScheduleLineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreProductionScheduleService_PublishProductionSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishProductionScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreProductionScheduleServiceServer).PublishProductionSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreProductionScheduleService_PublishProductionSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreProductionScheduleServiceServer).PublishProductionSchedule(ctx, req.(*PublishProductionScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreProductionScheduleService_ReleaseProductionScheduleWeek_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseProductionScheduleWeekRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreProductionScheduleServiceServer).ReleaseProductionScheduleWeek(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreProductionScheduleService_ReleaseProductionScheduleWeek_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreProductionScheduleServiceServer).ReleaseProductionScheduleWeek(ctx, req.(*ReleaseProductionScheduleWeekRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreProductionScheduleService_PreviewReleaseProductionScheduleWeek_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreviewReleaseProductionScheduleWeekRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreProductionScheduleServiceServer).PreviewReleaseProductionScheduleWeek(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreProductionScheduleService_PreviewReleaseProductionScheduleWeek_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreProductionScheduleServiceServer).PreviewReleaseProductionScheduleWeek(ctx, req.(*PreviewReleaseProductionScheduleWeekRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreProductionScheduleService_ArchiveProductionSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveProductionScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreProductionScheduleServiceServer).ArchiveProductionSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreProductionScheduleService_ArchiveProductionSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreProductionScheduleServiceServer).ArchiveProductionSchedule(ctx, req.(*ArchiveProductionScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreProductionScheduleService_DeleteProductionSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductionScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreProductionScheduleServiceServer).DeleteProductionSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreProductionScheduleService_DeleteProductionSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreProductionScheduleServiceServer).DeleteProductionSchedule(ctx, req.(*DeleteProductionScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreProductionScheduleService_ServiceDesc is the grpc.ServiceDesc for CoreProductionScheduleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreProductionScheduleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.CoreProductionScheduleService",
	HandlerType: (*CoreProductionScheduleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PreviewProductionSchedule",
			Handler:    _CoreProductionScheduleService_PreviewProductionSchedule_Handler,
		},
		{
			MethodName: "GenerateProductionSchedule",
			Handler:    _CoreProductionScheduleService_GenerateProductionSchedule_Handler,
		},
		{
			MethodName: "PreviewRegenerateProductionSchedule",
			Handler:    _CoreProductionScheduleService_PreviewRegenerateProductionSchedule_Handler,
		},
		{
			MethodName: "RegenerateProductionSchedule",
			Handler:    _CoreProductionScheduleService_RegenerateProductionSchedule_Handler,
		},
		{
			MethodName: "GetProductionSchedule",
			Handler:    _CoreProductionScheduleService_GetProductionSchedule_Handler,
		},
		{
			MethodName: "GetCurrentProductionSchedule",
			Handler:    _CoreProductionScheduleService_GetCurrentProductionSchedule_Handler,
		},
		{
			MethodName: "ListProductionSchedules",
			Handler:    _CoreProductionScheduleService_ListProductionSchedules_Handler,
		},
		{
			MethodName: "ListProductionScheduleLines",
			Handler:    _CoreProductionScheduleService_ListProductionScheduleLines_Handler,
		},
		{
			MethodName: "ListProductionScheduleItemPolicies",
			Handler:    _CoreProductionScheduleService_ListProductionScheduleItemPolicies_Handler,
		},
		{
			MethodName: "ListProductionScheduleFinishedPolicies",
			Handler:    _CoreProductionScheduleService_ListProductionScheduleFinishedPolicies_Handler,
		},
		{
			MethodName: "GetProductionScheduleSettings",
			Handler:    _CoreProductionScheduleService_GetProductionScheduleSettings_Handler,
		},
		{
			MethodName: "UpdateProductionScheduleSettings",
			Handler:    _CoreProductionScheduleService_UpdateProductionScheduleSettings_Handler,
		},
		{
			MethodName: "ListProductionScheduleResourceSettings",
			Handler:    _CoreProductionScheduleService_ListProductionScheduleResourceSettings_Handler,
		},
		{
			MethodName: "UpsertProductionScheduleResourceSetting",
			Handler:    _CoreProductionScheduleService_UpsertProductionScheduleResourceSetting_Handler,
		},
		{
			MethodName: "DeleteProductionScheduleResourceSetting",
			Handler:    _CoreProductionScheduleService_DeleteProductionScheduleResourceSetting_Handler,
		},
		{
			MethodName: "ListProductionScheduleDerivedLines",
			Handler:    _CoreProductionScheduleService_ListProductionScheduleDerivedLines_Handler,
		},
		{
			MethodName: "ListScheduleDeviationTypes",
			Handler:    _CoreProductionScheduleService_ListScheduleDeviationTypes_Handler,
		},
		{
			MethodName: "ListProductionScheduleDeviations",
			Handler:    _CoreProductionScheduleService_ListProductionScheduleDeviations_Handler,
		},
		{
			MethodName: "CreateProductionScheduleLine",
			Handler:    _CoreProductionScheduleService_CreateProductionScheduleLine_Handler,
		},
		{
			MethodName: "UpdateProductionScheduleLine",
			Handler:    _CoreProductionScheduleService_UpdateProductionScheduleLine_Handler,
		},
		{
			MethodName: "DeleteProductionScheduleLine",
			Handler:    _CoreProductionScheduleService_DeleteProductionScheduleLine_Handler,
		},
		{
			MethodName: "PublishProductionSchedule",
			Handler:    _CoreProductionScheduleService_PublishProductionSchedule_Handler,
		},
		{
			MethodName: "ReleaseProductionScheduleWeek",
			Handler:    _CoreProductionScheduleService_ReleaseProductionScheduleWeek_Handler,
		},
		{
			MethodName: "PreviewReleaseProductionScheduleWeek",
			Handler:    _CoreProductionScheduleService_PreviewReleaseProductionScheduleWeek_Handler,
		},
		{
			MethodName: "ArchiveProductionSchedule",
			Handler:    _CoreProductionScheduleService_ArchiveProductionSchedule_Handler,
		},
		{
			MethodName: "DeleteProductionSchedule",
			Handler:    _CoreProductionScheduleService_DeleteProductionSchedule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core/core_production_schedule.proto",
}
