// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: core/core_fulfillment.proto

// Package core defines additional gRPC services for the core-service.
// CoreFulfillmentService handles machine management RPCs.

package core

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MachineInfo represents a machine resource returned by the core-service.
type MachineInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SerialNumber        string                 `protobuf:"bytes,3,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Notes               *string                `protobuf:"bytes,4,opt,name=notes,proto3,oneof" json:"notes,omitempty"`
	DepartmentId        *string                `protobuf:"bytes,5,opt,name=department_id,json=departmentId,proto3,oneof" json:"department_id,omitempty"`
	DepartmentName      *string                `protobuf:"bytes,6,opt,name=department_name,json=departmentName,proto3,oneof" json:"department_name,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DepartmentCreatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=department_created_at,json=departmentCreatedAt,proto3,oneof" json:"department_created_at,omitempty"`
	DepartmentUpdatedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=department_updated_at,json=departmentUpdatedAt,proto3,oneof" json:"department_updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MachineInfo) Reset() {
	*x = MachineInfo{}
	mi := &file_core_core_fulfillment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineInfo) ProtoMessage() {}

func (x *MachineInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_fulfillment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineInfo.ProtoReflect.Descriptor instead.
func (*MachineInfo) Descriptor() ([]byte, []int) {
	return file_core_core_fulfillment_proto_rawDescGZIP(), []int{0}
}

func (x *MachineInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MachineInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MachineInfo) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *MachineInfo) GetNotes() string {
	if x != nil && x.Notes != nil {
		return *x.Notes
	}
	return ""
}

func (x *MachineInfo) GetDepartmentId() string {
	if x != nil && x.DepartmentId != nil {
		return *x.DepartmentId
	}
	return ""
}

func (x *MachineInfo) GetDepartmentName() string {
	if x != nil && x.DepartmentName != nil {
		return *x.DepartmentName
	}
	return ""
}

func (x *MachineInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MachineInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *MachineInfo) GetDepartmentCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DepartmentCreatedAt
	}
	return nil
}

func (x *MachineInfo) GetDepartmentUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DepartmentUpdatedAt
	}
	return nil
}

type ListMachinesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        *string                `protobuf:"bytes,1,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Query         *string                `protobuf:"bytes,3,opt,name=query,proto3,oneof" json:"query,omitempty"`
	Includes      []string               `protobuf:"bytes,4,rep,name=includes,proto3" json:"includes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMachinesRequest) Reset() {
	*x = ListMachinesRequest{}
	mi := &file_core_core_fulfillment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMachinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMachinesRequest) ProtoMessage() {}

func (x *ListMachinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_fulfillment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMachinesRequest.ProtoReflect.Descriptor instead.
func (*ListMachinesRequest) Descriptor() ([]byte, []int) {
	return file_core_core_fulfillment_proto_rawDescGZIP(), []int{1}
}

func (x *ListMachinesRequest) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

func (x *ListMachinesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMachinesRequest) GetQuery() string {
	if x != nil && x.Query != nil {
		return *x.Query
	}
	return ""
}

func (x *ListMachinesRequest) GetIncludes() []string {
	if x != nil {
		return x.Includes
	}
	return nil
}

type ListMachinesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Machines      []*MachineInfo         `protobuf:"bytes,1,rep,name=machines,proto3" json:"machines,omitempty"`
	PageInfo      *PageInfo              `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMachinesResponse) Reset() {
	*x = ListMachinesResponse{}
	mi := &file_core_core_fulfillment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMachinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMachinesResponse) ProtoMessage() {}

func (x *ListMachinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_fulfillment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMachinesResponse.ProtoReflect.Descriptor instead.
func (*ListMachinesResponse) Descriptor() ([]byte, []int) {
	return file_core_core_fulfillment_proto_rawDescGZIP(), []int{2}
}

func (x *ListMachinesResponse) GetMachines() []*MachineInfo {
	if x != nil {
		return x.Machines
	}
	return nil
}

func (x *ListMachinesResponse) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type GetMachineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Includes      []string               `protobuf:"bytes,2,rep,name=includes,proto3" json:"includes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMachineRequest) Reset() {
	*x = GetMachineRequest{}
	mi := &file_core_core_fulfillment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMachineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMachineRequest) ProtoMessage() {}

func (x *GetMachineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_fulfillment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMachineRequest.ProtoReflect.Descriptor instead.
func (*GetMachineRequest) Descriptor() ([]byte, []int) {
	return file_core_core_fulfillment_proto_rawDescGZIP(), []int{3}
}

func (x *GetMachineRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetMachineRequest) GetIncludes() []string {
	if x != nil {
		return x.Includes
	}
	return nil
}

type GetMachineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Machine       *MachineInfo           `protobuf:"bytes,1,opt,name=machine,proto3" json:"machine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMachineResponse) Reset() {
	*x = GetMachineResponse{}
	mi := &file_core_core_fulfillment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMachineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMachineResponse) ProtoMessage() {}

func (x *GetMachineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_fulfillment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMachineResponse.ProtoReflect.Descriptor instead.
func (*GetMachineResponse) Descriptor() ([]byte, []int) {
	return file_core_core_fulfillment_proto_rawDescGZIP(), []int{4}
}

func (x *GetMachineResponse) GetMachine() *MachineInfo {
	if x != nil {
		return x.Machine
	}
	return nil
}

type CreateMachineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SerialNumber  string                 `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Notes         *string                `protobuf:"bytes,3,opt,name=notes,proto3,oneof" json:"notes,omitempty"`
	DepartmentId  string                 `protobuf:"bytes,4,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	Includes      []string               `protobuf:"bytes,5,rep,name=includes,proto3" json:"includes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMachineRequest) Reset() {
	*x = CreateMachineRequest{}
	mi := &file_core_core_fulfillment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMachineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMachineRequest) ProtoMessage() {}

func (x *CreateMachineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_fulfillment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMachineRequest.ProtoReflect.Descriptor instead.
func (*CreateMachineRequest) Descriptor() ([]byte, []int) {
	return file_core_core_fulfillment_proto_rawDescGZIP(), []int{5}
}

func (x *CreateMachineRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMachineRequest) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *CreateMachineRequest) GetNotes() string {
	if x != nil && x.Notes != nil {
		return *x.Notes
	}
	return ""
}

func (x *CreateMachineRequest) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

func (x *CreateMachineRequest) GetIncludes() []string {
	if x != nil {
		return x.Includes
	}
	return nil
}

type CreateMachineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Machine       *MachineInfo           `protobuf:"bytes,1,opt,name=machine,proto3" json:"machine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMachineResponse) Reset() {
	*x = CreateMachineResponse{}
	mi := &file_core_core_fulfillment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMachineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMachineResponse) ProtoMessage() {}

func (x *CreateMachineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_fulfillment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMachineResponse.ProtoReflect.Descriptor instead.
func (*CreateMachineResponse) Descriptor() ([]byte, []int) {
	return file_core_core_fulfillment_proto_rawDescGZIP(), []int{6}
}

func (x *CreateMachineResponse) GetMachine() *MachineInfo {
	if x != nil {
		return x.Machine
	}
	return nil
}

type UpdateMachineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	SerialNumber  *string                `protobuf:"bytes,3,opt,name=serial_number,json=serialNumber,proto3,oneof" json:"serial_number,omitempty"`
	Notes         *string                `protobuf:"bytes,4,opt,name=notes,proto3,oneof" json:"notes,omitempty"`
	Includes      []string               `protobuf:"bytes,5,rep,name=includes,proto3" json:"includes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMachineRequest) Reset() {
	*x = UpdateMachineRequest{}
	mi := &file_core_core_fulfillment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMachineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMachineRequest) ProtoMessage() {}

func (x *UpdateMachineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_fulfillment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMachineRequest.ProtoReflect.Descriptor instead.
func (*UpdateMachineRequest) Descriptor() ([]byte, []int) {
	return file_core_core_fulfillment_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateMachineRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMachineRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateMachineRequest) GetSerialNumber() string {
	if x != nil && x.SerialNumber != nil {
		return *x.SerialNumber
	}
	return ""
}

func (x *UpdateMachineRequest) GetNotes() string {
	if x != nil && x.Notes != nil {
		return *x.Notes
	}
	return ""
}

func (x *UpdateMachineRequest) GetIncludes() []string {
	if x != nil {
		return x.Includes
	}
	return nil
}

type UpdateMachineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Machine       *MachineInfo           `protobuf:"bytes,1,opt,name=machine,proto3" json:"machine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMachineResponse) Reset() {
	*x = UpdateMachineResponse{}
	mi := &file_core_core_fulfillment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMachineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMachineResponse) ProtoMessage() {}

func (x *UpdateMachineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_fulfillment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMachineResponse.ProtoReflect.Descriptor instead.
func (*UpdateMachineResponse) Descriptor() ([]byte, []int) {
	return file_core_core_fulfillment_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateMachineResponse) GetMachine() *MachineInfo {
	if x != nil {
		return x.Machine
	}
	return nil
}

type DeleteMachineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMachineRequest) Reset() {
	*x = DeleteMachineRequest{}
	mi := &file_core_core_fulfillment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMachineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMachineRequest) ProtoMessage() {}

func (x *DeleteMachineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_fulfillment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMachineRequest.ProtoReflect.Descriptor instead.
func (*DeleteMachineRequest) Descriptor() ([]byte, []int) {
	return file_core_core_fulfillment_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteMachineRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BatchGetMachinesByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetMachinesByIDsRequest) Reset() {
	*x = BatchGetMachinesByIDsRequest{}
	mi := &file_core_core_fulfillment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetMachinesByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetMachinesByIDsRequest) ProtoMessage() {}

func (x *BatchGetMachinesByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_fulfillment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetMachinesByIDsRequest.ProtoReflect.Descriptor instead.
func (*BatchGetMachinesByIDsRequest) Descriptor() ([]byte, []int) {
	return file_core_core_fulfillment_proto_rawDescGZIP(), []int{10}
}

func (x *BatchGetMachinesByIDsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type BatchGetMachinesByIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Machines      []*MachineInfo         `protobuf:"bytes,1,rep,name=machines,proto3" json:"machines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetMachinesByIDsResponse) Reset() {
	*x = BatchGetMachinesByIDsResponse{}
	mi := &file_core_core_fulfillment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetMachinesByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetMachinesByIDsResponse) ProtoMessage() {}

func (x *BatchGetMachinesByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_fulfillment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetMachinesByIDsResponse.ProtoReflect.Descriptor instead.
func (*BatchGetMachinesByIDsResponse) Descriptor() ([]byte, []int) {
	return file_core_core_fulfillment_proto_rawDescGZIP(), []int{11}
}

func (x *BatchGetMachinesByIDsResponse) GetMachines() []*MachineInfo {
	if x != nil {
		return x.Machines
	}
	return nil
}

type ListMachineStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AsOf          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=as_of,json=asOf,proto3,oneof" json:"as_of,omitempty"`
	DepartmentIds []string               `protobuf:"bytes,2,rep,name=department_ids,json=departmentIds,proto3" json:"department_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMachineStatusRequest) Reset() {
	*x = ListMachineStatusRequest{}
	mi := &file_core_core_fulfillment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMachineStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMachineStatusRequest) ProtoMessage() {}

func (x *ListMachineStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_fulfillment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMachineStatusRequest.ProtoReflect.Descriptor instead.
func (*ListMachineStatusRequest) Descriptor() ([]byte, []int) {
	return file_core_core_fulfillment_proto_rawDescGZIP(), []int{12}
}

func (x *ListMachineStatusRequest) GetAsOf() *timestamppb.Timestamp {
	if x != nil {
		return x.AsOf
	}
	return nil
}

func (x *ListMachineStatusRequest) GetDepartmentIds() []string {
	if x != nil {
		return x.DepartmentIds
	}
	return nil
}

// MachineCampaignInfo is one campaign on a machine with how far through it the floor is.
type MachineCampaignInfo struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ProductionScheduleLineId string                 `protobuf:"bytes,1,opt,name=production_schedule_line_id,json=productionScheduleLineId,proto3" json:"production_schedule_line_id,omitempty"`
	ItemId                   string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Sku                      string                 `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	WeekStartDate            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=week_start_date,json=weekStartDate,proto3" json:"week_start_date,omitempty"`
	WeekIndex                int32                  `protobuf:"varint,5,opt,name=week_index,json=weekIndex,proto3" json:"week_index,omitempty"`
	PlannedQuantity          float64                `protobuf:"fixed64,6,opt,name=planned_quantity,json=plannedQuantity,proto3" json:"planned_quantity,omitempty"`
	ScannedQuantity          float64                `protobuf:"fixed64,7,opt,name=scanned_quantity,json=scannedQuantity,proto3" json:"scanned_quantity,omitempty"`
	RemainingQuantity        float64                `protobuf:"fixed64,8,opt,name=remaining_quantity,json=remainingQuantity,proto3" json:"remaining_quantity,omitempty"`
	Unit                     *string                `protobuf:"bytes,9,opt,name=unit,proto3,oneof" json:"unit,omitempty"`
	ReleasedBatchCount       int64                  `protobuf:"varint,10,opt,name=released_batch_count,json=releasedBatchCount,proto3" json:"released_batch_count,omitempty"`
	ScannedBatchCount        int64                  `protobuf:"varint,11,opt,name=scanned_batch_count,json=scannedBatchCount,proto3" json:"scanned_batch_count,omitempty"`
	PlannedRunHours          float64                `protobuf:"fixed64,12,opt,name=planned_run_hours,json=plannedRunHours,proto3" json:"planned_run_hours,omitempty"`
	StatusCode               string                 `protobuf:"bytes,13,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ProductionRunId          *string                `protobuf:"bytes,14,opt,name=production_run_id,json=productionRunId,proto3,oneof" json:"production_run_id,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *MachineCampaignInfo) Reset() {
	*x = MachineCampaignInfo{}
	mi := &file_core_core_fulfillment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineCampaignInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineCampaignInfo) ProtoMessage() {}

func (x *MachineCampaignInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_fulfillment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineCampaignInfo.ProtoReflect.Descriptor instead.
func (*MachineCampaignInfo) Descriptor() ([]byte, []int) {
	return file_core_core_fulfillment_proto_rawDescGZIP(), []int{13}
}

func (x *MachineCampaignInfo) GetProductionScheduleLineId() string {
	if x != nil {
		return x.ProductionScheduleLineId
	}
	return ""
}

func (x *MachineCampaignInfo) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *MachineCampaignInfo) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *MachineCampaignInfo) GetWeekStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.WeekStartDate
	}
	return nil
}

func (x *MachineCampaignInfo) GetWeekIndex() int32 {
	if x != nil {
		return x.WeekIndex
	}
	return 0
}

func (x *MachineCampaignInfo) GetPlannedQuantity() float64 {
	if x != nil {
		return x.PlannedQuantity
	}
	return 0
}

func (x *MachineCampaignInfo) GetScannedQuantity() float64 {
	if x != nil {
		return x.ScannedQuantity
	}
	return 0
}

func (x *MachineCampaignInfo) GetRemainingQuantity() float64 {
	if x != nil {
		return x.RemainingQuantity
	}
	return 0
}

func (x *MachineCampaignInfo) GetUnit() string {
	if x != nil && x.Unit != nil {
		return *x.Unit
	}
	return ""
}

func (x *MachineCampaignInfo) GetReleasedBatchCount() int64 {
	if x != nil {
		return x.ReleasedBatchCount
	}
	return 0
}

func (x *MachineCampaignInfo) GetScannedBatchCount() int64 {
	if x != nil {
		return x.ScannedBatchCount
	}
	return 0
}

func (x *MachineCampaignInfo) GetPlannedRunHours() float64 {
	if x != nil {
		return x.PlannedRunHours
	}
	return 0
}

func (x *MachineCampaignInfo) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *MachineCampaignInfo) GetProductionRunId() string {
	if x != nil && x.ProductionRunId != nil {
		return *x.ProductionRunId
	}
	return ""
}

type MachineDowntimeSummaryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	ReasonName    string                 `protobuf:"bytes,3,opt,name=reason_name,json=reasonName,proto3" json:"reason_name,omitempty"`
	OeeBucket     string                 `protobuf:"bytes,4,opt,name=oee_bucket,json=oeeBucket,proto3" json:"oee_bucket,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Note          *string                `protobuf:"bytes,6,opt,name=note,proto3,oneof" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineDowntimeSummaryInfo) Reset() {
	*x = MachineDowntimeSummaryInfo{}
	mi := &file_core_core_fulfillment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineDowntimeSummaryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineDowntimeSummaryInfo) ProtoMessage() {}

func (x *MachineDowntimeSummaryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_fulfillment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineDowntimeSummaryInfo.ProtoReflect.Descriptor instead.
func (*MachineDowntimeSummaryInfo) Descriptor() ([]byte, []int) {
	return file_core_core_fulfillment_proto_rawDescGZIP(), []int{14}
}

func (x *MachineDowntimeSummaryInfo) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *MachineDowntimeSummaryInfo) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *MachineDowntimeSummaryInfo) GetReasonName() string {
	if x != nil {
		return x.ReasonName
	}
	return ""
}

func (x *MachineDowntimeSummaryInfo) GetOeeBucket() string {
	if x != nil {
		return x.OeeBucket
	}
	return ""
}

func (x *MachineDowntimeSummaryInfo) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *MachineDowntimeSummaryInfo) GetNote() string {
	if x != nil && x.Note != nil {
		return *x.Note
	}
	return ""
}

type MachineStatusInfo struct {
	state               protoimpl.MessageState      `protogen:"open.v1"`
	MachineId           string                      `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	MachineName         string                      `protobuf:"bytes,2,opt,name=machine_name,json=machineName,proto3" json:"machine_name,omitempty"`
	DepartmentId        *string                     `protobuf:"bytes,3,opt,name=department_id,json=departmentId,proto3,oneof" json:"department_id,omitempty"`
	DepartmentName      *string                     `protobuf:"bytes,4,opt,name=department_name,json=departmentName,proto3,oneof" json:"department_name,omitempty"`
	Status              string                      `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Downtime            *MachineDowntimeSummaryInfo `protobuf:"bytes,6,opt,name=downtime,proto3,oneof" json:"downtime,omitempty"`
	Current             *MachineCampaignInfo        `protobuf:"bytes,7,opt,name=current,proto3,oneof" json:"current,omitempty"`
	Next                *MachineCampaignInfo        `protobuf:"bytes,8,opt,name=next,proto3,oneof" json:"next,omitempty"`
	WeekPlannedQuantity float64                     `protobuf:"fixed64,9,opt,name=week_planned_quantity,json=weekPlannedQuantity,proto3" json:"week_planned_quantity,omitempty"`
	WeekScannedQuantity float64                     `protobuf:"fixed64,10,opt,name=week_scanned_quantity,json=weekScannedQuantity,proto3" json:"week_scanned_quantity,omitempty"`
	WeekPlannedRunHours float64                     `protobuf:"fixed64,11,opt,name=week_planned_run_hours,json=weekPlannedRunHours,proto3" json:"week_planned_run_hours,omitempty"`
	Unit                *string                     `protobuf:"bytes,12,opt,name=unit,proto3,oneof" json:"unit,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MachineStatusInfo) Reset() {
	*x = MachineStatusInfo{}
	mi := &file_core_core_fulfillment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineStatusInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineStatusInfo) ProtoMessage() {}

func (x *MachineStatusInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_fulfillment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineStatusInfo.ProtoReflect.Descriptor instead.
func (*MachineStatusInfo) Descriptor() ([]byte, []int) {
	return file_core_core_fulfillment_proto_rawDescGZIP(), []int{15}
}

func (x *MachineStatusInfo) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *MachineStatusInfo) GetMachineName() string {
	if x != nil {
		return x.MachineName
	}
	return ""
}

func (x *MachineStatusInfo) GetDepartmentId() string {
	if x != nil && x.DepartmentId != nil {
		return *x.DepartmentId
	}
	return ""
}

func (x *MachineStatusInfo) GetDepartmentName() string {
	if x != nil && x.DepartmentName != nil {
		return *x.DepartmentName
	}
	return ""
}

func (x *MachineStatusInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MachineStatusInfo) GetDowntime() *MachineDowntimeSummaryInfo {
	if x != nil {
		return x.Downtime
	}
	return nil
}

func (x *MachineStatusInfo) GetCurrent() *MachineCampaignInfo {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *MachineStatusInfo) GetNext() *MachineCampaignInfo {
	if x != nil {
		return x.Next
	}
	return nil
}

func (x *MachineStatusInfo) GetWeekPlannedQuantity() float64 {
	if x != nil {
		return x.WeekPlannedQuantity
	}
	return 0
}

func (x *MachineStatusInfo) GetWeekScannedQuantity() float64 {
	if x != nil {
		return x.WeekScannedQuantity
	}
	return 0
}

func (x *MachineStatusInfo) GetWeekPlannedRunHours() float64 {
	if x != nil {
		return x.WeekPlannedRunHours
	}
	return 0
}

func (x *MachineStatusInfo) GetUnit() string {
	if x != nil && x.Unit != nil {
		return *x.Unit
	}
	return ""
}

type ListMachineStatusResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ProductionScheduleId *string                `protobuf:"bytes,1,opt,name=production_schedule_id,json=productionScheduleId,proto3,oneof" json:"production_schedule_id,omitempty"`
	WeekStartDate        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=week_start_date,json=weekStartDate,proto3" json:"week_start_date,omitempty"`
	Machines             []*MachineStatusInfo   `protobuf:"bytes,3,rep,name=machines,proto3" json:"machines,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ListMachineStatusResponse) Reset() {
	*x = ListMachineStatusResponse{}
	mi := &file_core_core_fulfillment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMachineStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMachineStatusResponse) ProtoMessage() {}

func (x *ListMachineStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_fulfillment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMachineStatusResponse.ProtoReflect.Descriptor instead.
func (*ListMachineStatusResponse) Descriptor() ([]byte, []int) {
	return file_core_core_fulfillment_proto_rawDescGZIP(), []int{16}
}

func (x *ListMachineStatusResponse) GetProductionScheduleId() string {
	if x != nil && x.ProductionScheduleId != nil {
		return *x.ProductionScheduleId
	}
	return ""
}

func (x *ListMachineStatusResponse) GetWeekStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.WeekStartDate
	}
	return nil
}

func (x *ListMachineStatusResponse) GetMachines() []*MachineStatusInfo {
	if x != nil {
		return x.Machines
	}
	return nil
}

var File_core_core_fulfillment_proto protoreflect.FileDescriptor

const file_core_core_fulfillment_proto_rawDesc = "" +
	"\n" +
	"\x1bcore/core_fulfillment.proto\x12\x04core\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0fcore/core.proto\"\xcd\x04\n" +
	"\vMachineInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rserial_number\x18\x03 \x01(\tR\fserialNumber\x12\x19\n" +
	"\x05notes\x18\x04 \x01(\tH\x00R\x05notes\x88\x01\x01\x12(\n" +
	"\rdepartment_id\x18\x05 \x01(\tH\x01R\fdepartmentId\x88\x01\x01\x12,\n" +
	"\x0fdepartment_name\x18\x06 \x01(\tH\x02R\x0edepartmentName\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12S\n" +
	"\x15department_created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x03R\x13departmentCreatedAt\x88\x01\x01\x12S\n" +
	"\x15department_updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampH\x04R\x13departmentUpdatedAt\x88\x01\x01B\b\n" +
	"\x06_notesB\x10\n" +
	"\x0e_department_idB\x12\n" +
	"\x10_department_nameB\x18\n" +
	"\x16_department_created_atB\x18\n" +
	"\x16_department_updated_at\"\x94\x01\n" +
	"\x13ListMachinesRequest\x12\x1b\n" +
	"\x06cursor\x18\x01 \x01(\tH\x00R\x06cursor\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x19\n" +
	"\x05query\x18\x03 \x01(\tH\x01R\x05query\x88\x01\x01\x12\x1a\n" +
	"\bincludes\x18\x04 \x03(\tR\bincludesB\t\n" +
	"\a_cursorB\b\n" +
	"\x06_query\"r\n" +
	"\x14ListMachinesResponse\x12-\n" +
	"\bmachines\x18\x01 \x03(\v2\x11.core.MachineInfoR\bmachines\x12+\n" +
	"\tpage_info\x18\x02 \x01(\v2\x0e.core.PageInfoR\bpageInfo\"?\n" +
	"\x11GetMachineRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bincludes\x18\x02 \x03(\tR\bincludes\"A\n" +
	"\x12GetMachineResponse\x12+\n" +
	"\amachine\x18\x01 \x01(\v2\x11.core.MachineInfoR\amachine\"\xb5\x01\n" +
	"\x14CreateMachineRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\x12\x19\n" +
	"\x05notes\x18\x03 \x01(\tH\x00R\x05notes\x88\x01\x01\x12#\n" +
	"\rdepartment_id\x18\x04 \x01(\tR\fdepartmentId\x12\x1a\n" +
	"\bincludes\x18\x05 \x03(\tR\bincludesB\b\n" +
	"\x06_notes\"D\n" +
	"\x15CreateMachineResponse\x12+\n" +
	"\amachine\x18\x01 \x01(\v2\x11.core.MachineInfoR\amachine\"\xc5\x01\n" +
	"\x14UpdateMachineRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12(\n" +
	"\rserial_number\x18\x03 \x01(\tH\x01R\fserialNumber\x88\x01\x01\x12\x19\n" +
	"\x05notes\x18\x04 \x01(\tH\x02R\x05notes\x88\x01\x01\x12\x1a\n" +
	"\bincludes\x18\x05 \x03(\tR\bincludesB\a\n" +
	"\x05_nameB\x10\n" +
	"\x0e_serial_numberB\b\n" +
	"\x06_notes\"D\n" +
	"\x15UpdateMachineResponse\x12+\n" +
	"\amachine\x18\x01 \x01(\v2\x11.core.MachineInfoR\amachine\"&\n" +
	"\x14DeleteMachineRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x1cBatchGetMachinesByIDsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"N\n" +
	"\x1dBatchGetMachinesByIDsResponse\x12-\n" +
	"\bmachines\x18\x01 \x03(\v2\x11.core.MachineInfoR\bmachines\"\x81\x01\n" +
	"\x18ListMachineStatusRequest\x124\n" +
	"\x05as_of\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x04asOf\x88\x01\x01\x12%\n" +
	"\x0edepartment_ids\x18\x02 \x03(\tR\rdepartmentIdsB\b\n" +
	"\x06_as_of\"\xff\x04\n" +
	"\x13MachineCampaignInfo\x12=\n" +
	"\x1bproduction_schedule_line_id\x18\x01 \x01(\tR\x18productionScheduleLineId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\x12B\n" +
	"\x0fweek_start_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rweekStartDate\x12\x1d\n" +
	"\n" +
	"week_index\x18\x05 \x01(\x05R\tweekIndex\x12)\n" +
	"\x10planned_quantity\x18\x06 \x01(\x01R\x0fplannedQuantity\x12)\n" +
	"\x10scanned_quantity\x18\a \x01(\x01R\x0fscannedQuantity\x12-\n" +
	"\x12remaining_quantity\x18\b \x01(\x01R\x11remainingQuantity\x12\x17\n" +
	"\x04unit\x18\t \x01(\tH\x00R\x04unit\x88\x01\x01\x120\n" +
	"\x14released_batch_count\x18\n" +
	" \x01(\x03R\x12releasedBatchCount\x12.\n" +
	"\x13scanned_batch_count\x18\v \x01(\x03R\x11scannedBatchCount\x12*\n" +
	"\x11planned_run_hours\x18\f \x01(\x01R\x0fplannedRunHours\x12\x1f\n" +
	"\vstatus_code\x18\r \x01(\tR\n" +
	"statusCode\x12/\n" +
	"\x11production_run_id\x18\x0e \x01(\tH\x01R\x0fproductionRunId\x88\x01\x01B\a\n" +
	"\x05_unitB\x14\n" +
	"\x12_production_run_id\"\xec\x01\n" +
	"\x1aMachineDowntimeSummaryInfo\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1f\n" +
	"\vreason_name\x18\x03 \x01(\tR\n" +
	"reasonName\x12\x1d\n" +
	"\n" +
	"oee_bucket\x18\x04 \x01(\tR\toeeBucket\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12\x17\n" +
	"\x04note\x18\x06 \x01(\tH\x00R\x04note\x88\x01\x01B\a\n" +
	"\x05_note\"\xfd\x04\n" +
	"\x11MachineStatusInfo\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12!\n" +
	"\fmachine_name\x18\x02 \x01(\tR\vmachineName\x12(\n" +
	"\rdepartment_id\x18\x03 \x01(\tH\x00R\fdepartmentId\x88\x01\x01\x12,\n" +
	"\x0fdepartment_name\x18\x04 \x01(\tH\x01R\x0edepartmentName\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12A\n" +
	"\bdowntime\x18\x06 \x01(\v2 .core.MachineDowntimeSummaryInfoH\x02R\bdowntime\x88\x01\x01\x128\n" +
	"\acurrent\x18\a \x01(\v2\x19.core.MachineCampaignInfoH\x03R\acurrent\x88\x01\x01\x122\n" +
	"\x04next\x18\b \x01(\v2\x19.core.MachineCampaignInfoH\x04R\x04next\x88\x01\x01\x122\n" +
	"\x15week_planned_quantity\x18\t \x01(\x01R\x13weekPlannedQuantity\x122\n" +
	"\x15week_scanned_quantity\x18\n" +
	" \x01(\x01R\x13weekScannedQuantity\x123\n" +
	"\x16week_planned_run_hours\x18\v \x01(\x01R\x13weekPlannedRunHours\x12\x17\n" +
	"\x04unit\x18\f \x01(\tH\x05R\x04unit\x88\x01\x01B\x10\n" +
	"\x0e_department_idB\x12\n" +
	"\x10_department_nameB\v\n" +
	"\t_downtimeB\n" +
	"\n" +
	"\b_currentB\a\n" +
	"\x05_nextB\a\n" +
	"\x05_unit\"\xea\x01\n" +
	"\x19ListMachineStatusResponse\x129\n" +
	"\x16production_schedule_id\x18\x01 \x01(\tH\x00R\x14productionScheduleId\x88\x01\x01\x12B\n" +
	"\x0fweek_start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\rweekStartDate\x123\n" +
	"\bmachines\x18\x03 \x03(\v2\x17.core.MachineStatusInfoR\bmachinesB\x19\n" +
	"\x17_production_schedule_id2\xb1\x04\n" +
	"\x16CoreFulfillmentService\x12E\n" +
	"\fListMachines\x12\x19.core.ListMachinesRequest\x1a\x1a.core.ListMachinesResponse\x12?\n" +
	"\n" +
	"GetMachine\x12\x17.core.GetMachineRequest\x1a\x18.core.GetMachineResponse\x12T\n" +
	"\x11ListMachineStatus\x12\x1e.core.ListMachineStatusRequest\x1a\x1f.core.ListMachineStatusResponse\x12H\n" +
	"\rCreateMachine\x12\x1a.core.CreateMachineRequest\x1a\x1b.core.CreateMachineResponse\x12H\n" +
	"\rUpdateMachine\x12\x1a.core.UpdateMachineRequest\x1a\x1b.core.UpdateMachineResponse\x12C\n" +
	"\rDeleteMachine\x12\x1a.core.DeleteMachineRequest\x1a\x16.google.protobuf.Empty\x12`\n" +
	"\x15BatchGetMachinesByIDs\x12\".core.BatchGetMachinesByIDsRequest\x1a#.core.BatchGetMachinesByIDsResponseB\x18Z\x16shared/proto/core;coreb\x06proto3"

var (
	file_core_core_fulfillment_proto_rawDescOnce sync.Once
	file_core_core_fulfillment_proto_rawDescData []byte
)

func file_core_core_fulfillment_proto_rawDescGZIP() []byte {
	file_core_core_fulfillment_proto_rawDescOnce.Do(func() {
		file_core_core_fulfillment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_core_fulfillment_proto_rawDesc), len(file_core_core_fulfillment_proto_rawDesc)))
	})
	return file_core_core_fulfillment_proto_rawDescData
}

var file_core_core_fulfillment_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_core_core_fulfillment_proto_goTypes = []any{
	(*MachineInfo)(nil),                   // 0: core.MachineInfo
	(*ListMachinesRequest)(nil),           // 1: core.ListMachinesRequest
	(*ListMachinesResponse)(nil),          // 2: core.ListMachinesResponse
	(*GetMachineRequest)(nil),             // 3: core.GetMachineRequest
	(*GetMachineResponse)(nil),            // 4: core.GetMachineResponse
	(*CreateMachineRequest)(nil),          // 5: core.CreateMachineRequest
	(*CreateMachineResponse)(nil),         // 6: core.CreateMachineResponse
	(*UpdateMachineRequest)(nil),          // 7: core.UpdateMachineRequest
	(*UpdateMachineResponse)(nil),         // 8: core.UpdateMachineResponse
	(*DeleteMachineRequest)(nil),          // 9: core.DeleteMachineRequest
	(*BatchGetMachinesByIDsRequest)(nil),  // 10: core.BatchGetMachinesByIDsRequest
	(*BatchGetMachinesByIDsResponse)(nil), // 11: core.BatchGetMachinesByIDsResponse
	(*ListMachineStatusRequest)(nil),      // 12: core.ListMachineStatusRequest
	(*MachineCampaignInfo)(nil),           // 13: core.MachineCampaignInfo
	(*MachineDowntimeSummaryInfo)(nil),    // 14: core.MachineDowntimeSummaryInfo
	(*MachineStatusInfo)(nil),             // 15: core.MachineStatusInfo
	(*ListMachineStatusResponse)(nil),     // 16: core.ListMachineStatusResponse
	(*timestamppb.Timestamp)(nil),         // 17: google.protobuf.Timestamp
	(*PageInfo)(nil),                      // 18: core.PageInfo
	(*emptypb.Empty)(nil),                 // 19: google.protobuf.Empty
}
var file_core_core_fulfillment_proto_depIdxs = []int32{
	17, // 0: core.MachineInfo.created_at:type_name -> google.protobuf.Timestamp
	17, // 1: core.MachineInfo.updated_at:type_name -> google.protobuf.Timestamp
	17, // 2: core.MachineInfo.department_created_at:type_name -> google.protobuf.Timestamp
	17, // 3: core.MachineInfo.department_updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: core.ListMachinesResponse.machines:type_name -> core.MachineInfo
	18, // 5: core.ListMachinesResponse.page_info:type_name -> core.PageInfo
	0,  // 6: core.GetMachineResponse.machine:type_name -> core.MachineInfo
	0,  // 7: core.CreateMachineResponse.machine:type_name -> core.MachineInfo
	0,  // 8: core.UpdateMachineResponse.machine:type_name -> core.MachineInfo
	0,  // 9: core.BatchGetMachinesByIDsResponse.machines:type_name -> core.MachineInfo
	17, // 10: core.ListMachineStatusRequest.as_of:type_name -> google.protobuf.Timestamp
	17, // 11: core.MachineCampaignInfo.week_start_date:type_name -> google.protobuf.Timestamp
	17, // 12: core.MachineDowntimeSummaryInfo.started_at:type_name -> google.protobuf.Timestamp
	14, // 13: core.MachineStatusInfo.downtime:type_name -> core.MachineDowntimeSummaryInfo
	13, // 14: core.MachineStatusInfo.current:type_name -> core.MachineCampaignInfo
	13, // 15: core.MachineStatusInfo.next:type_name -> core.MachineCampaignInfo
	17, // 16: core.ListMachineStatusResponse.week_start_date:type_name -> google.protobuf.Timestamp
	15, // 17: core.ListMachineStatusResponse.machines:type_name -> core.MachineStatusInfo
	1,  // 18: core.CoreFulfillmentService.ListMachines:input_type -> core.ListMachinesRequest
	3,  // 19: core.CoreFulfillmentService.GetMachine:input_type -> core.GetMachineRequest
	12, // 20: core.CoreFulfillmentService.ListMachineStatus:input_type -> core.ListMachineStatusRequest
	5,  // 21: core.CoreFulfillmentService.CreateMachine:input_type -> core.CreateMachineRequest
	7,  // 22: core.CoreFulfillmentService.UpdateMachine:input_type -> core.UpdateMachineRequest
	9,  // 23: core.CoreFulfillmentService.DeleteMachine:input_type -> core.DeleteMachineRequest
	10, // 24: core.CoreFulfillmentService.BatchGetMachinesByIDs:input_type -> core.BatchGetMachinesByIDsRequest
	2,  // 25: core.CoreFulfillmentService.ListMachines:output_type -> core.ListMachinesResponse
	4,  // 26: core.CoreFulfillmentService.GetMachine:output_type -> core.GetMachineResponse
	16, // 27: core.CoreFulfillmentService.ListMachineStatus:output_type -> core.ListMachineStatusResponse
	6,  // 28: core.CoreFulfillmentService.CreateMachine:output_type -> core.CreateMachineResponse
	8,  // 29: core.CoreFulfillmentService.UpdateMachine:output_type -> core.UpdateMachineResponse
	19, // 30: core.CoreFulfillmentService.DeleteMachine:output_type -> google.protobuf.Empty
	11, // 31: core.CoreFulfillmentService.BatchGetMachinesByIDs:output_type -> core.BatchGetMachinesByIDsResponse
	25, // [25:32] is the sub-list for method output_type
	18, // [18:25] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_core_core_fulfillment_proto_init() }
func file_core_core_fulfillment_proto_init() {
	if File_core_core_fulfillment_proto != nil {
		return
	}
	file_core_core_proto_init()
	file_core_core_fulfillment_proto_msgTypes[0].OneofWrappers = []any{}
	file_core_core_fulfillment_proto_msgTypes[1].OneofWrappers = []any{}
	file_core_core_fulfillment_proto_msgTypes[5].OneofWrappers = []any{}
	file_core_core_fulfillment_proto_msgTypes[7].OneofWrappers = []any{}
	file_core_core_fulfillment_proto_msgTypes[12].OneofWrappers = []any{}
	file_core_core_fulfillment_proto_msgTypes[13].OneofWrappers = []any{}
	file_core_core_fulfillment_proto_msgTypes[14].OneofWrappers = []any{}
	file_core_core_fulfillment_proto_msgTypes[15].OneofWrappers = []any{}
	file_core_core_fulfillment_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_core_fulfillment_proto_rawDesc), len(file_core_core_fulfillment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_core_fulfillment_proto_goTypes,
		DependencyIndexes: file_core_core_fulfillment_proto_depIdxs,
		MessageInfos:      file_core_core_fulfillment_proto_msgTypes,
	}.Build()
	File_core_core_fulfillment_proto = out.File
	file_core_core_fulfillment_proto_goTypes = nil
	file_core_core_fulfillment_proto_depIdxs = nil
}
