// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: core/core_document_settings.proto

// CoreService message types (imported by core.proto).

package core

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An account's customizations to one document type. id and the timestamps are unset for a type the account
// has never saved.
type DocumentSettingInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	DocumentType   string                 `protobuf:"bytes,2,opt,name=document_type,json=documentType,proto3" json:"document_type,omitempty"`
	ProcessOwner   *string                `protobuf:"bytes,3,opt,name=process_owner,json=processOwner,proto3,oneof" json:"process_owner,omitempty"`
	DocumentNumber *string                `protobuf:"bytes,4,opt,name=document_number,json=documentNumber,proto3,oneof" json:"document_number,omitempty"`
	Revision       *string                `protobuf:"bytes,5,opt,name=revision,proto3,oneof" json:"revision,omitempty"`
	FooterText     *string                `protobuf:"bytes,6,opt,name=footer_text,json=footerText,proto3,oneof" json:"footer_text,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DocumentSettingInfo) Reset() {
	*x = DocumentSettingInfo{}
	mi := &file_core_core_document_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentSettingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentSettingInfo) ProtoMessage() {}

func (x *DocumentSettingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_document_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentSettingInfo.ProtoReflect.Descriptor instead.
func (*DocumentSettingInfo) Descriptor() ([]byte, []int) {
	return file_core_core_document_settings_proto_rawDescGZIP(), []int{0}
}

func (x *DocumentSettingInfo) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *DocumentSettingInfo) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

func (x *DocumentSettingInfo) GetProcessOwner() string {
	if x != nil && x.ProcessOwner != nil {
		return *x.ProcessOwner
	}
	return ""
}

func (x *DocumentSettingInfo) GetDocumentNumber() string {
	if x != nil && x.DocumentNumber != nil {
		return *x.DocumentNumber
	}
	return ""
}

func (x *DocumentSettingInfo) GetRevision() string {
	if x != nil && x.Revision != nil {
		return *x.Revision
	}
	return ""
}

func (x *DocumentSettingInfo) GetFooterText() string {
	if x != nil && x.FooterText != nil {
		return *x.FooterText
	}
	return ""
}

func (x *DocumentSettingInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DocumentSettingInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListDocumentSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentSettingsRequest) Reset() {
	*x = ListDocumentSettingsRequest{}
	mi := &file_core_core_document_settings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentSettingsRequest) ProtoMessage() {}

func (x *ListDocumentSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_document_settings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentSettingsRequest.ProtoReflect.Descriptor instead.
func (*ListDocumentSettingsRequest) Descriptor() ([]byte, []int) {
	return file_core_core_document_settings_proto_rawDescGZIP(), []int{1}
}

type ListDocumentSettingsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DocumentSettings []*DocumentSettingInfo `protobuf:"bytes,1,rep,name=document_settings,json=documentSettings,proto3" json:"document_settings,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListDocumentSettingsResponse) Reset() {
	*x = ListDocumentSettingsResponse{}
	mi := &file_core_core_document_settings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentSettingsResponse) ProtoMessage() {}

func (x *ListDocumentSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_document_settings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentSettingsResponse.ProtoReflect.Descriptor instead.
func (*ListDocumentSettingsResponse) Descriptor() ([]byte, []int) {
	return file_core_core_document_settings_proto_rawDescGZIP(), []int{2}
}

func (x *ListDocumentSettingsResponse) GetDocumentSettings() []*DocumentSettingInfo {
	if x != nil {
		return x.DocumentSettings
	}
	return nil
}

type GetDocumentSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentType  string                 `protobuf:"bytes,1,opt,name=document_type,json=documentType,proto3" json:"document_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentSettingRequest) Reset() {
	*x = GetDocumentSettingRequest{}
	mi := &file_core_core_document_settings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentSettingRequest) ProtoMessage() {}

func (x *GetDocumentSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_document_settings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentSettingRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentSettingRequest) Descriptor() ([]byte, []int) {
	return file_core_core_document_settings_proto_rawDescGZIP(), []int{3}
}

func (x *GetDocumentSettingRequest) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

type GetDocumentSettingResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DocumentSetting *DocumentSettingInfo   `protobuf:"bytes,1,opt,name=document_setting,json=documentSetting,proto3" json:"document_setting,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetDocumentSettingResponse) Reset() {
	*x = GetDocumentSettingResponse{}
	mi := &file_core_core_document_settings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentSettingResponse) ProtoMessage() {}

func (x *GetDocumentSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_document_settings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentSettingResponse.ProtoReflect.Descriptor instead.
func (*GetDocumentSettingResponse) Descriptor() ([]byte, []int) {
	return file_core_core_document_settings_proto_rawDescGZIP(), []int{4}
}

func (x *GetDocumentSettingResponse) GetDocumentSetting() *DocumentSettingInfo {
	if x != nil {
		return x.DocumentSetting
	}
	return nil
}

type UpdateDocumentSettingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DocumentType   string                 `protobuf:"bytes,1,opt,name=document_type,json=documentType,proto3" json:"document_type,omitempty"`
	ProcessOwner   *StringPatch           `protobuf:"bytes,2,opt,name=process_owner,json=processOwner,proto3" json:"process_owner,omitempty"`
	DocumentNumber *StringPatch           `protobuf:"bytes,3,opt,name=document_number,json=documentNumber,proto3" json:"document_number,omitempty"`
	Revision       *StringPatch           `protobuf:"bytes,4,opt,name=revision,proto3" json:"revision,omitempty"`
	FooterText     *StringPatch           `protobuf:"bytes,5,opt,name=footer_text,json=footerText,proto3" json:"footer_text,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateDocumentSettingRequest) Reset() {
	*x = UpdateDocumentSettingRequest{}
	mi := &file_core_core_document_settings_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentSettingRequest) ProtoMessage() {}

func (x *UpdateDocumentSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_document_settings_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentSettingRequest.ProtoReflect.Descriptor instead.
func (*UpdateDocumentSettingRequest) Descriptor() ([]byte, []int) {
	return file_core_core_document_settings_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateDocumentSettingRequest) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

func (x *UpdateDocumentSettingRequest) GetProcessOwner() *StringPatch {
	if x != nil {
		return x.ProcessOwner
	}
	return nil
}

func (x *UpdateDocumentSettingRequest) GetDocumentNumber() *StringPatch {
	if x != nil {
		return x.DocumentNumber
	}
	return nil
}

func (x *UpdateDocumentSettingRequest) GetRevision() *StringPatch {
	if x != nil {
		return x.Revision
	}
	return nil
}

func (x *UpdateDocumentSettingRequest) GetFooterText() *StringPatch {
	if x != nil {
		return x.FooterText
	}
	return nil
}

type UpdateDocumentSettingResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DocumentSetting *DocumentSettingInfo   `protobuf:"bytes,1,opt,name=document_setting,json=documentSetting,proto3" json:"document_setting,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateDocumentSettingResponse) Reset() {
	*x = UpdateDocumentSettingResponse{}
	mi := &file_core_core_document_settings_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentSettingResponse) ProtoMessage() {}

func (x *UpdateDocumentSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_core_document_settings_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentSettingResponse.ProtoReflect.Descriptor instead.
func (*UpdateDocumentSettingResponse) Descriptor() ([]byte, []int) {
	return file_core_core_document_settings_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDocumentSettingResponse) GetDocumentSetting() *DocumentSettingInfo {
	if x != nil {
		return x.DocumentSetting
	}
	return nil
}

var File_core_core_document_settings_proto protoreflect.FileDescriptor

const file_core_core_document_settings_proto_rawDesc = "" +
	"\n" +
	"!core/core_document_settings.proto\x12\x04core\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15core/core_patch.proto\"\xd6\x03\n" +
	"\x13DocumentSettingInfo\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12#\n" +
	"\rdocument_type\x18\x02 \x01(\tR\fdocumentType\x12(\n" +
	"\rprocess_owner\x18\x03 \x01(\tH\x01R\fprocessOwner\x88\x01\x01\x12,\n" +
	"\x0fdocument_number\x18\x04 \x01(\tH\x02R\x0edocumentNumber\x88\x01\x01\x12\x1f\n" +
	"\brevision\x18\x05 \x01(\tH\x03R\brevision\x88\x01\x01\x12$\n" +
	"\vfooter_text\x18\x06 \x01(\tH\x04R\n" +
	"footerText\x88\x01\x01\x12>\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x05R\tcreatedAt\x88\x01\x01\x12>\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x06R\tupdatedAt\x88\x01\x01B\x05\n" +
	"\x03_idB\x10\n" +
	"\x0e_process_ownerB\x12\n" +
	"\x10_document_numberB\v\n" +
	"\t_revisionB\x0e\n" +
	"\f_footer_textB\r\n" +
	"\v_created_atB\r\n" +
	"\v_updated_at\"\x1d\n" +
	"\x1bListDocumentSettingsRequest\"f\n" +
	"\x1cListDocumentSettingsResponse\x12F\n" +
	"\x11document_settings\x18\x01 \x03(\v2\x19.core.DocumentSettingInfoR\x10documentSettings\"@\n" +
	"\x19GetDocumentSettingRequest\x12#\n" +
	"\rdocument_type\x18\x01 \x01(\tR\fdocumentType\"b\n" +
	"\x1aGetDocumentSettingResponse\x12D\n" +
	"\x10document_setting\x18\x01 \x01(\v2\x19.core.DocumentSettingInfoR\x0fdocumentSetting\"\x9a\x02\n" +
	"\x1cUpdateDocumentSettingRequest\x12#\n" +
	"\rdocument_type\x18\x01 \x01(\tR\fdocumentType\x126\n" +
	"\rprocess_owner\x18\x02 \x01(\v2\x11.core.StringPatchR\fprocessOwner\x12:\n" +
	"\x0fdocument_number\x18\x03 \x01(\v2\x11.core.StringPatchR\x0edocumentNumber\x12-\n" +
	"\brevision\x18\x04 \x01(\v2\x11.core.StringPatchR\brevision\x122\n" +
	"\vfooter_text\x18\x05 \x01(\v2\x11.core.StringPatchR\n" +
	"footerText\"e\n" +
	"\x1dUpdateDocumentSettingResponse\x12D\n" +
	"\x10document_setting\x18\x01 \x01(\v2\x19.core.DocumentSettingInfoR\x0fdocumentSettingB\x18Z\x16shared/proto/core;coreb\x06proto3"

var (
	file_core_core_document_settings_proto_rawDescOnce sync.Once
	file_core_core_document_settings_proto_rawDescData []byte
)

func file_core_core_document_settings_proto_rawDescGZIP() []byte {
	file_core_core_document_settings_proto_rawDescOnce.Do(func() {
		file_core_core_document_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_core_document_settings_proto_rawDesc), len(file_core_core_document_settings_proto_rawDesc)))
	})
	return file_core_core_document_settings_proto_rawDescData
}

var file_core_core_document_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_core_core_document_settings_proto_goTypes = []any{
	(*DocumentSettingInfo)(nil),           // 0: core.DocumentSettingInfo
	(*ListDocumentSettingsRequest)(nil),   // 1: core.ListDocumentSettingsRequest
	(*ListDocumentSettingsResponse)(nil),  // 2: core.ListDocumentSettingsResponse
	(*GetDocumentSettingRequest)(nil),     // 3: core.GetDocumentSettingRequest
	(*GetDocumentSettingResponse)(nil),    // 4: core.GetDocumentSettingResponse
	(*UpdateDocumentSettingRequest)(nil),  // 5: core.UpdateDocumentSettingRequest
	(*UpdateDocumentSettingResponse)(nil), // 6: core.UpdateDocumentSettingResponse
	(*timestamppb.Timestamp)(nil),         // 7: google.protobuf.Timestamp
	(*StringPatch)(nil),                   // 8: core.StringPatch
}
var file_core_core_document_settings_proto_depIdxs = []int32{
	7, // 0: core.DocumentSettingInfo.created_at:type_name -> google.protobuf.Timestamp
	7, // 1: core.DocumentSettingInfo.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: core.ListDocumentSettingsResponse.document_settings:type_name -> core.DocumentSettingInfo
	0, // 3: core.GetDocumentSettingResponse.document_setting:type_name -> core.DocumentSettingInfo
	8, // 4: core.UpdateDocumentSettingRequest.process_owner:type_name -> core.StringPatch
	8, // 5: core.UpdateDocumentSettingRequest.document_number:type_name -> core.StringPatch
	8, // 6: core.UpdateDocumentSettingRequest.revision:type_name -> core.StringPatch
	8, // 7: core.UpdateDocumentSettingRequest.footer_text:type_name -> core.StringPatch
	0, // 8: core.UpdateDocumentSettingResponse.document_setting:type_name -> core.DocumentSettingInfo
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_core_core_document_settings_proto_init() }
func file_core_core_document_settings_proto_init() {
	if File_core_core_document_settings_proto != nil {
		return
	}
	file_core_core_patch_proto_init()
	file_core_core_document_settings_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_core_document_settings_proto_rawDesc), len(file_core_core_document_settings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_core_document_settings_proto_goTypes,
		DependencyIndexes: file_core_core_document_settings_proto_depIdxs,
		MessageInfos:      file_core_core_document_settings_proto_msgTypes,
	}.Build()
	File_core_core_document_settings_proto = out.File
	file_core_core_document_settings_proto_goTypes = nil
	file_core_core_document_settings_proto_depIdxs = nil
}
