// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: core/core_shipping_case.proto

// Package core defines the gRPC service for shipping case management.

package core

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoreShippingCaseService_GetShippingCase_FullMethodName      = "/core.CoreShippingCaseService/GetShippingCase"
	CoreShippingCaseService_UpdateShippingCase_FullMethodName   = "/core.CoreShippingCaseService/UpdateShippingCase"
	CoreShippingCaseService_DeleteShippingCase_FullMethodName   = "/core.CoreShippingCaseService/DeleteShippingCase"
	CoreShippingCaseService_GetShippingCaseLabel_FullMethodName = "/core.CoreShippingCaseService/GetShippingCaseLabel"
)

// CoreShippingCaseServiceClient is the client API for CoreShippingCaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoreShippingCaseServiceClient interface {
	// GetShippingCase returns a single shipping case by its ID.
	GetShippingCase(ctx context.Context, in *GetShippingCaseRequest, opts ...grpc.CallOption) (*GetShippingCaseResponse, error)
	// UpdateShippingCase updates an existing shipping case.
	UpdateShippingCase(ctx context.Context, in *UpdateShippingCaseRequest, opts ...grpc.CallOption) (*UpdateShippingCaseResponse, error)
	// DeleteShippingCase deletes a shipping case.
	DeleteShippingCase(ctx context.Context, in *DeleteShippingCaseRequest, opts ...grpc.CallOption) (*DeleteShippingCaseResponse, error)
	// GetShippingCaseLabel returns a presigned URL for the shipping case's label.
	GetShippingCaseLabel(ctx context.Context, in *GetShippingCaseLabelRequest, opts ...grpc.CallOption) (*GetShippingCaseLabelResponse, error)
}

type coreShippingCaseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreShippingCaseServiceClient(cc grpc.ClientConnInterface) CoreShippingCaseServiceClient {
	return &coreShippingCaseServiceClient{cc}
}

func (c *coreShippingCaseServiceClient) GetShippingCase(ctx context.Context, in *GetShippingCaseRequest, opts ...grpc.CallOption) (*GetShippingCaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShippingCaseResponse)
	err := c.cc.Invoke(ctx, CoreShippingCaseService_GetShippingCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreShippingCaseServiceClient) UpdateShippingCase(ctx context.Context, in *UpdateShippingCaseRequest, opts ...grpc.CallOption) (*UpdateShippingCaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateShippingCaseResponse)
	err := c.cc.Invoke(ctx, CoreShippingCaseService_UpdateShippingCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreShippingCaseServiceClient) DeleteShippingCase(ctx context.Context, in *DeleteShippingCaseRequest, opts ...grpc.CallOption) (*DeleteShippingCaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteShippingCaseResponse)
	err := c.cc.Invoke(ctx, CoreShippingCaseService_DeleteShippingCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreShippingCaseServiceClient) GetShippingCaseLabel(ctx context.Context, in *GetShippingCaseLabelRequest, opts ...grpc.CallOption) (*GetShippingCaseLabelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShippingCaseLabelResponse)
	err := c.cc.Invoke(ctx, CoreShippingCaseService_GetShippingCaseLabel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreShippingCaseServiceServer is the server API for CoreShippingCaseService service.
// All implementations must embed UnimplementedCoreShippingCaseServiceServer
// for forward compatibility.
type CoreShippingCaseServiceServer interface {
	// GetShippingCase returns a single shipping case by its ID.
	GetShippingCase(context.Context, *GetShippingCaseRequest) (*GetShippingCaseResponse, error)
	// UpdateShippingCase updates an existing shipping case.
	UpdateShippingCase(context.Context, *UpdateShippingCaseRequest) (*UpdateShippingCaseResponse, error)
	// DeleteShippingCase deletes a shipping case.
	DeleteShippingCase(context.Context, *DeleteShippingCaseRequest) (*DeleteShippingCaseResponse, error)
	// GetShippingCaseLabel returns a presigned URL for the shipping case's label.
	GetShippingCaseLabel(context.Context, *GetShippingCaseLabelRequest) (*GetShippingCaseLabelResponse, error)
	mustEmbedUnimplementedCoreShippingCaseServiceServer()
}

// UnimplementedCoreShippingCaseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreShippingCaseServiceServer struct{}

func (UnimplementedCoreShippingCaseServiceServer) GetShippingCase(context.Context, *GetShippingCaseRequest) (*GetShippingCaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShippingCase not implemented")
}
func (UnimplementedCoreShippingCaseServiceServer) UpdateShippingCase(context.Context, *UpdateShippingCaseRequest) (*UpdateShippingCaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateShippingCase not implemented")
}
func (UnimplementedCoreShippingCaseServiceServer) DeleteShippingCase(context.Context, *DeleteShippingCaseRequest) (*DeleteShippingCaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteShippingCase not implemented")
}
func (UnimplementedCoreShippingCaseServiceServer) GetShippingCaseLabel(context.Context, *GetShippingCaseLabelRequest) (*GetShippingCaseLabelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShippingCaseLabel not implemented")
}
func (UnimplementedCoreShippingCaseServiceServer) mustEmbedUnimplementedCoreShippingCaseServiceServer() {
}
func (UnimplementedCoreShippingCaseServiceServer) testEmbeddedByValue() {}

// UnsafeCoreShippingCaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreShippingCaseServiceServer will
// result in compilation errors.
type UnsafeCoreShippingCaseServiceServer interface {
	mustEmbedUnimplementedCoreShippingCaseServiceServer()
}

func RegisterCoreShippingCaseServiceServer(s grpc.ServiceRegistrar, srv CoreShippingCaseServiceServer) {
	// If the following call panics, it indicates UnimplementedCoreShippingCaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreShippingCaseService_ServiceDesc, srv)
}

func _CoreShippingCaseService_GetShippingCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShippingCaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreShippingCaseServiceServer).GetShippingCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreShippingCaseService_GetShippingCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreShippingCaseServiceServer).GetShippingCase(ctx, req.(*GetShippingCaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreShippingCaseService_UpdateShippingCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateShippingCaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreShippingCaseServiceServer).UpdateShippingCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreShippingCaseService_UpdateShippingCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreShippingCaseServiceServer).UpdateShippingCase(ctx, req.(*UpdateShippingCaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreShippingCaseService_DeleteShippingCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteShippingCaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreShippingCaseServiceServer).DeleteShippingCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreShippingCaseService_DeleteShippingCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreShippingCaseServiceServer).DeleteShippingCase(ctx, req.(*DeleteShippingCaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreShippingCaseService_GetShippingCaseLabel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShippingCaseLabelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreShippingCaseServiceServer).GetShippingCaseLabel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreShippingCaseService_GetShippingCaseLabel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreShippingCaseServiceServer).GetShippingCaseLabel(ctx, req.(*GetShippingCaseLabelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreShippingCaseService_ServiceDesc is the grpc.ServiceDesc for CoreShippingCaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreShippingCaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.CoreShippingCaseService",
	HandlerType: (*CoreShippingCaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetShippingCase",
			Handler:    _CoreShippingCaseService_GetShippingCase_Handler,
		},
		{
			MethodName: "UpdateShippingCase",
			Handler:    _CoreShippingCaseService_UpdateShippingCase_Handler,
		},
		{
			MethodName: "DeleteShippingCase",
			Handler:    _CoreShippingCaseService_DeleteShippingCase_Handler,
		},
		{
			MethodName: "GetShippingCaseLabel",
			Handler:    _CoreShippingCaseService_GetShippingCaseLabel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core/core_shipping_case.proto",
}
