name: CD

on:
    release:
        types: [published]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version-file: go.mod
                  cache: true

            - name: Install Dependencies
              run: go mod download

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                  role-to-assume: arn:aws:iam::AWS_ACCOUNT_ID:role/github-action-role
                  aws-region: us-east-2

            - name: Build Docker images
              run: make docker-build-prod
              env:
                  AWS_REGION: "us-east-2"

            - name: Push Docker images
              run: make docker-push-prod
              env:
                  AWS_REGION: "us-east-2"

            - name: Deploy to EKS
              run: make deploy-prod
              env:
                  AWS_REGION: "us-east-2"
                  CLUSTER_NAME: "augno-prod"
